### ISSUE TITLE
Initiate Transaction FAILED, Please try Re-Initiating the Transaction. PLEASE APPROVE OPEN TXN FIRST [ExistingReferenceId:53247, Amount:37501] message is displayed when the user tries to place a transaction when the there is an open transaction at the store.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1002]
Actual result
Initiate Transaction FAILED, Please try Re-Initiating the Transaction. PLEASE APPROVE OPEN TXN FIRST [ExistingReferenceId:53247, Amount:37501] message is displayed when the user tries to place a transaction when the there is an open transaction at the store for POS and HK.com orders

Expected result
Message should be changed to "Close the open transactions to place a new order"

![image](https://user-images.githubusercontent.com/54023516/72046180-dae7b180-32dd-11ea-8d7a-b0326468ba81.png)

**Comment by sharangsamonkar** [comment]
Please close open transaction (PTRID: 1234, Amount: 452.21) before initiating a new transaction. <Link to open transactions UI - target blank>.

Also change the column name in UI from Plututs Transaction Id to PTRID.
