### ISSUE TITLE
Final payable amount should be displayed on the pinelab device.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1006]
Actual result 
Total Offer Price is displayed on the Pine Labs device.

Expected result
Final payable amount should be displayed on the pine labs device.

**Comment by shivam-kurtarkar** [comment]
amount is displayed. amount rounding requirements needs to be checked raise an issue

**Comment by larissa-c-d** [comment]
Final payable amount is the Rounded off value.

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/72412156-acad1a80-3792-11ea-8f94-b6091c9d8f19.png)
amount on the receipt is 3649.00

**Comment by sharangsamonkar** [comment]
Has been fixed
