### ISSUE TITLE
Transaction status is displayed as open on the POS screen while status is displayed as success on the open transaction UI.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1007]
Actual result
Transaction status id displayed as open on the POS screen while status is displayed as success on the open transaction UI.

Expected result
The transaction status should  be the same on the open transactions UI and the POS page.

![image](https://user-images.githubusercontent.com/54023516/72056527-cc57c500-32f2-11ea-9f2d-6e18048d181b.png)
![image](https://user-images.githubusercontent.com/54023516/72056593-ea252a00-32f2-11ea-85a6-b089dacc66c8.png)

**Comment by shivam-kurtarkar** [comment]
page needs to be refreshed. or try doing get status.

**Comment by sharangsamonkar** [comment]
Issue already fixed. Please check again.

**Comment by larissa-c-d** [comment]
Issue resolved
