### ISSUE TITLE
Transaction cancelled from the open transaction UI page should display cancelled status on the pos screen.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1010]
Actual result
when an open transaction is cancelled from the open transaction UI, and the get status button is clicked on the POS screen the transaction status is changed to Success.

Expected result
Transaction cancelled from the open transaction UI page should display cancelled status on the pos screen.

![image](https://user-images.githubusercontent.com/54023516/72061860-a59e8c00-32fc-11ea-92a6-c73918a504dc.png)
![image](https://user-images.githubusercontent.com/54023516/72061885-b4853e80-32fc-11ea-9a43-df247a2ade94.png)

**Steps**
Scan a barcode
choose the payment mode as credit/debit card.
click on initiate transaction on the POS
Go to the open transaction UI page
Click on cancel transaction
Go to the POS screen 
Click on Get payment status button.

**Comment by shivam-kurtarkar** [comment]
if debug is enabled get status marks it as success.
