### ISSUE TITLE
transaction can be void when void is false.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1013]
Actual result
The transaction can be void when the void is false.

Expected result
The transaction should not be when the void is set to false in the debug_table.The transaction should not be reverted.

**Steps**
Set the debug to false in the debug table
scan a barcode 
select the payment mode as Credit/debit card
click on initiate transaction 
Click on get status 
Click on cancel transaction

![image](https://user-images.githubusercontent.com/54023516/72064586-3330aa80-3302-11ea-911a-1070b8e2d4ea.png)
![image](https://user-images.githubusercontent.com/54023516/72064708-7559ec00-3302-11ea-9b8f-8cec4efb564f.png)

**Comment by shivam-kurtarkar** [comment]
setting value to null if failed

**Comment by shivam-kurtarkar** [comment]
forcePinelabsInitApiCall is global flag for init cancel and void
