### ISSUE TITLE
The status of the transaction is displayed when the get status is set to false.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1014]
Actual result
The status of the transaction is displayed when the get status is set to false.

Expected result
The status of the transaction should not be displayed when the get status is set to false.

![image](https://user-images.githubusercontent.com/54023516/72068517-3aa88180-330b-11ea-96e7-ca4a7b27ea28.png)
![image](https://user-images.githubusercontent.com/54023516/72068559-5b70d700-330b-11ea-9d4e-d0d473f23c43.png)

**Comment by shivam-kurtarkar** [comment]
debug code issue solved

**Comment by sharangsamonkar** [comment]
Issue fixed. Please check again.

**Comment by larissa-c-d** [comment]
Payment Pending.
Failed to get status
Status is displayed and also the failed message is displayed.
