### ISSUE TITLE
Multiple open transactions are allowed, for a store.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1017]
Actual result
Multiple open transactions are allowed, for a store.

Expected result
Multiple open transactions are are allowed for the store.

![image](https://user-images.githubusercontent.com/54023516/72128843-35dede80-339a-11ea-9d02-e6622c30100d.png)

**Comment by sharangsamonkar** [comment]
This issue was due to pinelabs device config change on PineLabs team end.
