### ISSUE TITLE
"Error Occured while cancelling transaction." message is displayed on the POS screen 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1018]
![image](https://user-images.githubusercontent.com/54023516/72129749-67a57480-339d-11ea-9d99-da4773f27e29.png)
![image](https://user-images.githubusercontent.com/54023516/72130639-2498d080-33a0-11ea-96d6-fc85cb4d87e4.png)
`[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (POSAction.java:2975) - Ajency.in :: Customer Order Transaction Id196
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:169) - Ajency.in :: cancelling transaction, id:196
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:193) - Ajency.in :: transaction already succeded making a void call id:196
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:194) - Ajency.in :: making void api call for transaction id:53365
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:526) - Ajency.in :: transaction number :1235848-1578635994532 amount:89908
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:255) - Ajency.in :: fetching pinelabs config for store 4034
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:546) - Ajency.in :: pinelabs params {"SecurityToken":"661c9a5f-5d7a-4d76-a950-68beb8225cfd","TransactionNumber":"1235848-1578635994532","TxnType":1,"AllowedPaymentMode":"1","OriginalPlutusTransactionReferenceID":53365,"UserID":15563757,"Amount":89908,"SequenceNumber":1,"MerchantStorePosCode":"04190588","IMEI":"IM239018","MerchantID":2300}
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:550) - Ajency.in :: making url call to  https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/UploadBilledTransaction
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (HkHttpClient.java:267) - Ajency.in :: parsing json response
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:561) - Ajency.in :: response code not handled
[ERROR] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:562) - Ajency.in :: Pinelabs api call :1 : VOID UPLOAD : ORIGINAL TXN IS CURRENTLY OPEN
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:569) - Ajency.in :: pinelabs response {"responseCode":1,"responseMessage":"VOID UPLOAD : ORIGINAL TXN IS CURRENTLY OPEN","plutusTransactionReferenceID":-4}
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:581) - Ajency.in :: resultset: true
[ INFO] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (ThirdPartyPaymentServiceImpl.java:584) - Ajency.in :: forcePinelabsVoidApiCall true active :false
[ERROR] [] [http-nio-8181-exec-7] (10 Jan 2020 11:34:16) (POSAction.java:2991) - Ajency.in :: Error occured when cancelling order status:3`

**Comment by shivam-kurtarkar** [comment]
now cancel api makes get status call looks like old bug.
