### ISSUE TITLE
payment mode is displayed as COD on the invoice, when the counter cash payment mode is selected on POS 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1032]
Actual result
payment mode is displayed as COD on the invoice, when the counter cash payment mode is selected on POS.

Expected result
counter cash payment mode should be displayed  on the invoice. 

![image](https://user-images.githubusercontent.com/54023516/72150908-c6361700-33cc-11ea-856e-a15bf8ddbd5b.png)
![image](https://user-images.githubusercontent.com/54023516/72150932-d6e68d00-33cc-11ea-92ad-0da7f24bc356.png)

**Comment by sharangsamonkar** [comment]
Not an issue. Counter cash is displayed as COD in invoice.

Can check master to confirm.
