### ISSUE TITLE
"This Cart is eligible for 1 Freebie(s)" pop up is displayed on click of  receive payment ,initiate transaction, cancel payment , get status button when the cart if eligible for a freebie

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1034]
Actual result
"This Cart is eligible for 1 Freebie(s)" pop up is displayed on click of  receive payment ,initiate transaction, cancel payment , get status button when the cart if eligible for a freebie.

Expected result
"This Cart is eligible for 1 Freebie(s)" pop up should not be displayed on click of  receive payment ,initiate transaction, cancel payment , get status button when the cart if eligible for a freebie

![image](https://user-images.githubusercontent.com/54023516/72232801-7b451b00-35e9-11ea-9728-c70dc0c6d0c3.png)

**Comment by sharangsamonkar** [comment]
In case there is no open transaction the pop up should be shown.

On receive payment, pop up should not come regardless.

**Comment by larissa-c-d** [comment]
popup is displayed on cancel button
