### ISSUE TITLE
permission to view/hide the Pinelab config section on the catalog retail store create/edit page not present.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1036]
Actual result
permission to view/hide the Pinelab config section on the catalog retail store create/edit page not present.

Expected result
permission to view/hide the Pinelab config section on the catalog retail store create/edit page should be  present.

![image](https://user-images.githubusercontent.com/54023516/72234996-c107e080-35f5-11ea-9e59-8d3cfc0696e6.png)

**Comment by sharangsamonkar** [comment]
Added permission 'PINELABS_CONFIG'
