### ISSUE TITLE
'Initiate Transaction FAILED, Please try Re-Initiating the Transaction. Failed to get pinelabs config' message is displayed when the enable pinelabs checkbox Is checked

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1040]
Actual result
'Initiate Transaction FAILED, Please try Re-Initiating the Transaction. Failed to get pinelabs config' message is displayed when the enable pinelabs checkbox Is checked

Expected result
The user should be able to initiate the transaction 

Store:Mum Bandra
Scan the Item 
Enter the details 
click on initiate transaction

![image](https://user-images.githubusercontent.com/54023516/72236951-c1f14000-35fe-11ea-9a3e-42a665f7dbaf.png)
![image](https://user-images.githubusercontent.com/54023516/72236974-ddf4e180-35fe-11ea-8039-3b4fd499a632.png)
![image](https://user-images.githubusercontent.com/54023516/72236989-e8af7680-35fe-11ea-942c-741512138daf.png)
![image](https://user-images.githubusercontent.com/54023516/72237001-f49b3880-35fe-11ea-8fb1-db49029f8eeb.png)

**Comment by sharangsamonkar** [comment]
basically the details are not synced from catalog to aqua

**Comment by sharangsamonkar** [comment]
similar to #1041
