### ISSUE TITLE
No entry is made in the store_pinelabs_config table when a new retail store is created with pinelabs config details.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1043]
Actual result
No entry is made in the store_pinelabs_config table when a new retail store is created with pinelabs config details.

Expected result the Entry should be made in the store_pinelabs_config table when a new retail store is created with pinelabs config details.

![image](https://user-images.githubusercontent.com/54023516/72238772-d0daf100-3604-11ea-9761-1750663c9928.png)
![image](https://user-images.githubusercontent.com/54023516/72238781-dd5f4980-3604-11ea-8a3c-88d3a55b3a40.png)
![image](https://user-images.githubusercontent.com/54023516/72238821-fa941800-3604-11ea-9ec4-cfb25e20e6d4.png)

**Comment by sharangsamonkar** [comment]
Sync issue #1041
