### ISSUE TITLE
Enable pinelabs config, Store I M E I, Merchant Store Pos Code fields should be compulsory fields if the credit/debit card mode is activated for the store.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1044]
Expected  result
Enable pinelabs config, Store I M E I, Merchant Store Pos Code fields should be compulsory fields if the credit/debit card mode is activated for the store.

![image](https://user-images.githubusercontent.com/54023516/72239311-9ffbbb80-3606-11ea-8dcc-8e0743447431.png)

**Comment by shivam-kurtarkar** [comment]
they are made compulsory if pinelabs config is enabled.  @sharangsamonkar

**Comment by sharangsamonkar** [comment]
@larissa this should be the behavior. If Pinelabs is enabled, then
compulsory. Regardless of card payment mode is selected or not.

Reason for this: sis stores have card payment but no pinelabs.

Please close the issue of the above is met.
