### ISSUE TITLE
On 3rd Attempt, if Transaction is still pending, the transaction is not cancelled

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1045]
Actual result
On 3rd Attempt, if Transaction is still pending, the transaction is not cancelled

expected result
 On 3rd Attempt, if Transaction is still pending, then the transaction should be Cancelled and the message “Payment Cancelled/Reverted, Please try Re-Initiating the Transaction” should be displayed.

Go to the POS screen
Enter the details
Scan a barcode
choose the payment mode as credit/debit card
Click on initiate payment 
Click on get status button thrice.

**Comment by sharangsamonkar** [comment]
Good catch!

**Comment by rohan-morje** [comment]
Transaction is not getting cancelled when clicked on get Status button more than 3 times
