### ISSUE TITLE
HK.com transaction can be initiated without scanning the barcode. 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1048]
Actual result
HK.com transaction can be initiated without scanning the barcode. 

Expected result
HK.com transaction should not be initiated  without scanning the barcode. 

![image](https://user-images.githubusercontent.com/54023516/72247287-911f0400-361a-11ea-8f99-4328a195a548.png)

**Comment by sharangsamonkar** [comment]
Can the order be placed?

**Comment by sharangsamonkar** [comment]
If the order cant be placed, the SM can always cancel the payment later.

**Comment by larissa-c-d** [comment]
HK.com transaction can be initiated without scanning the barcode.

**Comment by shivam-kurtarkar** [comment]
should placing order be stopped if items not checked out @sharangsamonkar ?
