### ISSUE TITLE
Green tick mark is not displayed for split payment when Transaction is Success, and the payment mode is credit/Debit card on  HK.com checkout page

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1049]
Actual result
 Green tick mark is not displayed for split payment when Transaction is Success, and the payment mode is credit/Debit card  on HK.com checkout page.

Expected result
Green tick mark should be displayed for split payment when Transaction is Success, and the payment mode is credit/Debit card on HK.com checkout page..

![image](https://user-images.githubusercontent.com/54023516/72249602-b3675080-361f-11ea-8695-a517acbb8a6b.png)

**Comment by shivam-kurtarkar** [comment]
SUCCESS Tag is added instead

**Comment by larissa-c-d** [comment]
Green tick mark is displayed for normal orders and not displayed for split payment mode
![image](https://user-images.githubusercontent.com/54023516/72590720-70a9bf00-3924-11ea-851c-cfb7cb6fdd8d.png)
![image](https://user-images.githubusercontent.com/54023516/72590741-80290800-3924-11ea-85ff-a4683801b8f7.png)

**Comment by rohan-morje** [comment]
Works for credit card
