### ISSUE TITLE
UPI via EDC machine payment mode not displayed on the checkout page for Hk.com

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1050]
Actual result
UPI via EDC machine payment mode not displayed on the checkout page for Hk.com

Expected result
UPI via EDC machine payment mode should be displayed on the checkout page for Hk.com

![Screenshot from 2020-01-13 15-53-14](https://user-images.githubusercontent.com/54023516/72250025-b1ea5800-3620-11ea-8ded-af993177c711.png)

**Comment by sharangsamonkar** [comment]
Not an issue. UPI and Paytm Voucher are not shown for HK.com orders

**Comment by rohan-morje** [comment]
UPI via EDC machine displaying for HK.com orders

![image](https://user-images.githubusercontent.com/14803102/72410115-9f416180-378d-11ea-97c0-889159b2c4f4.png)

**Comment by rohan-morje** [comment]
Not able tto verify on master due to nulll pointer issue

**Comment by larissa-c-d** [comment]
UPI via EDC Machine should be displayed for HK.com order, but should not be displayed in case the payment mode is split on hk.com  and same behaviour is observed on master @sharangsamonkar @rohan-morje

**Comment by rohan-morje** [comment]
UPI via EDC machine  should load for HK.com order .
