### ISSUE TITLE
"Error Occured while cancelling transaction." message should be changed to "Error Occurred while cancelling transaction."

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1053]
Actual result
Error Occured while cancelling transaction.

Expected result
Error Occurred while cancelling transaction.

![image](https://user-images.githubusercontent.com/54023516/72250893-b3b51b00-3622-11ea-9043-89247e2f9369.png)

**Comment by sharangsamonkar** [comment]
Need to change it to "Error occurred while cancelling transaction".
