### ISSUE TITLE
Previously selected payment mode is not displayed, in case of split payment

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1055]
Actual result
previously selected payment mode is not displayed, in case of split payment

Expected result
the payment modes selected should be displayed.
 
Select the payment mode as split payment 
Choose a payment mode
Click on add, and choose a payment mode
Remove the first selected payment mode
Click on add
Add a Payment mode
![image](https://user-images.githubusercontent.com/54023516/72251881-79e51400-3624-11ea-8ef2-1cf8835474d4.png)

**Comment by sharangsamonkar** [comment]
Need clarity on the issue.

**Comment by larissa-c-d** [comment]
After the steps are followed , out if the 2 payment modes selected for split payment, the first payment mode is not displayed.

**Comment by shivam-kurtarkar** [comment]
id gets messed up live issue i think
