### ISSUE TITLE
Invalid state with given pincode null message displayed is not correct when contact details are not entered

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1061]
Go to POS screen
Do not enter phone number
Scan the barcode and clcick on Recieve payment button

Actual result: Invalid state with given pincode null message displayed 

Expected: Enter the customer details message should display  

![image](https://user-images.githubusercontent.com/14803102/72257430-a6ebf380-3631-11ea-85bd-a09ad000772c.png)

**Comment by larissa-c-d** [comment]
does not exists on master.

**Comment by rohan-morje** [comment]
Invalid state with given pincode message is displayed when phone number not entered



![image](https://user-images.githubusercontent.com/14803102/72702599-4bfa5500-3b79-11ea-9d52-62c868dbd934.png)
