### ISSUE TITLE
Payment mode selected for split payment , get status,cancel payment buttons are not visible when clicked on initiate payment 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1065]
Actual result
Payment mode selected for split payment , get status,cancel payment buttons are not visible when clicked on initiate payment 

Expected result
Payment mode selected for split payment , get status,cancel payment buttons should be  visible when clicked on initiate payment 

![image](https://user-images.githubusercontent.com/54023516/72314555-659d2780-36b5-11ea-8818-f15e5a5bb728.png)

**Comment by shivam-kurtarkar** [comment]
please put js console bug this was cause of js
