### ISSUE TITLE
If the payment mode is split payment and the amount for split payment is not specified , and the initiate transaction button is clicked the Payment mode selected for split payment , get status,cancel payment buttons are not visible .

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1067]
Actual result
If the payment mode is split payment and the amount for split payment is not specified , and the initiate transaction button is clicked the Payment mode selected for split payment , get status,cancel payment buttons are not visible .

Expected result
the Payment mode selected for split payment , get status,cancel payment buttons  should be visible .

![image](https://user-images.githubusercontent.com/54023516/72315164-cc234500-36b7-11ea-8499-4a81731994c6.png)

**Comment by shivam-kurtarkar** [comment]
steps to replicate??
this might be the count getting wrong master issue

**Comment by shivam-kurtarkar** [comment]
on refresh should show up split
