### ISSUE TITLE
"HealthKart Premium Membership, 12 months" can be added to the cart after the payment is initiated

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1073]
Actual result
"HealthKart Premium Membership, 12 months" can be added to the cart after the payment is initiated

Expected result
Add to cart button and HealthKart Premium Membership, 12 months should not be visible when the payment is initiated.

![image](https://user-images.githubusercontent.com/54023516/72318533-89b33580-36c2-11ea-9be6-0a9f45c92b1d.png)

**Comment by sharangsamonkar** [comment]
This was probably fixed on a different branch. Check again and if issue is present then check master
