### ISSUE TITLE
offer section should be disabled when the payment is initiated.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1075]
Actual result
Offer section not disabled when the payment is initiated.

Expected result
offer section should be disabled when the payment is initiated.
![image](https://user-images.githubusercontent.com/54023516/72318782-3b526680-36c3-11ea-804b-c802d30fbb54.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/72411948-2264b680-3792-11ea-9216-08d41d0f0aef.png)
