### ISSUE TITLE
Scenario: No  internet when user clicks on receive payment button  - Customer details are not displaying when phone number is entered when user clicks back button on Browser so cannot place the order

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1083]
Go to POS
Scan the barcode and select payment as Credit Card
Initiate the payment and complete the payment
Disconnect the internet - 
Click on Recieve payment button - > No internet connection page will display
Connect to the internet
Click on back button on browser
Enter the phone number and observe

Actual result: Customer details are not displaying when phone number is entered when user clicks back button on Browser so cannot place the order

![image](https://user-images.githubusercontent.com/14803102/72336192-466abe00-36e6-11ea-9a45-b18634b555d1.png)

![image](https://user-images.githubusercontent.com/14803102/72334421-4a491100-36e3-11ea-88e5-63b1f08260e6.png)

**Comment by sharangsamonkar** [comment]
Order can be reset and we can proceed.

Check if theres a deadlock or wrong behaviour like placing the order without payment. If not please close the issue.
