### ISSUE TITLE
order is placed when the payment is cancelled and the user clicks back button  and clicks the receive payment button.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1084]
Actual result
order is placed when the payment is cancelled and the user clicks back button  and clicks the receive payment button.

Expected result
order should not be placed.

Steps
Scan the barcode
Enter the details
choose the payment mode as credit/debit card
click on initiate payment
Do the payment 
Click on get status
click on cancel transaction
Click on the back button
Click on receive payment

![image](https://user-images.githubusercontent.com/54023516/72336774-6b136580-36e7-11ea-9ea6-34fab58b74d3.png)
![image](https://user-images.githubusercontent.com/54023516/72336811-80888f80-36e7-11ea-9667-333aaf1b00d4.png)

**Comment by sharangsamonkar** [comment]
@shivam-kurtarkar  do a check on 0 open and success transactions

**Comment by shivam-kurtarkar** [comment]
tried got the message pls complete payment din place order

**Comment by shivam-kurtarkar** [comment]
*PLEASE ATTACH LOGS*

**Comment by shivam-kurtarkar** [comment]
done

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/72675919-50f3d180-3ab1-11ea-8a98-8838236fbc09.png)
