### ISSUE TITLE
Multiple textboxes are displayed when the Credit/debit card and the upi via EDC machine payment mode is selected for split payment.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1085]
Actual result
Multiple textboxes ate displayed when the Credit/debit card and the upi via EDC machine payment mode is selected for split payment.

Expected result
Single text box should be displayed for amount

![image](https://user-images.githubusercontent.com/54023516/72340400-27702a00-36ee-11ea-9242-25b891b9af18.png)

**Comment by sharangsamonkar** [comment]
Textboxes have been changed to text.

This is used for PTRIF and Success status.
