### ISSUE TITLE
responseCode":1052 is not handled hence error occured when Get Payment status error is displayed

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1086]
Go to POS
Scan barcode
Select payment mode as UPI via EDC machine
Click on Iniitate payment button

inelabs response {"responseCode":1052,"responseMessage":"CBI UPI/PhonePe TXN INITIATED. Perform GetStatus","plutusTransactionReferenceID":53628}

![image](https://user-images.githubusercontent.com/14803102/72341008-3e634c00-36ef-11ea-9527-ca2c07d31b45.png)

**Comment by sharangsamonkar** [comment]
Proper message is shown.
