### ISSUE TITLE
customer details are cleared when the get status button is clicked and are not auto populated on entering phone number.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1089]
Actual result
customer details are cleared when the get status button is clicked and are not auto populated on entering phone number.

Expected result
Customer details should be auto populated on entering the phone number.

![image](https://user-images.githubusercontent.com/54023516/72403868-934ba480-3779-11ea-9f74-5a96747867b5.png)

**Comment by rohan-morje** [comment]
Do not allow to enter customer details again on click of Receive Payment button, if user has not entered all the details

![image](https://user-images.githubusercontent.com/14803102/72584562-89a87500-3910-11ea-8fef-9e166bc2a40f.png)

**Comment by larissa-c-d** [comment]
Details are cleared on click of initiate payment for split payment 
![image](https://user-images.githubusercontent.com/54023516/72592002-9d130a80-3927-11ea-9148-025b0ec08d8d.png)
