### ISSUE TITLE
Average sales value for global, zone or custom level should be  calculated as (totalSales)/(total_number_of_stores * 3)

### ISSUE THREAD

**Issue by nutank** [ajency/HK-Issue-Tracker#109]
![screen shot 2018-10-30 at 5 21 57 pm](https://user-images.githubusercontent.com/7425622/47716308-5379c980-dc68-11e8-8bd3-464a689b6260.png)

**Comment by nutank** [comment]
@ambksud - please check this.

In Global tab avg = total_sales across all stores/(total no_of_stores * 3)
In Zone tab avg = total_sales for that zone/(total_no_of_stores **in that zone** * 3 )
In Custom tab avg = total_sales for that store/ 3 )

**Comment by ambksud** [comment]
Global level  average displayed is incorrect
Query :SELECT * FROM warehouse WHERE warehouse_type IN (3, 10) AND active = 1;

**Comment by ambksud** [comment]
Issue Fixed
