### ISSUE TITLE
"Transaction Cancelled." message is displayed when the Open transaction page is refreshed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1092]
Actual result
"Transaction Cancelled." message is displayed when the Open transaction page is refreshed.

Expected result
"Transaction Cancelled." message should not be  displayed when the Open transaction page is refreshed.

Go to open transactions UI page
Click on the refresh button.

![image](https://user-images.githubusercontent.com/54023516/72412865-72dd1380-3794-11ea-96a7-fd1e56133731.png)

**Comment by shivam-kurtarkar** [comment]
refresh performs last actin hence it runs last cancel transaction and shows the message @sharangsamonkar

**Comment by sharangsamonkar** [comment]
Browser functionality.
