### ISSUE TITLE
PTRID of both the both the transactions are not displayed when the credit/debit card and UPI via EDC machine both are selected for split payment.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1094]
Actual result
PTRID of both the both the transactions are not displayed when the credit/debit card and UPI via EDC machine both are selected for split payment.

Expected result
PTRID for both the transactions should be displayed.

steps
Go to the POS screen 
Scan the barcode 
Select the payment mode as split payment 
choose the payment mode as credit/debit card
choose the payment mode as UPI via EDC machine
Click on initiate payment for the credit/debit card mode
Complete the payment 
Click on get status button .
 Click on initiate payment for UPI via EDC machine
Complete the payment 
Click on get status button .

![image](https://user-images.githubusercontent.com/54023516/72430946-9a92a280-37b9-11ea-850b-4372837894a7.png)

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/72503666-498ab900-3862-11ea-981f-6bb7e3788168.png)

**Comment by rohan-morje** [comment]
PTRID of UPI via EDC machine not displayed when Split payment of Credit card and UPI is selected

![image](https://user-images.githubusercontent.com/14803102/72872293-fce82780-3d12-11ea-8e4f-46c5d2c7dcd6.png)

**Comment by rohan-morje** [comment]
PTRID is displaying
