### ISSUE TITLE
Transaction successful is displayed on the app when the Response is Timed Out on the pinelab device.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1095]
Actual result
Transaction successful is displayed on the app when the Response is Timed Out on the pinelab device.

Go to the POS screen 
Scan the barcode 
Select the payment mode as split payment 
choose the payment mode as credit/debit card
choose the payment mode as UPI via EDC machine
Click on initiate payment for the credit/debit card mode
Complete the payment 
Click on get status button .
Click on initiate payment for UPI via EDC machine
Complete the payment 
Click on get status button .

App screenshot
![image](https://user-images.githubusercontent.com/54023516/72432256-9caa3080-37bc-11ea-806a-65f63ba6b08a.png)

receipt
Response timeout

![image](https://user-images.githubusercontent.com/54023516/72432317-c2cfd080-37bc-11ea-8e3f-04c403020d9b.png)

**Comment by sharangsamonkar** [comment]
Not an issue. We need to go 'Get Status' on the pinelabs device.
