### ISSUE TITLE
SIS/ Retail Store - Do not allow to place order when any payment mode is selected. Please select a valid Payment Mode. message when split payment mode of Cash and Card is selected

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1096]
Go to SIs
Scan barocde
Select split payment of Cash andCard
Click on recieve payment

Actual result: Please select a valid Payment Mode. message displayed

Expected:Should allow to place the order

![image](https://user-images.githubusercontent.com/14803102/72492751-62847180-3844-11ea-88b1-567a73ec18a5.png)
![image](https://user-images.githubusercontent.com/14803102/72492766-6ca67000-3844-11ea-9851-7f82fb14d846.png)

**Comment by rohan-morje** [comment]
Not working for SIS store

**Comment by sharangsamonkar** [comment]
This was a missed live issue. This message should come only for Retail Stores (OFFLINE_B2C)

**Comment by rohan-morje** [comment]
Issue resolved for SIS
