### ISSUE TITLE
"Transaction pending" is displayed on the POS screen but "No open transactions" is displayed on the pine labs device.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1097]
Actual result
"Transaction pending" is displayed on the POS screen but "No open transactions" is displayed on the pine labs device.

Expected result
The transaction should be displayed on the pine labs device.

Steps
Go to the POS screen 
Scan a barcode
Enter the details
Select the split payment mode
Select counter cash and credit/debit card
enter the amount 
Click on initiate payment
Click on get payment mode

![image](https://user-images.githubusercontent.com/54023516/72492722-3ec12b80-3844-11ea-9bd0-6eff06cfedea.png)
![image](https://user-images.githubusercontent.com/54023516/72492967-3b7a6f80-3845-11ea-928a-831ab95111e5.png)

**Comment by sharangsamonkar** [comment]
Not replicable. Must be because of 
1. DB change between 62 and 138
2. Batch clearing on Pinelab machine

Shouldn't come again but please check.
