### ISSUE TITLE
Catalog - Null pointer exception when Store IMEI  or Merchant POS code removed and Saved

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1103]
Go to Catalog -> Retail SIS edit page
Eg: Mum Seawoods
Remove the Store IMEI  or Merchant POS code or Both and click on Save

Actual result: Null pointer exception observed

![image](https://user-images.githubusercontent.com/14803102/72501007-d0886300-385b-11ea-9ec3-d29b5826ff48.png)

**Comment by larissa-c-d** [comment]
Store IMEI and  Merchant POS code are compulsory fields if the enable config checkbox is checked
