### ISSUE TITLE
PTRID is not displayed when the cancel transaction button is clicked and there is an error cancelling the transaction

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1109]
Actual result
PTRID is not displayed when the cancel transaction button is clicked and there is an error cancelling the transaction

Expected result
PTRID should be displayed

![image](https://user-images.githubusercontent.com/54023516/72523788-8e284b80-3886-11ea-9e25-2bf571d9b8fc.png)

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/72594475-69d37a00-392d-11ea-906c-223313da06db.png)

**Comment by shivam-kurtarkar** [comment]
functionality

**Comment by larissa-c-d** [comment]
PTRID is not displayed when the cancel transaction button is clicked and there is an error cancelling the transaction
![image](https://user-images.githubusercontent.com/54023516/72609949-32c09100-394c-11ea-8557-acccc0a6cacb.png)
![image](https://user-images.githubusercontent.com/54023516/72610023-5daae500-394c-11ea-9186-c25ecde5e6f2.png)
