### ISSUE TITLE
Data not getting saved when record is selected to edit without clicking on checkbox

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#111]
https://bright61.healthkartqa.com/admin/inventory/MinimumInventoryConfig.action
Go to Custom tab
Search for the product variant to edit using filter
Do not click on the checkbox against the record to edit > Click on edit/view link > enter the min inventory data and click on Save

Actual result: Data not getting saved when record is selected to edit without clicking on checkbox

![image](https://user-images.githubusercontent.com/14803102/47769764-0ac31e80-dd03-11e8-9b15-2589e6ddf9f8.png)

**Comment by ambksud** [comment]
Fixed
