### ISSUE TITLE
Transaction Reverted when Mark as packed button clicked

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1110]
Go to HK.com
Checkout barocde
Do credit card payment
Click on mark as Packed and Observe

Actual result: Transaction Reverted when Mark as packed button clicked
HK.cm delhi pashchim vihar  HKI-22273-21789147

![image](https://user-images.githubusercontent.com/14803102/72524084-27eff880-3887-11ea-966b-1411c682949c.png)

**Comment by shivam-kurtarkar** [comment]
need more info to recreate but
