### ISSUE TITLE
PLEASE APPROVE OPEN TXN FIRST message is displayed on POS but can initiate transaction for HK.com

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1111]
Actual result
Failed to Initiate Transaction, please try again.
PLEASE APPROVE OPEN TXN FIRST [ExistingReferenceId:53791, Amount:52500] message is displayed on POS but can initiate transaction for HK.com

![image](https://user-images.githubusercontent.com/54023516/72524707-794cb780-3888-11ea-9883-35fdd6686b56.png)
![image](https://user-images.githubusercontent.com/54023516/72524800-b31dbe00-3888-11ea-93d7-2bcb5b1c2aba.png)

**Comment by shivam-kurtarkar** [comment]
cannot replicable
