### ISSUE TITLE
Do not allow to enter card amount again when transaction is initiated without entering the card amount

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1123]
Delhi Greenpark
Hk.com order

Go to HK.com order
Select payment mode Split of Cash and Card
Do not enter Cash amount and click on Initiate Payment button. -> Please specify proper amount for chosen split payment mode. message is displayed.

But do not allow to enter the Card amount . textbox is disabled

![image](https://user-images.githubusercontent.com/14803102/72588463-6a184900-391e-11ea-9961-dc695740387e.png)

**Comment by sharangsamonkar** [comment]
Validation in thrown on screen.

**Comment by rohan-morje** [comment]
issue resolved
