### ISSUE TITLE
payment pending is displayed on click of get status, when the payment is successful on the application.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1125]
Actual result
payment pending is displayed on click of get status, when the payment is successful on the application, while Pinelabs device displays the QR code.

steps
Scan a barcode 
Choose payment mode as UPI via EDC machine
Go to the pinelabs device open transactions 
Scan the barcode on the app
Displays payment successful on the app
Click on get payment status displays payment pending is displayed.
Pinelabs device displays the QR code

![image](https://user-images.githubusercontent.com/54023516/72588541-a9469a00-391e-11ea-94b0-52bb81ed2626.png)

**Comment by sharangsamonkar** [comment]
It has to complete on the Pinelab device first (slip printing part).

Not an issue.
