### ISSUE TITLE
Source to Destination Mapping doesnt exist message displayed when marking as packed

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1126]
Go to POS
Store BLR HSR 
Marked order as Packed

Source to Destination Mapping doesnt exist message displayed when marking as packed

![image](https://user-images.githubusercontent.com/14803102/72591891-5d4c2300-3927-11ea-8130-75ee11d395c4.png)

**Comment by sharangsamonkar** [comment]
HK setup issue

**Comment by sharangsamonkar** [comment]
Probably setup issue. Able to place orders for GGN Good Earth Mall.
