### ISSUE TITLE
"Third party Payment transaction are not complete" message is displayed when the receive payment button id clicked after removing one of the split payment modes.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1127]
Actual result
"Third party Payment transaction are not complete" message is displayed when the receive payment button id clicked after removing one of the split payment modes.

Steps
Scan a barcode on the POS screen
Select the payment mode as split payment mode
Select UPI and Counter cash payment mode.
Initiate the transaction
![image](https://user-images.githubusercontent.com/54023516/72591799-1d853b80-3927-11ea-9a9a-baa2d1270e72.png)
Click on get payment status
![image](https://user-images.githubusercontent.com/54023516/72592235-29253200-3928-11ea-849e-c8b0d7f79a35.png)
complete the payment
![image](https://user-images.githubusercontent.com/54023516/72592261-39d5a800-3928-11ea-9be0-392c3bf78b96.png)
remove the counter cash mode 
add the amount to UPI payment mode
![image](https://user-images.githubusercontent.com/54023516/72592356-65f12900-3928-11ea-93a2-964b4aeaa874.png)

Click on receive payment

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/72613582-ef6b2000-3955-11ea-9f7e-e6b80ff1e2f4.png)

**Comment by sharangsamonkar** [comment]
Done using inspect element.

**Comment by larissa-c-d** [comment]
"Split amount mismatch found" message should be changed to 'Please select the the payment mode for split payment'

**Comment by larissa-c-d** [comment]
Message changed to "Split payment mismatch found"
