### ISSUE TITLE
Error occurred while cancelling transaction. CANNOT CANCEL AS TRANSACTION IS IN PROGRESS message is displayed

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1129]
Steps select the payment mode as upi via edc machine 
Click scan the barcode do not click on pay 
click on cancel transaction
on click of get status payment pending status is displayed.

 :: user 15563757 customerOrder Transcation id 675
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:623) - Ajency.in :: resultset: 3
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:627) - Ajency.in :: forcePinelabsGetStatusApiStatus 3 active :false
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:455) - Ajency.in :: fetching pinelabs config for store 4034
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:654) - Ajency.in :: pinelabs params {"SecurityToken":"661c9a5f-5d7a-4d76-a950-68beb8225cfd","UserID":15563757,"PlutusTransactionReferenceID":53859,"MerchantStorePosCode":"04190588","IMEI":"IM239018","MerchantID":2300}
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:665) - Ajency.in :: resultset: https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:668) - Ajency.in :: pinelabsurl https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/ active :false
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:681) - Ajency.in :: making url call to  https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/GetCloudBasedTxnStatus
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:720) - Ajency.in :: pinelabs response {"responseCode":1001,"responseMessage":"TXN UPLOADED","plutusTransactionReferenceID":53859}
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:176) - Ajency.in :: customerOrderTransaction::
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:233) - Ajency.in :: transactionData empty

**Comment by shivam-kurtarkar** [comment]
@sharangsamonkar  response rerurned by pinelabs  need to check with pinelabs team


[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:176) - Ajency.in :: customerOrderTransaction:: 
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:233) - Ajency.in :: transactionData empty
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:245) - Ajency.in :: customer
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:298) - Ajency.in :: making cancel api call for transaction id:53859
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:740) - Ajency.in :: resultset: true
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:743) - Ajency.in :: forcePinelabsCancelApiCall true active :false
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:455) - Ajency.in :: fetching pinelabs config for store 4034
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:771) - Ajency.in :: pinelabs params {"SecurityToken":"661c9a5f-5d7a-4d76-a950-68beb8225cfd","Amount":150000,"PlutusTransactionReferenceID":53859,"MerchantStorePosCode":"04190588","IMEI":"IM239018","MerchantID":2300}
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:782) - Ajency.in :: resultset: https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:785) - Ajency.in :: pinelabsurl https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/ active :false
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:36) (ThirdPartyPaymentServiceImpl.java:798) - Ajency.in :: making url call to  https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/CancelTransaction
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:37) (ThirdPartyPaymentServiceImpl.java:809) - Ajency.in :: Pinelabs api call :1 : CANNOT CANCEL AS TRANSACTION IS IN PROGRESS
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:37) (ThirdPartyPaymentServiceImpl.java:822) - Ajency.in :: pinelabs response {"responseCode":1,"responseMessage":"CANNOT CANCEL AS TRANSACTION IS IN PROGRESS"}
[ERROR] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:37) (POSAction.java:3091) - Ajency.in :: Error occured when cancelling order status:1



[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:37) (ThirdPartyPaymentServiceImpl.java:400) - Ajency.in :: DEV :: customer order transaction id: 674 status: 5
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:37) (ThirdPartyPaymentServiceImpl.java:400) - Ajency.in :: DEV :: customer order transaction id: 675 status: 1
[ INFO] [] [http-nio-8181-exec-8] (17 Jan 2020 13:27:37) (ThirdPartyPaymentServiceImpl.java:403) - Ajency.in :: has pending transactions true
[ INFO] [] [pool-24-thread-1] (17 Jan 2020 13:29:58) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (17 Jan 2020 13:29:58) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : fal

**Comment by sharangsamonkar** [comment]
Functionality: Cannot cancel a transaction when the transaction is in progress.
