### ISSUE TITLE
Failed to Initiate Transaction, please try again. Please close open transaction (PTRID: 53882, Amount: 10000) before initiating a new transaction from Open Transaction   is displayed for void trnsactions

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1132]
Actual result
Failed to Initiate Transaction, please try again. Please close open transaction (PTRID: 53882, Amount: 10000) before initiating a new transaction from Open Transaction   is displayed for void transactions.

Expected result
void trnsaction are not displayed on the UI so the message should be changed to Failed to Initiate Transaction, please try again. Please close void transactions on the pine labs device

**Comment by shivam-kurtarkar** [comment]
this is pinelabs flow

**Comment by larissa-c-d** [comment]
message change: Failed to Initiate Transaction, please try again. 
Please close open transaction (PTRID: 53882, Amount: 10000)  from Open Transaction / check the pine labs device for void transactions before initiating a new transaction.

**Comment by larissa-c-d** [comment]
message changed
