### ISSUE TITLE
Please complete Open Payment transactions. message displayed when only Credi card payment select

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1133]
Go to POS
scan barocde
select credit card payment
COmplete payment process
Click on Receive payment button

Actual result Please complete Open Payment transactions. message displayed when only Credi card payment select

Expected: should allow to place order when only one payment mode selected

![image](https://user-images.githubusercontent.com/14803102/72611100-3570b580-394f-11ea-9f5a-40f3cac1c1d9.png)

**Comment by sharangsamonkar** [comment]
Also when the validation is thrown, the PTRID is lost.
