### ISSUE TITLE
Do not allow to scan barcode in HK.com checkout page

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1140]
Go to Mahavir Nagar store
Go to HK.com order
HKA-09079-21793277
Try to scan barocde

Do not allow to scan barcode in HK.com checkout page

**Comment by shivam-kurtarkar** [comment]
there is a open transaction hence you cannot edit

**Comment by sharangsamonkar** [comment]
Lets add a message when there is an open transaction
