### ISSUE TITLE
Loggers displayed on click of get payment status for HK.com order.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1144]
`[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:193) - Ajency.in :: creating new customerOrderTransactionDetails
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:231) - Ajency.in :: Saved customerOrderTransactionDetails
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:245) - Ajency.in :: customer
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 612 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 613 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 614 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 615 status: 4
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 618 status: 4
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 621 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 622 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 623 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 652 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 653 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 654 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 655 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 656 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 658 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 781 status: 4
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 782 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 835 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 836 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 837 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 838 status: 3
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:411) - Ajency.in :: has pending transactions true
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (POSAction.java:3016) - Ajency.in :: hasPendingOrCompleteTransactions :true
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (POSAction.java:3018) - Ajency.in :: customer name:Guest phone:XXXXXXXX72 email:suraj.rathore@brightlifecare.com pincode: null gender:null
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 612 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 613 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 614 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 615 status: 4
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 618 status: 4
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 621 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 622 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 623 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 652 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 653 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 654 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 655 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 656 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 658 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 781 status: 4
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 782 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 835 status: 5
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 836 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 837 status: 2
[ INFO] [] [http-nio-8181-exec-22] (20 Jan 2020 11:50:24) (ThirdPartyPaymentServiceImpl.java:408) - Ajency.in :: DEV :: customer order transaction id: 838 status: 3
`

**Comment by sharangsamonkar** [comment]
will be removed during clean up.
