### ISSUE TITLE
Open Transaction header not displaying

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1154]
Go to http://aqua61.healthkartqa.com/admin/payment/OpenTransactionUi.action and observe

ACTUAL:  Open Transaction header not displaying

![image](https://user-images.githubusercontent.com/14803102/72727864-03ab5900-3bb2-11ea-8663-fbc2cef8c3ef.png)

**Comment by larissa-c-d** [comment]
change Open Transaction ui: to  Open Transaction UI and the font size should be increased.
