### ISSUE TITLE
Mark as packed button is enabled when the payment is cancelled

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1160]
Actual result
Mark as packed button is enabled when the payment is cancelled

Expected result
Mark as packed button should be disabled when the payment is cancelled.

![image](https://user-images.githubusercontent.com/54023516/72782769-90a1f100-3c4a-11ea-8ed9-2c47f6dd91b5.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/72893705-b957e280-3d3f-11ea-948c-2015985c3017.png)
