### ISSUE TITLE
Error occurred while cancelling transaction. message displayed while cancelling Open HK.com transcation but transaction is cancelled

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1161]
Go to Open UI
Cancel the transaction and Observe

Actual result: Error occurred while cancelling transaction. message displayed while cancelling Open HK.com transcation but transaction is cancelled

![image](https://user-images.githubusercontent.com/14803102/72784280-7bc75c80-3c4e-11ea-912c-18caf05ebd81.png)

![image](https://user-images.githubusercontent.com/14803102/72784445-d6f94f00-3c4e-11ea-91a7-ef8e375aee3e.png)

**Comment by shivam-kurtarkar** [comment]
please attach logs .
Occurs when pinelabs api is down. and giving html response. 
and input occurs while parsing the response

**Comment by rohan-morje** [comment]
Pending

**Comment by rohan-morje** [comment]
Could not check as Order not displaying in Open Transaction UI

**Comment by shivam-kurtarkar** [comment]
same as   #1173

**Comment by rohan-morje** [comment]
Issue resolved
