### ISSUE TITLE
Transaction Time in customer order transaction details table is incorrect

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1165]
Go to POS
Initiate credit card payment

Transaction was done at 172810 but Transaction Time shown as 173205 in customer_order_transaction details table

![image](https://user-images.githubusercontent.com/14803102/72803321-cb6c4f00-3c73-11ea-9507-e0c6ab77cf27.png)

**Comment by sharangsamonkar** [comment]
@shivam-kurtarkar 
In sql:
1. Change transaction_date to DATE field
2. Change transaction_time to TIME FIELD

In java:
Convert the string to the date/time using SimpleDateFormat.

**Comment by rohan-morje** [comment]
Customer_order_transaction_details table not updated
