### ISSUE TITLE
Mark as packed button is enabled when the initiate transaction button is clicked without scanning the barcode.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1166]
Actual result
Mark as packed button is enabled when the initiate transaction button is clicked without scanning the barcode.

![image](https://user-images.githubusercontent.com/54023516/72805120-299b3100-3c78-11ea-88ca-859059cbef53.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/72892922-c70c6880-3d3d-11ea-87e6-b10f867890ca.png)
