### ISSUE TITLE
HK com OPen transaction not displaying in Open Transaction UI

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1173]

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/72894545-90385180-3d41-11ea-970d-ff0f4658f161.png)


![image](https://user-images.githubusercontent.com/14803102/72894458-5ebf8600-3d41-11ea-9626-eafc99d4de99.png)

**Comment by shivam-kurtarkar** [comment]
store was different in the table .

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/72957066-2c0ca080-3dc8-11ea-9ec8-39ca87096571.png)


![image](https://user-images.githubusercontent.com/14803102/72957080-3b8be980-3dc8-11ea-9066-655878146079.png)

**Comment by shivam-kurtarkar** [comment]
customer order is marked against 4049 in hkcat
but mapped against 4267 in aqua hence transaction are shown against different store.

**aqua**
![image](https://user-images.githubusercontent.com/52652317/72961514-4a2dcd00-3dd7-11ea-97c8-fa0b1700fcdf.png)


**hkcat** 
![image](https://user-images.githubusercontent.com/52652317/72961386-e0152800-3dd6-11ea-905f-8463c2502201.png)
