### ISSUE TITLE
Initiate Payment button is not displayed when payment mode selected is UPI VIa EDC machine

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1174]
Go to POS
Select payment mode as Counter Cash
Den selecte mode as UPI via EDC machine
Den click on back browseer button
Then click on Forward browser button

![image](https://user-images.githubusercontent.com/14803102/72895302-09847400-3d43-11ea-835c-b156af6b21bc.png)

**Comment by sharangsamonkar** [comment]
This is caused by going back and coming in front again.

1. If you proceed with Receive Payment you will get server side validation.
2. Also if you change and select the payment mode again you will see the inititate button.

**Comment by rohan-morje** [comment]
As per dev comment closing the issue
