### ISSUE TITLE
Transaction are initiated and cancelled when clicked on back and Forward button on the browser

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1175]
Go to POS
INiitate the payment 
Cancel the payment  -> Click on back arrow button -> Payment is Initiated
Now click Forward arrow button -> payment is cancelled

**Comment by sharangsamonkar** [comment]
Browser behaviour.

There are server side validations. Please check if doing this lets you place the order or breaks some flow

**Comment by rohan-morje** [comment]
As per dev comment , closing the issue
