### ISSUE TITLE
Entries in the Liquidation Discount table should be store specific.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1182]
Actual result
Entries in the Liquidation Discount table should be store specific.

![image](https://user-images.githubusercontent.com/54023516/73056634-92bbb800-3eb5-11ea-8a29-911f1cffe708.png)

**Comment by Shraddhar23** [comment]
No.Barcodes of the warehouse other than logged in warehouse will be allowed to upload.
