### ISSUE TITLE
If the barcode is not valid(Special Characters Found in the Barcode) the entry is made in the database.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1183]
Actual result
If the barcode is not valid(Special Characters Found in the Barcode) the entry is made in the database.

upload the excel with a special character in the barcode.

![image](https://user-images.githubusercontent.com/54023516/73058022-bf250380-3eb8-11ea-86e9-a2e03ec2f81f.png)

**Comment by Shraddhar23** [comment]
An entry will be made into master_discount_failed_barcodes table for special characters present in the excel.
