### ISSUE TITLE
No check is made for the values in the barcode column  to be unique in the excel sheet

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1184]
Actual result
No check is made for the values in the barcode column  to be unique in the excel sheet

Expected result
barcodes in the column should be unique

![image](https://user-images.githubusercontent.com/54023516/73061543-707b6780-3ec0-11ea-9067-5127e0e3c603.png)
![image](https://user-images.githubusercontent.com/54023516/73061569-7e30ed00-3ec0-11ea-91e4-91ebe3332e8d.png)

**Comment by Shraddhar23** [comment]
Since we will allow multiple uploads for the same barcode , the latest discount_percentage will be updated in the master_discount_details.

**Comment by larissa-c-d** [comment]
second duplicate entry for the barcode will fail
