### ISSUE TITLE
Null pointer exception when clicked on Print button

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1188]
Place the order by scanning the barcode
Click on Print button

Actual result: Null pointer exception when clicked on Print button

![image](https://user-images.githubusercontent.com/14803102/73149751-c03c7780-40e8-11ea-9d1d-760a7f3505f3.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/73149809-05f94000-40e9-11ea-93c4-5b9355f800cf.png)

**Comment by rohan-morje** [comment]
Null pointer exception when clicked on Print
![image](https://user-images.githubusercontent.com/14803102/73253607-d3337280-41e2-11ea-8a28-b06947daa591.png)

**Comment by larissa-c-d** [comment]
issue resolved
