### ISSUE TITLE
Liquidation Discount Applied label not removed when Item level discount on MRP is applied

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1191]
Scan barocde with Liquidation discount 
Apply  Item level discoiunt on MRP and Observe

Offer: 1501 flat item lvl on MRP

Actual: Liquidation Discount Applied label not removed when Item level discount on MRP is applied

Expected; Liquidation Discount Applied label should be removed when Item level discount on MRP is applied

![image](https://user-images.githubusercontent.com/14803102/73152769-1e705700-40f7-11ea-947d-cb080bf54813.png)

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/73259612-2d860080-41ee-11ea-8adf-69b55e6f5764.png)
issue resolved
