### ISSUE TITLE
Liquidation Discount applied label is displayed when offer is removed

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1200]
Go to POS
Scan the barcode for which Liquidation discount not enbaled 
IVN-1148743-913
Apply the offer
Remove the offer and Observe

Actual result: Liquidation Discount applied label is displayed when offer is removed

![image](https://user-images.githubusercontent.com/14803102/73166761-7f5e5600-411c-11ea-9a65-8d6ba28065da.png)

**Comment by larissa-c-d** [comment]
Issue resolved
