### ISSUE TITLE
Liquidation discount is applied when the liquidation discount is less than the discount_percent 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1202]
Actual result
Liquidation discount is applied when the liquidation discount is less than the discount_percent 

Scan a barcode for  NPL product

![image](https://user-images.githubusercontent.com/54023516/73175500-5778ed80-4130-11ea-8ce0-d9596e5f5014.png)
![image](https://user-images.githubusercontent.com/54023516/73175514-61025580-4130-11ea-84ea-2576c7847504.png)
![image](https://user-images.githubusercontent.com/54023516/73175530-6bbcea80-4130-11ea-8d59-d40787eb9227.png)
![image](https://user-images.githubusercontent.com/54023516/73175566-81caab00-4130-11ea-926a-e8571c2a6343.png)
![image](https://user-images.githubusercontent.com/54023516/73175584-8db66d00-4130-11ea-949a-dc202f8f5695.png)

**Comment by Shraddhar23** [comment]
For a NPL barcode , FEFO gets applied even if sku and product variant discount is higher than FEFO.
Hence , in this case Liquidation will get applied if its higher than FEFO.

**Comment by larissa-c-d** [comment]
same flow is observed on master

**Comment by larissa-c-d** [comment]
issue resolved,liquidation discount does not get applied in the above case
