### ISSUE TITLE
Offers are not displaying when you scan barcode of different variants

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1204]
Check the screenshot below
Scan 1 barcode of 1 variant NUT1367-51)
Scan 3 barcode of another variant  (Liquidation discount enabled for all 3 barcodes) NUT1367-30

Actual result: Offers are not displaying when you scan barcode of different variants

![image](https://user-images.githubusercontent.com/14803102/73235741-b3d22080-41b5-11ea-88d1-ea792f190e71.png)111

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/73258882-a2583b00-41ec-11ea-883b-345154067cf1.png)
issue resolved
