### ISSUE TITLE
When the item level offer cannot be applied the liquidation discount label disappears

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1210]
Actual result
When the item level offer cannot be applied the liquidation discount label disappears.

Scan the barcode for truebasics brand store id:4033
Liquidation discount:61%
Offer discount:21%
Click on Buy 1-4TRU Get21.0% ITEMLEVELDIS ITEM VALUE ON MRP

![image](https://user-images.githubusercontent.com/54023516/73239066-0d8c1800-41c1-11ea-9082-48e9f3da7e6a.png)
![image](https://user-images.githubusercontent.com/54023516/73239080-17ae1680-41c1-11ea-8627-4c0f4b9232d5.png)

**Comment by Shraddhar23** [comment]
same as 
https://github.com/ajency/HK-Issue-Tracker/issues/1205

**Comment by larissa-c-d** [comment]
Issue resolved
