### ISSUE TITLE
Liquidation discount label disappears when applied offer is applicable on offer price

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1211]
Go to POS
Scan the barcode with Liquidation discount applicable
IV-2325827-16  Liquidation discount will be applied  NPL
Now apply Item level discount on Offer price and Obaerve

Liquidation discount label disappears when applied offer is applicable on offer price

![image](https://user-images.githubusercontent.com/14803102/73240889-614d3000-41c6-11ea-9775-a4de88a352b0.png)

**Comment by larissa-c-d** [comment]
Issue resolved
