### ISSUE TITLE
item level offer is applied on the offer price when item level offer is less than the liquidation discount.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1212]
Actual result
item level offer is applied on the offer price when item level offer is less than the liquidation discount.

Scan the barcode IVN-1306923-418
               liquidation discount:0.65
               Apply the offer:Buy 1-4 TRU 14.0% ITEM LEVEL PERITEM VALUE

![image](https://user-images.githubusercontent.com/54023516/73242897-31089000-41cc-11ea-885d-55772f4c216b.png)
![image](https://user-images.githubusercontent.com/54023516/73242937-4ed5f500-41cc-11ea-8c6d-09095d929e00.png)

**Comment by Shraddhar23** [comment]
Not an issue as the offer is applied on the offer price after liquidation discount is applied.
