### ISSUE TITLE
Order could not be placed! Amount mismatch issue has occured. Please try again!! message displayed when pack converted barcode are scanned

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1215]
Scan pack converted  1 barcode one has Liquidation Discount and Other   barcode has Fefo discount
CLick on Receive Payment button

Expected result : Order cannot be created as different variants of the same product should have same discount message should be displayed.

Actual result: Order could not be placed! Amount mismatch issue has occured. Please try again!! message displayed when pack converted barcode are scanned

![image](https://user-images.githubusercontent.com/14803102/73260382-cc5f2c80-41ef-11ea-8883-aa53b4104138.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/73261624-7c359980-41f2-11ea-8148-563c9289bc37.png)

**Comment by larissa-c-d** [comment]
issue exists for phone number:9999999999

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/73334698-66c47c00-4293-11ea-9d38-5eeb9ea94ce8.png)
issue resolved
