### ISSUE TITLE
AMount displayed on Print page is not matching the actual amount on POS

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1218]
Scan 2 converted NUT B barcode
One has Liquidation discount and one without any discount
PLace the order and observe the final amount

Actual: AMount displayed on Print page is not matching the actual amount on POS
Amount on POS: 7019
Amount on print: 3239

![image](https://user-images.githubusercontent.com/14803102/73266694-6a0d2880-41fd-11ea-8902-3a843f0f1e21.png)

![image](https://user-images.githubusercontent.com/14803102/73266667-582b8580-41fd-11ea-956e-55c41c175e84.png)

**Comment by larissa-c-d** [comment]
issue occurred in case of  #1219, not an issue mow as order won't be placed
