### ISSUE TITLE
Customer details are not auto populate on entering the phone number.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1229]
Actual result
Customer details are not auto populate on entering the phone number.

expected result
Customer details should be auto populate on entering the phone number.

Steps
Enter the phone number on POS store id:4033.

![image](https://user-images.githubusercontent.com/54023516/73628444-52f38e00-4676-11ea-85f9-2b41a1a6a8bc.png)

**Comment by shivam-kurtarkar** [comment]
json circular ref error
