### ISSUE TITLE
Error message displayed when Order level discount applied on NPL product is not proper

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#123]
Go to POS
Scan he NPL product
Select the order level offer  "Test Offer Discount on Retail SIS" and Observe

Actual Result: Error message displayed ie "Item level offer cannot be applied to some of the item(s) in your cart!" when **Order level discount applied** on NPL product is not proper.

![image](https://user-images.githubusercontent.com/14803102/47990531-bc03f300-e10d-11e8-9d6e-7164f0e53fac.png)

**Comment by nutank** [comment]
Existing issue. Same message is shown always.
