### ISSUE TITLE
transaction status is displayed when the PAYU_ENDPOINT is changed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1236]
Actual result
transaction status is displayed when the PAYU_ENDPOINT is changed.

Expected result
No status should be fetched, the message "Failed to get the status of the transaction" should be displayed.

Steps
Change the end point for PAYU_ENDPOINT in global defaults table.
Scan the barcode 
Enter the details
click on initiate transaction
Click on get status.
 
![image](https://user-images.githubusercontent.com/54023516/73643015-be4e5780-4698-11ea-8502-ebb206f8d56a.png)

**Comment by shivam-kurtarkar** [comment]
please change the endpoint to wrong endpoint empty will make it use default

**Comment by larissa-c-d** [comment]
message changed to "Payment Pending.
Error occurred while getting latest status."
