### ISSUE TITLE
transaction status is displayed as failed in the database, but the message transaction is initiated is displayed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1239]
Actual result
transaction status is displayed as failed in the database, but the message transaction is initiated is displayed.

Expected result
message "Failed to  initiate transaction" should be displayed.
`
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 16:02:32) (ThirdPartyPaymentServiceImpl.java:460) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 16:02:32) (ThirdPartyPaymentServiceImpl.java:462) - Ajency.in :: has pending transactions false for null
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:2787) - Ajency.in :: payment mode : 700: PayU Static QR
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:2798) - Ajency.in :: payment mode upi || card || split
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:2810) - Ajency.in :: creating customer order
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:5954) - user id:5590881
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:5955) - user gender:FEMALE
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:5964) - Ajency.in :: Invoice email :5590881suraj.rathore@brightlifecare.com
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:2732) - Ajency.in :: pos cart dto , coupon code: null
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:3917) - Ajency.in :: IsHKMembership: false skuItem Id: 7758651 skuItem: null
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:3924) - Ajency.in :: updated skuItem: com.hk.domain.sku.SkuItem@6e892012 vendor : 2
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:3942) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:3943) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSServiceImpl.java:753) - Ajency.in :: updating customer order :null
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSServiceImpl.java:764) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:2820) - Ajency.in :: customer order created id 1236322
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:2844) - Ajency.in :: final payable  rounded amount :1499.0
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (ThirdPartyPaymentServiceImpl.java:57) - Ajency.in :: customer order id :1236322 transaction id 1236322-1580725961656
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:77) - Ajency.in :: transaction number :1236322-1580725961656 amount:149900
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:341) - Ajency.in :: fetching payu config for store 4033
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:345) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@10ba10eb
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:349) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@10ba10eb qrid:STQI-payu12-136227
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:102) - Ajency.in :: making url call to   https://mobiletest.payu.in/QrPayment
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuApiRequest.java:78) - data : vDy3i7|1236322-1580725961656|149900|Integrated Static QR|||3600|STQI-payu12-136227|||||||||ozyEFwfA
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuApiRequest.java:79) - hash : 132ce35d0f1d9ffb949874b679a45717c6250480fd654ca95d98f55c9d2bf347bc744fdbfa6d135444d2932c87c63bb7853565a80a3467bf3c0876af486d2f22
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:375) - post data to payu gateway: key=vDy3i7&hash=132ce35d0f1d9ffb949874b679a45717c6250480fd654ca95d98f55c9d2bf347bc744fdbfa6d135444d2932c87c63bb7853565a80a3467bf3c0876af486d2f22&txnid=1236322-1580725961656&amount=149900&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-payu12-136227
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:393) - Ajency.in :: retval {"status":"failed","message":"There is transaction which is in progress against given qr id.","errorCode":"E2043"}
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:425) - {"status":"failed","message":"There is transaction which is in progress against given qr id.","errorCode":"E2043","map":{}}
[ERROR] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:107) - Ajency.in :: payu api call :failed : There is transaction which is in progress against given qr id.
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:125) - Ajency.in :: payu response {"status":"failed","message":"There is transaction which is in progress against given qr id.","errorCode":"E2043","map":{}}
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:132) - Ajency.in :: payu api call for transaction 1236322-1580725961656
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (PayuServiceImpl.java:133) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (ThirdPartyPaymentServiceImpl.java:92) - Ajency.in :: saved customerOrderTransaction 1225 transactionId :1236322-1580725961656
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (POSAction.java:2853) - Ajency.in :: pos action transaction status :FAILED
[ INFO] [] [http-nio-8181-exec-8] (03 Feb 2020 16:02:41) (ThirdPartyPaymentServiceImpl.java:462) - Ajency.in :: has pending transactions false for 1236322
[ INFO] [] [pool-24-thread-1] (03 Feb 2020 16:06:58) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (03 Feb 2020 16:06:58) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
`
![image](https://user-images.githubusercontent.com/54023516/73646652-e2616700-469f-11ea-8214-c515bf1bd808.png)

**Comment by shivam-kurtarkar** [comment]
open transaction message is displayed

**Comment by larissa-c-d** [comment]
> open transaction message is displayed

has pending transactions false is displayed
