### ISSUE TITLE
Amount displayed on Invoices and BO after applying the Order level discount is incorrect for PL and NPM porduct

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#124]
Go to POS screen
Scan NPL product and Scan PL product
Apply 27% discount on Order level offer 
and click on Receive payment button  and Observe the Invoices and BO for that order

Actual Result: Order level discount is split between PL and NPL product
Offer price of MuscleBlaze Whey Protein, 4.4 lb Rich Milk Chocolate (NUT1367-39) is 3849.14 . And after applying order level 27%discount it should be 3849.14-1039 ie 2810.
But in invoice and BO it is displaying as 3464.

--
ON (Optimum Nutrition) Gold Standard 100% Whey Protein, 5 lb Double Rich Chocolate (NUT304-27) offer price is 6544.15 but in invoice amount displayed is Rs. 5,889.85

![image](https://user-images.githubusercontent.com/14803102/47992580-4569f400-e113-11e8-87e7-9f882203d9e5.png)

![image](https://user-images.githubusercontent.com/14803102/47992625-5f0b3b80-e113-11e8-9f9b-d46b2f17cd7c.png)
![image](https://user-images.githubusercontent.com/14803102/47992652-6f231b00-e113-11e8-9613-902f874577e9.png)

**Comment by ambksud** [comment]
Issue Resolved
