### ISSUE TITLE
Order level discount offer not displaying when Total offer price is more than  Trigger price

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#125]
precondition: Trigger for Order levle Offer : Buy 1-11 items worth Rs. 900.0-20000.0 in cat : Nutrition#2|Sports Nutrition#979|Whey Proteins#1475

Go to POS screen 
sacn 2 barcode NPL product and 2 barcode of PL product> Total of all 4 barcode is 20786.58

Actual Result: Order level discount offer not displaying when Total offer price is more than  Trigger price

Total Offer price of MuscleBlaze Whey Protein, 4.4 lb Rich Milk Chocolate (NUT1367-39) 2 PL product is 7780 

![image](https://user-images.githubusercontent.com/14803102/47994882-a98fb680-e119-11e8-8d70-eae9baad3555.png)

**Comment by ambksud** [comment]
Issue Resolved
