### ISSUE TITLE
"Error occurred while cancelling transaction." message is displayed when clicked on cancel transaction.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1251]
Actual result
"Error occurred while cancelling transaction." message is displayed when clicked on cancel transaction.

Steps
go to the POS screen
Scan a barcode 
choose the payment mode PayU
Click on initaite transaction
Click on get payment status 
Click on cancel transaction

`[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (POSAction.java:3054) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (POSAction.java:3062) - Ajency.in :: Customer Order Transaction Id1250
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (ThirdPartyPaymentServiceImpl.java:257) - Ajency.in :: cancelling transaction, id:1250
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (ThirdPartyPaymentServiceImpl.java:123) - Ajency.in :: user 15563757 customerOrder Transcation id 1250
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (ThirdPartyPaymentServiceImpl.java:207) - Ajency.in :: customer
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (ThirdPartyPaymentServiceImpl.java:267) - Ajency.in :: making cancel api call for transaction id:null
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (PayuServiceImpl.java:211) - Ajency.in :: transaction number :1236329-1580732124646
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (PayuServiceImpl.java:345) - Ajency.in :: fetching payu config for store 4033
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (PayuServiceImpl.java:349) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@766786b7
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (PayuServiceImpl.java:353) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@766786b7 qrid:STQI-IM4033o1-136227
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (PayuServiceImpl.java:238) - Ajency.in :: making url call to  https://mobiletest.payu.in/merchant/postservice.php"
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (PayuApiRequest.java:56) - data : vDy3i7|cancel_qr_payment|{"transactionId":"1236329-1580732124646"}|ozyEFwfA
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (PayuApiRequest.java:57) - hash : e70daf32505616743dae14cddbb7caf4b1690a1f963cc58a4441989efac11063ed6794c1d43dc1848150691de7a8cd6f3d9f80530b96b5819c33850a40814732
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:54) (PayuServiceImpl.java:379) - post data to payu gateway: key=vDy3i7&command=cancel_qr_payment&hash=e70daf32505616743dae14cddbb7caf4b1690a1f963cc58a4441989efac11063ed6794c1d43dc1848150691de7a8cd6f3d9f80530b96b5819c33850a40814732&var1=%7B%22transactionId%22%3A%221236329-1580732124646%22%7D
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:55) (PayuServiceImpl.java:397) - Ajency.in :: retval <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />    <title>Page Not Found</title>    <link rel="shortcut icon" type="image/ico" href="https://mobiletest.payu.in/images/favicon.png" />    <link href="https://mobiletest.payu.in/css/main.css" rel="stylesheet" type="text/css" />    </head><body>	<div id="header">		<div class="logo"></div>		<div class="merchantName"></div>	</div>	<div id="container">		<div class="paymentDetailsDiv">			<div class="paymentDetailsHeading">Page Not Found</div>			<div class="paymentDetails"><div class="payby"></div>				<div class="card-bg-top"></div>				<div class="card-bg-mid">					<div id="visamaster-container"></div>					<div						style="font-size: 22px; font-weight: normal; margin-top: 15px; clear: both">					<h4 align="center">							<strong> <span style="color: #FF6600">Page Not Found! Please									check the url.<br />Error: 404							</span>							</strong>						</h4>		</div>				</div>				<div class="card-bg-bottom"></div>			</div>		</div>	</div></body></html>
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:55) (PayuServiceImpl.java:408) - Ajency.in :: json parsing error  
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:55) (PayuServiceImpl.java:421) - Ajency.in :: serialized parsing error  
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:55) (PayuServiceImpl.java:429) - 
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:55) (PayuServiceImpl.java:264) - Ajency.in :: payu api call for transaction 1236329-1580732124646
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:55) (PayuServiceImpl.java:265) - Ajency.in :: messages: Failed to cancel.
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:55) (POSAction.java:3070) - Ajency.in :: pos action transaction status :OPEN
[ERROR] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:55) (POSAction.java:3079) - Ajency.in :: Error occured when cancelling order status:1
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 17:52:55) (ThirdPartyPaymentServiceImpl.java:452) - Ajency.in :: has pending transactions true
`

**Comment by shivam-kurtarkar** [comment]
end point was wrong
