### ISSUE TITLE
"transaction cancelled" message is displayed on click on cancel button on the POS screen when the transaction is cancelled from the open transaction UI.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1257]
Actual result
transaction cancelled message is displayed on click on cancel button on the POS screen when the transaction is cancelled from the open transaction UI.

Expected result
Message " Transaction already cancelled" should be displayed.

Steps
Go to the POS screen 
Scan the barcode
Enter the details
Select the PayU payment mode
Click on initiate transaction
Go to the open transaction UI click on cancel transaction.
Go back to the POS screen click on cancel button .

![image](https://user-images.githubusercontent.com/54023516/73714216-3d459d80-4736-11ea-8ccf-57d67f336728.png)

![image](https://user-images.githubusercontent.com/54023516/73714169-14bda380-4736-11ea-93b4-610584cbf630.png)

**Comment by shivam-kurtarkar** [comment]
this will require additional handling to pass existing status from third party service to pos action
 @sharangsamonkar

**Comment by shivam-kurtarkar** [comment]
payu response to get status
```
[ INFO] [] [http-nio-8181-exec-33] (12 Feb 2020 11:37:21) (PayuServiceImpl.java:221) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-33] (12 Feb 2020 11:37:21) (ThirdPartyPaymentServiceImpl.java:147) - Ajency.in :: saving mihpay id :412345678912350828
[ INFO] [] [http-nio-8181-exec-33] (12 Feb 2020 11:37:21) (ThirdPartyPaymentServiceImpl.java:171) - Ajency.in :: saving get status details...{"mihpayid":"412345678912350828","mode":"ISBQR","status":"pending","txnid":"1386499-1581487563748","amount":"153900.00","key":"vDy3i7","addedon":"2020-02-12 11:36:05","productinfo":"Integrated Static QR","firstname":"","lastname":"","address1":"","address2":"","city":"","state":"","country":"","zipcode":"","email":"","phone":"","udf1":"3600","udf2":"STQI-4033-136227","udf3":"","udf4":"","udf5":"","udf6":"","udf7":"","udf8":"","udf9":"","udf10":"","field0":"","field1":"","field2":"","field3":"","field4":"","field5":"","field6":"","field7":"","field8":"","field9":"","unmappedstatus":"in progress","hash":"3a37c147a1d0cf72a8fda7689902b5430bc46eea9330396c8c44353f719aec8751281b07e5aa3f2fe5d2de22cf9e460167129757c4aa3fe9e1d96757c192ffba","bankcode":"ISBQR","map":{}}
```

payu response to cancel
```
{"status":"failed","message":"There is no [in progress] transaction with given transactionId","errorCode":"E2019","map":{}}
```

unmapped status is in progress
cancel says not in progress

**Comment by larissa-c-d** [comment]
message should be "Payment Cancelled, Please try Re-Initiating the Transaction."
