### ISSUE TITLE
PTRID is not displayed on the open transaction UI for payment mode PayU

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1258]
Actual result
PTRID is not displayed on the open transaction UI for payment mode PayU

Expected result
PTRID should be displayed on the open transaction UI for payment mode PayU

Steps
Go to the POS screen 
Scan the barcode
Enter the details
Select the PayU payment mode
Click on initiate transaction
Go to the open transactions ui page

![image](https://user-images.githubusercontent.com/54023516/73714588-47b46700-4737-11ea-953d-a8fd2aa9c11c.png)

**Comment by shivam-kurtarkar** [comment]
after initiating it wont show until get status is done

**Comment by larissa-c-d** [comment]
PTRID is displayed on click of get status
