### ISSUE TITLE
Item level discount on  MRP(higher than fefo) is not getting applied 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#126]
Scan the barcode
Apply item level discount on MRP and observe

Actual result: Item level discount on  MRP is not getting applied 

Item level discount on  MRP is higher than FEFO discount 

![image](https://user-images.githubusercontent.com/14803102/48126492-46cc2580-e2a7-11e8-86ca-3a7b28548e9f.png)

**Comment by ambksud** [comment]
Issue Resolved
