### ISSUE TITLE
no error message is displayed when the endpoint for initiate transaction is changed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1261]
Actual result
no error message is displayed when the endpoint for initiate transaction is changed.

Expected result
Message "Failed to initiate transaction" should be displayed.

Steps
Change the end point for initiate transaction in the global defaults table.
Go to the POS screen 
Scan the barcode
Enter the details
Select the PayU payment mode
Click on initiate transaction 

![image](https://user-images.githubusercontent.com/54023516/73716096-11c5b180-473c-11ea-81e8-8ea5aead2aa0.png)
`

[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (POSAction.java:2787) - Ajency.in :: payment mode : 700: PayU Static QR
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (POSAction.java:2798) - Ajency.in :: payment mode upi || card || split
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (POSAction.java:2806) - Ajency.in :: trying to fetch customer order by id :1236334
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (POSAction.java:2830) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (ThirdPartyPaymentServiceImpl.java:462) - Ajency.in :: has pending transactions false for 1236334
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (POSServiceImpl.java:753) - Ajency.in :: updating customer order :1236334
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (POSServiceImpl.java:764) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (POSAction.java:2844) - Ajency.in :: final payable  rounded amount :4959.0
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (ThirdPartyPaymentServiceImpl.java:57) - Ajency.in :: customer order id :1236334 transaction id 1236334-1580793531773
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:77) - Ajency.in :: transaction number :1236334-1580793531773 amount:495900
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:345) - Ajency.in :: fetching payu config for store 4033
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:349) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@729e1641
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:353) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@729e1641 qrid:STQI-IM4033o1-136227
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:102) - Ajency.in :: making url call to   https://mobiletest.payu.in/QrPay
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuApiRequest.java:78) - data : vDy3i7|1236334-1580793531773|495900|Integrated Static QR|||3600|STQI-IM4033o1-136227|||||||||ozyEFwfA
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuApiRequest.java:79) - hash : 53771f28d8de187c772b6c912a2e67de35fab50ed1e78373fc6e4915005e12a9ac7342f814ec27f0d51a0146c5ca68da33ee88481734f3a79c64354dc41b7dc7
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:379) - post data to payu gateway: key=vDy3i7&hash=53771f28d8de187c772b6c912a2e67de35fab50ed1e78373fc6e4915005e12a9ac7342f814ec27f0d51a0146c5ca68da33ee88481734f3a79c64354dc41b7dc7&txnid=1236334-1580793531773&amount=495900&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-IM4033o1-136227
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:397) - Ajency.in :: retval <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />    <title>Page Not Found</title>    <link rel="shortcut icon" type="image/ico" href="https://mobiletest.payu.in/images/favicon.png" />    <link href="https://mobiletest.payu.in/css/main.css" rel="stylesheet" type="text/css" />    </head><body>	<div id="header">		<div class="logo"></div>		<div class="merchantName"></div>	</div>	<div id="container">		<div class="paymentDetailsDiv">			<div class="paymentDetailsHeading">Page Not Found</div>			<div class="paymentDetails"><div class="payby"></div>				<div class="card-bg-top"></div>				<div class="card-bg-mid">					<div id="visamaster-container"></div>					<div						style="font-size: 22px; font-weight: normal; margin-top: 15px; clear: both">					<h4 align="center">							<strong> <span style="color: #FF6600">Page Not Found! Please									check the url.<br />Error: 404							</span>							</strong>						</h4>		</div>				</div>				<div class="card-bg-bottom"></div>			</div>		</div>	</div></body></html>
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:408) - Ajency.in :: json parsing error  
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:421) - Ajency.in :: serialized parsing error  
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:429) - 
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:129) - Ajency.in :: payu response 
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:136) - Ajency.in :: payu api call for transaction 1236334-1580793531773
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (PayuServiceImpl.java:137) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (ThirdPartyPaymentServiceImpl.java:92) - Ajency.in :: saved customerOrderTransaction 1274 transactionId :1236334-1580793531773
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (POSAction.java:2853) - Ajency.in :: pos action transaction status :CANCELLED
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:51) (POSAction.java:2862) - Ajency.in :: unhandled case customerOrderTransactionStatus:2
[ INFO] [] [http-nio-8181-exec-5] (04 Feb 2020 10:48:52) (ThirdPartyPaymentServiceImpl.java:462) - Ajency.in :: has pending transactions false for 1236334
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:19) (HKAPIRetailStoreServiceImpl.java:333) - Ajency.in:: Updating retail store:: MUM Bandra
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:19) (HKAPIRetailStoreServiceImpl.java:356) - Ajency.in :: SYNC retail store old SendSmsEmailInvoice true saved to store new SendSmsEmailInvoice:true
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:19) (HKAPIRetailStoreServiceImpl.java:363) - Ajency.in :: SYNC retail store pinelabs config truestore id :4033imeiaasasa merchant code asasas active:false
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:19) (Warehouse.java:337) - Setting gstin = 27AAECB5311J1ZU for warehouse MUM Bandra
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:19) (HKAPIRetailStoreServiceImpl.java:897) - Ajency.in:: Vendor for seek invoice number => BLC
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:19) (HKAPIRetailStoreServiceImpl.java:856) - Calling Bright to get seek invoice count
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:897) - Ajency.in:: Vendor for seek invoice number => AQUA
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:963) - Existing Vendor Mapping updated for store 4033 with vendor 2
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:963) - Existing Vendor Mapping updated for store 4033 with vendor 1
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:422) - Ajency.in:: Updating Retail Store Payment mode mapping for the store : 4033
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode COUNTER_CASH store ID : 4033
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode CARD_PAYMENT store ID : 4033
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode PAYTM_WALLET store ID : 4033
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode SPLIT store ID : 4033
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode SWIGGY store ID : 4033
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode PAYTM_VOUCHER store ID : 4033
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode UPI_VIA_EDC_MACHINE store ID : 4033
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode PAYU_STATIC_QR store ID : 4033
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:693) - Ajency.in :: WAREHOUSE VENDOR GSTIN :: Mapping Updated for Warehouse Id 4033 and Vendor Id 2 with GSTIN : 27AAECB5311J1ZU
[ INFO] [] [http-nio-8181-exec-10] (04 Feb 2020 10:49:20) (HKAPIRetailStoreServiceImpl.java:693) - Ajency.in :: WAREHOUSE VENDOR GSTIN :: Mapping Updated for Warehouse Id 4033 and Vendor Id 1 with GSTIN : 27AAJCA6439P1ZZ
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:333) - Ajency.in:: Updating retail store:: MUM Bandra
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:356) - Ajency.in :: SYNC retail store old SendSmsEmailInvoice true saved to store new SendSmsEmailInvoice:true
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:363) - Ajency.in :: SYNC retail store pinelabs config truestore id :4033imeiaasasa merchant code asasas active:false
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (Warehouse.java:337) - Setting gstin = 27AAECB5311J1ZU for warehouse MUM Bandra
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:897) - Ajency.in:: Vendor for seek invoice number => BLC
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:856) - Calling Bright to get seek invoice count
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:897) - Ajency.in:: Vendor for seek invoice number => AQUA
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:963) - Existing Vendor Mapping updated for store 4033 with vendor 2
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:963) - Existing Vendor Mapping updated for store 4033 with vendor 1
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:422) - Ajency.in:: Updating Retail Store Payment mode mapping for the store : 4033
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode COUNTER_CASH store ID : 4033
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode CARD_PAYMENT store ID : 4033
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode PAYTM_WALLET store ID : 4033
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode SPLIT store ID : 4033
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode SWIGGY store ID : 4033
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode PAYTM_VOUCHER store ID : 4033
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode UPI_VIA_EDC_MACHINE store ID : 4033
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode PAYU_STATIC_QR store ID : 4033
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:693) - Ajency.in :: WAREHOUSE VENDOR GSTIN :: Mapping Updated for Warehouse Id 4033 and Vendor Id 2 with GSTIN : 27AAECB5311J1ZU
[ INFO] [] [http-nio-8181-exec-7] (04 Feb 2020 10:49:42) (HKAPIRetailStoreServiceImpl.java:693) - Ajency.in :: WAREHOUSE VENDOR GSTIN :: Mapping Updated for Warehouse Id 4033 and Vendor Id 1 with GSTIN : 27AAJCA6439P1ZZ
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:333) - Ajency.in:: Updating retail store:: MUM Bandra
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:356) - Ajency.in :: SYNC retail store old SendSmsEmailInvoice true saved to store new SendSmsEmailInvoice:true
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:363) - Ajency.in :: SYNC retail store pinelabs config truestore id :4033imeiaasasa merchant code asasas active:false
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (Warehouse.java:337) - Setting gstin = 27AAECB5311J1ZU for warehouse MUM Bandra
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:897) - Ajency.in:: Vendor for seek invoice number => BLC
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:856) - Calling Bright to get seek invoice count
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:897) - Ajency.in:: Vendor for seek invoice number => AQUA
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:963) - Existing Vendor Mapping updated for store 4033 with vendor 2
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:963) - Existing Vendor Mapping updated for store 4033 with vendor 1
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:422) - Ajency.in:: Updating Retail Store Payment mode mapping for the store : 4033
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode COUNTER_CASH store ID : 4033
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode CARD_PAYMENT store ID : 4033
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode PAYTM_WALLET store ID : 4033
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode SPLIT store ID : 4033
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode SWIGGY store ID : 4033
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode PAYTM_VOUCHER store ID : 4033
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode UPI_VIA_EDC_MACHINE store ID : 4033
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:461) - Ajency.in :: Updating Store Payment mode mapping aquaPaymentMode PAYU_STATIC_QR store ID : 4033
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:473) - Ajency.in:: Updating Retail Store payment mode :: newEditStorePaymentModeMapping not null 
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:693) - Ajency.in :: WAREHOUSE VENDOR GSTIN :: Mapping Updated for Warehouse Id 4033 and Vendor Id 2 with GSTIN : 27AAECB5311J1ZU
[ INFO] [] [http-nio-8181-exec-2] (04 Feb 2020 10:49:47) (HKAPIRetailStoreServiceImpl.java:693) - Ajency.in :: WAREHOUSE VENDOR GSTIN :: Mapping Updated for Warehouse Id 4033 and Vendor Id 1 with GSTIN : 27AAJCA6439P1ZZ

`

**Comment by shivam-kurtarkar** [comment]
will give error occurred while initiating transaction

**Comment by larissa-c-d** [comment]
**Suggestion:**
"Failed to Initiate Transaction, please try again.
Error occurred, cannot initiate transaction" message should be should be changed to 

**"Error occurred, cannot initiate transaction"**

**Comment by shivam-kurtarkar** [comment]
Error occurred while initiating transaction

**Comment by larissa-c-d** [comment]
"Failed to Initiate Transaction, please try again.
Error occurred while initiating transaction" message is displayed
