### ISSUE TITLE
Data is not populated in the Customer_order_transaction_details_payu table.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1267]
Actual result
Data is not populated in the Customer_order_transaction_details_payu table.

Expected result
Data should be populated in the Customer_order_transaction_details_payu table.

Steps
Go to the POS screen 
Scan the barcode
Enter the details
Select the PayU payment mode
Click on initiate transaction 
Change the status of the transaction to 3
Click on get status.
Click on receive payment.

![image](https://user-images.githubusercontent.com/54023516/73811030-5023a500-47fe-11ea-9684-3fae08aedc90.png)
![image](https://user-images.githubusercontent.com/54023516/73811062-6a5d8300-47fe-11ea-9d9f-42bfb12a1118.png)

**Comment by shivam-kurtarkar** [comment]
on manual changing status doesnt add details
details populated only after success
now details should show up after get status fail or success irrespective
