### ISSUE TITLE
PayU payment mode is displayed in the payment mode dropdown on the BO search page for SIS store.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1269]
Actual result
PayU payment mode is displayed in the payment mode dropdown on the BO search page for SIS store.

Expected result
PayU payment mode should not be displayed in the payment mode dropdown on the BO search page for SIS store.

Steps
Go to the BO search page for SIS store
Check the payment mode dropdown.

![image](https://user-images.githubusercontent.com/54023516/73811774-603c8400-4800-11ea-83d5-e7120d1df215.png)

**Comment by shivam-kurtarkar** [comment]
search page is generic hence all payment modes are shown
