### ISSUE TITLE
Item level percentage discount on item value not getting applied 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#127]
Precondition:Fefo disabled
Scan the barcode
Apply Item level percentage discount on item value and observe

Actual result: Item level percentage discount on item value not getting applied 

![image](https://user-images.githubusercontent.com/14803102/48128729-59e1f400-e2ad-11e8-92c8-8ae5a4c13133.png)

**Comment by ambksud** [comment]
Issue Resolved
