### ISSUE TITLE
cannot initiate transaction on POS.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1270]
Actual result
cannot initiate transaction on POS, message "Failed to Initiate Transaction, please try again." is displayed.

Steps
store:4033
Go to the POS screen 
Scan the barcode
Enter the details
Select the PayU payment mode
Click on initiate transaction 
![image](https://user-images.githubusercontent.com/54023516/73812809-23728c00-4804-11ea-8bef-35f18c9dcce3.png)

![image](https://user-images.githubusercontent.com/54023516/73812787-0e95f880-4804-11ea-81bf-61976a4441b8.png)

![image](https://user-images.githubusercontent.com/54023516/73812750-ed350c80-4803-11ea-9c9e-556cdc47682d.png)
![image](https://user-images.githubusercontent.com/54023516/73812835-38e7b600-4804-11ea-9769-3e38633f1868.png)

`[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:2792) - Ajency.in :: payment mode : 700: PayU Static QR
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:2803) - Ajency.in :: payment mode upi || card || split
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:2811) - Ajency.in :: trying to fetch customer order by id :1236342
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:2834) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (ThirdPartyPaymentServiceImpl.java:466) - Ajency.in :: has pending transactions false for 1236342
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:5963) - user id:5590881
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:5964) - user gender:FEMALE
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:5973) - Ajency.in :: Invoice email :5590881suraj.rathore@brightlifecare.com
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:2737) - Ajency.in :: pos cart dto , coupon code: null
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:3926) - Ajency.in :: IsHKMembership: false skuItem Id: 8056960 skuItem: null
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:3933) - Ajency.in :: updated skuItem: com.hk.domain.sku.SkuItem@34cf3196 vendor : 2
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:3951) - offer dto is null ?true, offer id =169939
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:3952) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/offer/169939?z.ts==1580879017216&st=1&rstId=4033  RC: 200
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (HkHttpClient.java:129) -  parsing T:2 ms 
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:3956) - offerdto coupon code :215MUSCLE
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:2845) - Ajency.in :: customer : 684b985965a6b00d684f52ed3dd33bc7 address 3423322 store 4033
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSServiceImpl.java:753) - Ajency.in :: updating customer order :1236342
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSServiceImpl.java:764) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (POSAction.java:2854) - Ajency.in :: final payable  rounded amount :1405.0
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (ThirdPartyPaymentServiceImpl.java:59) - Ajency.in :: customer order id :1236342 transaction id 1236342-1580879017294
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (PayuServiceImpl.java:79) - Ajency.in :: transaction number :1236342-1580879017294 amount:140500
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (PayuServiceImpl.java:416) - Ajency.in :: fetching payu config for store 4033
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (PayuServiceImpl.java:420) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@654c0429
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (PayuServiceImpl.java:424) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@654c0429 qrid:STQI-IM4033o1-136227
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (PayuServiceImpl.java:104) - Ajency.in :: making url call to   https://mobiletest.payu.in/QrPayment
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (PayuApiRequest.java:78) - data : vDy3i7|1236342-1580879017294|140500|Integrated Static QR|||3600|STQI-IM4033o1-136227|||||||||ozyEFwfA
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (PayuApiRequest.java:79) - hash : 5ca5f16595ceeb8c5e6eb5410f5678b40a0640053b6e21f3f2d1462a135f6c1e648956d400249789bd8e55bf25e16158536f76e1d96afc28f01cd67fc2f7f2cc
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:37) (PayuServiceImpl.java:450) - post data to payu gateway: key=vDy3i7&hash=5ca5f16595ceeb8c5e6eb5410f5678b40a0640053b6e21f3f2d1462a135f6c1e648956d400249789bd8e55bf25e16158536f76e1d96afc28f01cd67fc2f7f2cc&txnid=1236342-1580879017294&amount=140500&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-IM4033o1-136227
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (PayuServiceImpl.java:468) - Ajency.in :: retval {"status":"failed","message":"There is transaction which is in progress against given qr id.","errorCode":"E2043"}
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (PayuServiceImpl.java:500) - {"status":"failed","message":"There is transaction which is in progress against given qr id.","errorCode":"E2043","map":{}}
[ERROR] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (PayuServiceImpl.java:109) - Ajency.in :: payu api call :failed : There is transaction which is in progress against given qr id.
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (PayuServiceImpl.java:131) - Ajency.in :: payu response {"status":"failed","message":"There is transaction which is in progress against given qr id.","errorCode":"E2043","map":{}}
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (PayuServiceImpl.java:138) - Ajency.in :: payu api call for transaction 1236342-1580879017294
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (PayuServiceImpl.java:139) - Ajency.in :: messages: There is transaction which is in progress against given qr id.
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (ThirdPartyPaymentServiceImpl.java:94) - Ajency.in :: saved customerOrderTransaction 1287 transactionId :1236342-1580879017294
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (POSAction.java:2864) - Ajency.in :: pos action transaction status :FAILED
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (ThirdPartyPaymentServiceImpl.java:466) - Ajency.in :: has pending transactions false for 1236342
[ INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (ThirdPartyPaymentServiceImpl.java:479) - Ajency.in :: hasActivePinelabsConfig true store 4033

`

**Comment by shivam-kurtarkar** [comment]
open transaction message is now printed on ui

**Comment by larissa-c-d** [comment]
> open transaction message is now printed on ui

Ajency.in :: has pending transactions false for 1236342 is displayed

**Comment by shivam-kurtarkar** [comment]
INFO] [] [http-nio-8181-exec-8] (05 Feb 2020 10:33:38) (PayuServiceImpl.java:468) - Ajency.in :: retval {"status":"failed","message":"There is transaction which is in progress against given qr id.","errorCode":"E2043"}
