### ISSUE TITLE
Allows to initiate a transaction when there is a void transaction.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1271]
Actual result
Allows to initiate a transaction when there is a void transaction.

1. Go to the POS screen 
2. Scan the barcode
3. Enter the details
4.Select the split payment mode
5. Select the PayU payment mode and counter cash
6. Click on initiate transaction 
7. Change the status of the transaction to 3
8. Click on cancel transaction
9. Repeat steps 1 to 7 

![image](https://user-images.githubusercontent.com/54023516/73813921-89acde00-4807-11ea-879e-df2432183ca4.png)

**Comment by shivam-kurtarkar** [comment]
please attach logs
ambiguous what is happening
transaction is not actually success its open cause of manual changing

**Comment by shivam-kurtarkar** [comment]
1. void call doesn't work on test url
2. payu is static qr based there is no machine hence if you initiate void transaction(refund) after that you can initiate again without having to settle it
