### ISSUE TITLE
payment_transaction_id is not displayed in the customer_order_transaction table

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1272]
Actual result
payment_transaction_id is not displayed in the customer_order_transaction table in case of PayU payment mode.

![image](https://user-images.githubusercontent.com/54023516/73814684-ca0d5b80-4809-11ea-94cb-ed1de7e1d3ba.png)

**Comment by shivam-kurtarkar** [comment]
mihpay is only updated in payment_transaction_id after get status
