### ISSUE TITLE
Transaction is cancelled when the of the hash is value is incorrect.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1273]
Actual result
Transaction is cancelled when the of the hash is value is incorrect.
![image](https://user-images.githubusercontent.com/54023516/73819449-90dae880-4815-11ea-927d-c5e9a695a7b9.png)

![image](https://user-images.githubusercontent.com/54023516/73819421-7f91dc00-4815-11ea-818d-dec17dbec112.png)

`[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (POSAction.java:3073) - Ajency.in :: Customer Order Transaction Id1293
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (ThirdPartyPaymentServiceImpl.java:262) - Ajency.in :: cancelling transaction, id:1293
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (ThirdPartyPaymentServiceImpl.java:125) - Ajency.in :: user 15563757 customerOrder Transcation id 1293
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (ThirdPartyPaymentServiceImpl.java:130) - Ajency.in :: payu get status ...
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (ThirdPartyPaymentServiceImpl.java:167) - Ajency.in :: payu getting status from db..
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (ThirdPartyPaymentServiceImpl.java:212) - Ajency.in :: customer
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (ThirdPartyPaymentServiceImpl.java:274) - Ajency.in :: making cancel api call for transaction id:null
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (PayuServiceImpl.java:214) - Ajency.in :: transaction number :1236351-1580886113233
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (PayuServiceImpl.java:414) - Ajency.in :: fetching payu config for store 4033
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (PayuServiceImpl.java:418) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@52e07222
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (PayuServiceImpl.java:422) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@52e07222 qrid:STQI-IM4033o1-136227
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (PayuServiceImpl.java:241) - Ajency.in :: making url call to  https://mobiletest.payu.in/merchant/postservice.php
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (PayuApiRequest.java:59) - data : vDy3i7|cancel_qr_payment|{"transactionId":"1236351-1580886113233"}|ozyEFwfA
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (PayuApiRequest.java:60) - hash : 7547672c4be7ef954e265307bacf52d215da849e17f837171e81c2b1e6d4161d5bdffeba4947b149d38e890c2989413b79792654d0e33eec41ac2a5c0cc198b8
[ERROR] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (PayuApiRequest.java:119) - Ajency.in :: Error occurred while injecting incorrect hash 
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (PayuServiceImpl.java:448) - post data to payu gateway: key=vDy3i7&command=cancel_qr_payment&hash=7547672c4be7ef954e265307bacf52d215da849e17f837171e81c2b1e6d4161d5bdffeba4947b149d38e890c2989413b79792654d0e33eec41ac2a5c0cc198b8&var1=%7B%22transactionId%22%3A%221236351-1580886113233%22%7D
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:03) (PayuServiceImpl.java:466) - Ajency.in :: retval {"status":"success","message":"Cancellation Successful"}
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:03) (PayuServiceImpl.java:498) - {"status":"success","message":"Cancellation Successful","map":{}}
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:03) (PayuServiceImpl.java:257) - Ajency.in :: payu response {"status":"success","message":"Cancellation Successful","map":{}}
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:03) (PayuServiceImpl.java:267) - Ajency.in :: payu api call for transaction 1236351-1580886113233
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:03) (PayuServiceImpl.java:268) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:03) (POSAction.java:3081) - Ajency.in :: pos action transaction status :CANCELLED
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:03) (ThirdPartyPaymentServiceImpl.java:473) - Ajency.in :: has pending transactions false for 1236351
[ INFO] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:03) (ThirdPartyPaymentServiceImpl.java:486) - Ajency.in :: hasActivePinelabsConfig true store 4033
`

**Comment by shivam-kurtarkar** [comment]
[ERROR] [] [http-nio-8181-exec-2] (05 Feb 2020 12:35:00) (PayuApiRequest.java:119) - Ajency.in :: Error occurred while injecting incorrect hash 

injecting hash was giving error now fixed

**Comment by larissa-c-d** [comment]
"Error occurred while cancelling transaction.
Error occurred while canceling transaction." message is displayed

Expected 
"Error occurred while cancelling transaction." message should be displayed

![image](https://user-images.githubusercontent.com/54023516/74313647-145a8380-4d9a-11ea-81bb-018df83889df.png)

**Comment by larissa-c-d** [comment]
Failed to cancel transaction.
Error occurred while **canceling** transaction. should be changed to
Failed to cancel transaction.
Error occurred while **cancelling** transaction.
