### ISSUE TITLE
payment status is fetched when the the hash value if incorrect for debugHashValue.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1274]
Actual result
payment status is fetched when the the hash value if incorrect for debugHashValue.

steps
Set an incorect hash value fordebugHashValue.
Go to the POS screen 
Scan the barcode
Enter the details
Select the PayU payment mode
Click on initiate transaction 
Click on get status.

`
[ INFO] [] [pool-24-thread-1] (05 Feb 2020 12:53:32) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (05 Feb 2020 12:53:32) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (POSAction.java:2936) - Ajency.in :: payment mode : 700: PayU Static QR
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (POSAction.java:2938) - Ajency.in :: customer name:test phone:9999999999 email:null pincode: null gender:FEMALE
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (ThirdPartyPaymentServiceImpl.java:125) - Ajency.in :: user 15563757 customerOrder Transcation id 1294
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (ThirdPartyPaymentServiceImpl.java:130) - Ajency.in :: payu get status ...
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (ThirdPartyPaymentServiceImpl.java:167) - Ajency.in :: payu getting status from db..
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (ThirdPartyPaymentServiceImpl.java:212) - Ajency.in :: customer
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (POSAction.java:2953) - Ajency.in :: pos action transaction status :OPEN
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (ThirdPartyPaymentServiceImpl.java:463) - Ajency.in :: has pending transactions true
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (POSAction.java:3039) - Ajency.in :: hasPendingOrCompleteTransactions :true
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (POSAction.java:3041) - Ajency.in :: customer name:test phone:9999999999 email:null pincode: null gender:FEMALE
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (ThirdPartyPaymentServiceImpl.java:463) - Ajency.in :: has pending transactions true
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 12:55:40) (ThirdPartyPaymentServiceImpl.java:486) - Ajency.in :: hasActivePinelabsConfig true store 4033
`

**Comment by shivam-kurtarkar** [comment]
the debugHash value is now only for cancel

will not affect any other api
