### ISSUE TITLE
update customer info button not disabled, when the transaction is initiated.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1276]
Actual result
update customer info button not disabled, when the transaction is initiated.

Steps
Go to the POS screen 
Scan the barcode
Enter the details
Select the PayU payment mode 
Click on initiate transaction 
Go to the console make the age dropdown editable.
Change the age and click on update customer details.

![image](https://user-images.githubusercontent.com/54023516/73828444-419db380-4827-11ea-9bca-d5d1f26395d0.png)

**Comment by shivam-kurtarkar** [comment]
from image it looks lik nothing is disabled.
also to make it enabled what did you do?

**Comment by sharangsamonkar** [comment]
follow pinelabs behaviour

**Comment by shivam-kurtarkar** [comment]
button is greyed out too

**Comment by larissa-c-d** [comment]
button not greyed out
![image](https://user-images.githubusercontent.com/54023516/74320317-6b665580-4da6-11ea-86d2-5679eaad34d4.png)

**Comment by larissa-c-d** [comment]
> button is greyed out too

button not greyed out
![image](https://user-images.githubusercontent.com/54023516/74320317-6b665580-4da6-11ea-86d2-5679eaad34d4.png)

**Comment by larissa-c-d** [comment]
issue resolved , button is greyed out
