### ISSUE TITLE
"Error occurred while cancelling transaction. TRANSACTION NOT FOUND" message is displayed when cancelling a transaction from open transactions UI in case of card payment but the transaction is cancelled.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1277]
Actual result
"Error occurred while cancelling transaction. TRANSACTION NOT FOUND" message is displayed when cancelling a transaction from open transactions UI in case of card payment but the transaction is cancelled.

Steps
Go to the POS screen 
Scan the barcode
Enter the details
Select the card payment mode 
Click on initiate transaction 
Go to the open transactions
Click on cancel transaction for the 

![image](https://user-images.githubusercontent.com/54023516/73832360-06eb4980-482e-11ea-8852-6972b8a3864b.png)
![image](https://user-images.githubusercontent.com/54023516/73832803-d821a300-482e-11ea-92ec-aedcaf051227.png)

**Comment by sharangsamonkar** [comment]
@larissa-c-d Is this card or payu?

**Comment by larissa-c-d** [comment]
credit/debit card
