### ISSUE TITLE
Incorrect MRP level discount getting applied on PL when product scanned are PL and NPL

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#128]
Go to POS
Scan one  PL product and one NPL product
Apply MRP level discount  Eg: Item level 800 flat on MRP

Actual Result: When Item level 800 flat on MRP is applied, only 329 amount is getting applied on PL product.

![image](https://user-images.githubusercontent.com/14803102/48177816-c0622300-e33c-11e8-853e-98d2678d742b.png)

**Comment by pitre55** [comment]
similar to already raised Live Issue: #69
