### ISSUE TITLE
"Error occurred while cancelling transaction. DB OPERATION FAILED" message is displayed on click of cancel transaction on the open transactions ui page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1280]
Actual result'
"Error occurred while cancelling transaction. DB OPERATION FAILED" message is displayed on click of cancel transaction on the open transactions ui page.

Steps
Go to the POS screen 
Scan the barcode.
Enter the details.
Select the split payment mode 
select credit card payment mode
Click on initiate transaction 
Go to the open transaction 
Click on the cancel transaction

![image](https://user-images.githubusercontent.com/54023516/73836656-cf809b00-4835-11ea-84bb-d4d35178712d.png)

`[ INFO] [] [pool-24-thread-1] (05 Feb 2020 16:32:02) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (05 Feb 2020 16:32:02) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 16:36:12) (ThirdPartyPaymentServiceImpl.java:262) - Ajency.in :: cancelling transaction, id:1315
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 16:36:12) (ThirdPartyPaymentServiceImpl.java:125) - Ajency.in :: user 15563757 customerOrder Transcation id 1315
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 16:36:12) (ThirdPartyPaymentServiceImpl.java:212) - Ajency.in :: customer
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 16:36:12) (ThirdPartyPaymentServiceImpl.java:274) - Ajency.in :: making cancel api call for transaction id:55403
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 16:36:12) (PinelabsServiceImpl.java:466) - Ajency.in :: fetching pinelabs config for store 4033
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 16:36:12) (PinelabsServiceImpl.java:239) - Ajency.in :: pinelabs params {"SecurityToken":"661c9a5f-5d7a-4d76-a950-68beb8225cfd","Amount":387900,"PlutusTransactionReferenceID":55403,"MerchantStorePosCode":"04190588","IMEI":"IM239018","MerchantID":2300}
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 16:36:12) (PinelabsServiceImpl.java:244) - Ajency.in :: making url call to  https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/CancelTransaction
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 16:36:29) (PinelabsServiceImpl.java:255) - Ajency.in :: Pinelabs api call :1 : DB OPERATION FAILED
[ INFO] [] [http-nio-8181-exec-6] (05 Feb 2020 16:36:29) (PinelabsServiceImpl.java:268) - Ajency.in :: pinelabs response {"responseCode":1,"responseMessage":"DB OPERATION FAILED"}
[ERROR] [] [http-nio-8181-exec-6] (05 Feb 2020 16:36:29) (OpenTransactionUiAction.java:57) - Ajency.in :: Error occured when cancelling order status:1
`

**Comment by shivam-kurtarkar** [comment]
pine labs is down
