### ISSUE TITLE
transaction cannot be cancelled.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1282]
Actual result
transaction cannot be cancelled.

![image](https://user-images.githubusercontent.com/54023516/73844071-d6afa500-4845-11ea-9d8e-1c57ee2441c4.png)

1236364-1580906675654

**Comment by shivam-kurtarkar** [comment]
please attach logs

**Comment by shivam-kurtarkar** [comment]
incoorect hash  was being injected

**Comment by larissa-c-d** [comment]
parsing issue
