### ISSUE TITLE
initiate payment button is active on loading POS screen if the payment mode is not  PayU,card payment and UPI

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1287]
Actual result
initiate payment button is active on loading POS screen if the payment mode is not  PayU,card payment and UPI

steps 
go to the POS screen

![image](https://user-images.githubusercontent.com/54023516/73917369-432db100-48e5-11ea-9502-ac3660a0d356.png)

**Comment by shivam-kurtarkar** [comment]
FOR UI ISSUES PLEASE ATTACH **JS CONSOLE LOGS**
this was cause js was breaking.
