### ISSUE TITLE
Flat Order level discount is getting applied on NPL product

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#129]
Go to POS screen
Scan only  NPL product  eg: ON (Optimum Nutrition) Gold Standard 100% Whey Protein, 5 lb Double Rich Chocolate (NUT304-27)
Apply Flat Order level discount 

Actual result: Flat Order level discount is getting applied on NPL product

![image](https://user-images.githubusercontent.com/14803102/48178175-55b1e700-e33e-11e8-94e1-f4bf2a26e331.png)

**Comment by ambksud** [comment]
Issue Resolved
