### ISSUE TITLE
Qid should be  displayed as a compulsory field if the "Enable payu config" is checked.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1297]
Actual result
Qid should be displayed as a  compulsory field if the "Enable payu config" is checked.

Expected result
Asterisk mark should be displayed if the enable payu config is checked. 

Steps
Go to the create a retail store page
Go to the edit retail store page

![image](https://user-images.githubusercontent.com/54023516/74007026-53a46100-49a3-11ea-8531-96c2cce42c64.png)

**Comment by shivam-kurtarkar** [comment]
@sharangsamonkar

**Comment by shivam-kurtarkar** [comment]
config and enabling mode are kept separate
