### ISSUE TITLE
PayU config should be a compulsory field when the PayU payment mode is selected.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1298]
Actual result
PayU config is not compulsory field when the PayU payment mode is selected.

Expected result
PayU config should be a compulsory field when the PayU payment mode is selected.

Steps
Go to create a retail store page
Select the payment mode as PayU
Do not enable the PayU config

![image](https://user-images.githubusercontent.com/54023516/74010528-b7cb2300-49ab-11ea-81e8-3934fdd9ab8d.png)

**Comment by shivam-kurtarkar** [comment]
@sharangsamonkar

**Comment by shivam-kurtarkar** [comment]
config and enabling mode are kept separate
