### ISSUE TITLE
Error: PAGE_NAME_CANNOT_BE_BLANK message is displayed on click of create a retail store page

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1300]
Actual result
Error: PAGE_NAME_CANNOT_BE_BLANK message is displayed on click of create a retail store page
![image](https://user-images.githubusercontent.com/54023516/74016593-b05e4680-49b8-11ea-8166-2506d2c841ab.png)

![image](https://user-images.githubusercontent.com/54023516/74016239-1a2a2080-49b8-11ea-8470-519c223387eb.png)

**Comment by shivam-kurtarkar** [comment]
master issue

**Comment by shivam-kurtarkar** [comment]
#1293 after removing null pointer this occurs 
should i put name as "error" that would solve name issue and should solve both issues

**Comment by sharangsamonkar** [comment]
Happened due to #1293 . Will be reverted.

@larissa-c-d 
Check once reverted.

**Comment by larissa-c-d** [comment]
#1300 is reverted to #1293
