### ISSUE TITLE
customer_order_transaction_details_payu table does not have the status column.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1302]
Actual result
customer_order_transaction_details_payu table does not have the status column.

Expected result
customer_order_transaction_details_payu table should have the status column.

![image](https://user-images.githubusercontent.com/54023516/74024451-ee169b80-49c7-11ea-8ac8-6be9cd813e18.png)

**Comment by shivam-kurtarkar** [comment]
no more needed as its there in main table
