### ISSUE TITLE
Amount displayed on the open transaction UI page does not match the total on the checkout page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1304]
![image](https://user-images.githubusercontent.com/54023516/74025820-ce34a700-49ca-11ea-97dc-9512c55de75f.png)

![image](https://user-images.githubusercontent.com/54023516/74025788-be1cc780-49ca-11ea-9aee-719ea15e68bc.png)
![image](https://user-images.githubusercontent.com/54023516/74025849-e1e00d80-49ca-11ea-99e2-df6effeae5f5.png)

**Comment by shivam-kurtarkar** [comment]
final payable is same
