### ISSUE TITLE
payu not displayed for split payment 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1309]
Actual result
payu not displayed for split payment 

Expected result
Payu should be displayed.

![image](https://user-images.githubusercontent.com/54023516/74031405-705a8c00-49d7-11ea-985d-19c3fe3df1a6.png)

**Comment by shivam-kurtarkar** [comment]
payu not displayed for hk.com on split

**Comment by larissa-c-d** [comment]
issue resolved, payu payment mode is displayed
