### ISSUE TITLE
"Failed to Initiate Transaction, please try again" message is displayed when trying to initiate transaction.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1314]
Actual result
"Failed to Initiate Transaction, please try again" message is displayed when trying to initiate transaction.

![image](https://user-images.githubusercontent.com/54023516/74142360-b3f30700-4c1e-11ea-97b0-47b7f13f9c62.png)

![image](https://user-images.githubusercontent.com/54023516/74142384-c2412300-4c1e-11ea-878c-10ade92a179e.png)

`[ INFO] [] [http-nio-8181-exec-7] (10 Feb 2020 15:24:40) (PayuServiceImpl.java:438) - Ajency.in :: fetching payu config for store 4034
[ INFO] [] [http-nio-8181-exec-7] (10 Feb 2020 15:24:40) (PayuServiceImpl.java:442) - Ajency.in :: store payu config :null
[ERROR] [] [http-nio-8181-exec-7] (10 Feb 2020 15:24:40) (PayuServiceImpl.java:460) - Failed to fetch payu config
[ERROR] [] [http-nio-8181-exec-7] (10 Feb 2020 15:24:40) (PayuServiceImpl.java:90) - Failed to get payu config
[ INFO] [] [http-nio-8181-exec-7] (10 Feb 2020 15:24:40) (ThirdPartyPaymentServiceImpl.java:94) - Ajency.in :: saved customerOrderTransaction 1 transactionId :1386481-1581328480090
[ERROR] [] [http-nio-8181-exec-7] (10 Feb 2020 15:24:40) (POSAction.java:2873) - Ajency.in :: logging error
[ INFO] [] [http-nio-8181-exec-7] (10 Feb 2020 15:24:40) (ThirdPartyPaymentServiceImpl.java:484) - Ajency.in :: has pending transactions false for 1386481
[ INFO] [] [http-nio-8181-exec-7] (10 Feb 2020 15:24:40) (ThirdPartyPaymentServiceImpl.java:497) - Ajency.in :: hasActivePinelabsConfig false store 4034
[ INFO] [] [pool-24-thread-1] (10 Feb 2020 15:28:49) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (10 Feb 2020 15:28:49) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false`

**Comment by shivam-kurtarkar** [comment]
it failed because payu config was not found 
message is added
