### ISSUE TITLE
Cancel button is not displayed when the message "Pincode courier mapping not found" is displayed

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1316]
Actual result
Cancel button is not displayed when the message "Pincode courier mapping not found" is displayed

Steps
Go to hk.com
Select the payment  mode as payu
Click on initiate transaction
Change the status of the transaction to 3
Click on get status 
Click on mark as packed

![image](https://user-images.githubusercontent.com/54023516/74145255-58c41300-4c24-11ea-8ea2-43e83e7abfd7.png)

**Comment by sharangsamonkar** [comment]
Good catch.

**Comment by shivam-kurtarkar** [comment]
![image](https://user-images.githubusercontent.com/52652317/74319707-6359e600-4da5-11ea-99e0-7311b4ae74e2.png)
