### ISSUE TITLE
HTTP Status 500 – Internal Server Error is displayed on hk.com page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1329]
**link:** http://aqua61.healthkartqa.com/pages/hk/hkOrderDetails.jsp
Store:GGN vpk bright
`HTTP Status 500 – Internal Server Error
Type Exception Report

Message An exception occurred processing JSP page [/pages/hk/hkOrderDetails.jsp] at line [80]

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.apache.jasper.JasperException: An exception occurred processing JSP page [/pages/hk/hkOrderDetails.jsp] at line [80]

77:   }
78:    MaskUtilService maskUtilService =  (MaskUtilService) ServiceLocatorFactory.getService(MaskUtilService.class);
79:  %>
80:   <s:useActionBean beanclass="com.hk.web.action.admin.order.HKOrderAction" event="pre" var="hkOrderAction"/>
81:   <s:layout-component name="htmlHead">
82:       <!--<link href="${pageContext.request.contextPath}/css/calendar-blue.css" rel="stylesheet" type="text/css"/>
83:       <script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.dynDateTime.pack.js"></script>

Stacktrace:
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:584)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
Root Cause

javax.servlet.ServletException: net.sourceforge.stripes.exception.StripesJspException: Unabled to prepare ActionBean for JSP Usage
	org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:905)
	org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:838)
	org.apache.jsp.pages.hk.hkOrderDetails_jsp._jspService(hkOrderDetails_jsp.java:2587)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
Root Cause

java.lang.reflect.InvocationTargetException
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	net.sourceforge.stripes.tag.UseActionBeanTag.doStartTag(UseActionBeanTag.java:163)
	org.apache.jsp.pages.hk.hkOrderDetails_jsp._jspService(hkOrderDetails_jsp.java:380)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
Root Cause

org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [com.hk.domain.courier.Awb#4478323]
	org.hibernate.internal.SessionFactoryImpl$1$1.handleEntityNotFound(SessionFactoryImpl.java:253)
	org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:262)
	org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:176)
	org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:286)
	org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:185)
	com.hk.domain.courier.Awb_$$_jvst65f_ef.getAwbNumber(Awb_$$_jvst65f_ef.java)
	com.hk.web.action.admin.order.HKOrderAction.pre(HKOrderAction.java:233)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	net.sourceforge.stripes.tag.UseActionBeanTag.doStartTag(UseActionBeanTag.java:163)
	org.apache.jsp.pages.hk.hkOrderDetails_jsp._jspService(hkOrderDetails_jsp.java:380)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/8.5.20`

**Comment by shivam-kurtarkar** [comment]
org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [com.hk.domain.courier.Awb#4478323]
data was missing

**Comment by larissa-c-d** [comment]
issue resolved
