### ISSUE TITLE
Carry forward quantity is not getting  updated correctly in daily_sales table

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#133]
Weight flag enabled > weight set =20kg
warehouse Id: 4095 
z=6  C=3 X=5 -> Case 2 executed
ST  is not created because of weight check, carry forward quantity is X-C ie 2 -> 
Run the cron again,  ST is not created due to weight check, but carry forward quantity becomes 6 instead of 4.

**Comment by ambksud** [comment]
Issue Resolved
