### ISSUE TITLE
Transaction for credit/debit card can be initiated when there is an open transaction for Payu

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1333]
Actual result
Transaction for credit/debit card can be initiated when there is an open transaction for Payu

Steps
Go to the pos screen 
Select the payment mode as payu
initiate a transaction
Open a new tab 
Go to the pos screen 
scan a barcode
Select the payment mode as credit/debit card
Click on initiate transaction

![image](https://user-images.githubusercontent.com/54023516/74306841-ba51c200-4d89-11ea-927d-8f2836af2ad5.png)

![image](https://user-images.githubusercontent.com/54023516/74306841-ba51c200-4d89-11ea-927d-8f2836af2ad5.png)
![image](https://user-images.githubusercontent.com/54023516/74306874-d2294600-4d89-11ea-9d04-b18fe12105e3.png)
`4&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-20] (12 Feb 2020 11:19:24) (POSHelper.java:192) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-20] (12 Feb 2020 11:19:24) (POSAction.java:3983) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-20] (12 Feb 2020 11:19:24) (POSAction.java:3984) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-20] (12 Feb 2020 11:19:24) (ThirdPartyPaymentServiceImpl.java:494) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-20] (12 Feb 2020 11:19:24) (ThirdPartyPaymentServiceImpl.java:496) - Ajency.in :: has pending transactions false for null
[ INFO] [] [http-nio-8181-exec-20] (12 Feb 2020 11:19:24) (ThirdPartyPaymentServiceImpl.java:509) - Ajency.in :: hasActivePinelabsConfig true store 4034
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:30) (POSAction.java:1801) - Ajency.in :: NUT CONVERSION :: No ProductVariantConversionDetails found.
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:30) (POSAction.java:1751) - Ajency.in :: Liquidation Discount not applicable for the scanned barcode : IVN-1401815-1148
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/variant/86409?z.ts==1581486570900&st=1&rtSt=4034&offerPerPage=20&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/variant/86409?z.ts==1581486571329&st=1&rtSt=4034&offerPerPage=20&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (POSServiceImpl.java:813) - Ajency.in :: fefo enabled true
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (POSServiceImpl.java:828) - Fefo discount not applicable for variant Nouriza Peanut Butter 100% Natural Unsweetened,  1 kg  Crunchy 
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (ProductVariantServiceImpl.java:471) - Ajency.in :: NPL FLASH Discount Config true
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (ProductVariantServiceImpl.java:473) - Ajency.in :: flash discount enabled for store
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/sale/flashDeal/0/HNUT10541-06?z.ts==1581486571628&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (POSServiceImpl.java:844) - Ajency.in :: Liquidation Discount :: Offer price before liquidation Discount is applied : 375.01
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (POSHelper.java:105) - Ajency.in:: Adding vendor to poslineitems >= 2
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (POSHelper.java:192) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (POSAction.java:3983) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (POSAction.java:3984) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (HkVariantServiceImpl.java:129) - Ajency.in :: POS OFFER INVENTORY CHECK ::  No Variant On Action Extra 10% off on Site Wide
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (HkVariantServiceImpl.java:88) - Ajency.in :: POS OFFER INVENTORY CHECK :: Offer Valid after inventory check 
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (ThirdPartyPaymentServiceImpl.java:494) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (ThirdPartyPaymentServiceImpl.java:496) - Ajency.in :: has pending transactions false for null
[ INFO] [] [http-nio-8181-exec-14] (12 Feb 2020 11:19:31) (ThirdPartyPaymentServiceImpl.java:509) - Ajency.in :: hasActivePinelabsConfig true store 4034
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSAction.java:2819) - Ajency.in :: payment mode : 100: Credit/Debit Card
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSAction.java:2841) - Ajency.in :: creating customer order
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSAction.java:5996) - user id:5590881user gender:FEMALE
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSAction.java:6005) - Ajency.in :: Invoice email :5590881suraj.rathore@brightlifecare.com
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSAction.java:2764) - Ajency.in :: pos cart dto , coupon code: null
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSHelper.java:192) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSAction.java:3983) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSAction.java:3984) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSServiceImpl.java:764) - Ajency.in :: updating customer order :null
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSServiceImpl.java:775) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSAction.java:2851) - Ajency.in :: customer order created id 1386498
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (POSAction.java:2880) - Ajency.in :: final payable  rounded amount :375.0
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (ThirdPartyPaymentServiceImpl.java:60) - Ajency.in :: customer order id :1386498 transaction id 1386498-1581486596522
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (PinelabsServiceImpl.java:68) - Ajency.in :: transaction number :1386498-1581486596522 amount:37500
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (PinelabsServiceImpl.java:468) - Ajency.in :: fetching pinelabs config for store 4034
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (PinelabsServiceImpl.java:90) - Ajency.in :: pinelabs params {"SecurityToken":"661c9a5f-5d7a-4d76-a950-68beb8225cfd","TotalInvoiceAmount":37500,"TransactionNumber":"1386498-1581486596522","AllowedPaymentMode":"1","UserID":16067491,"Amount":37500,"SequenceNumber":1,"MerchantStorePosCode":"04190588","IMEI":"IM239018","MerchantID":2300}
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:56) (PinelabsServiceImpl.java:95) - Ajency.in :: making url call to  https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/UploadBilledTransaction
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (PinelabsServiceImpl.java:124) - Ajency.in :: pinelabs response {"responseCode":0,"responseMessage":"APPROVED","plutusTransactionReferenceID":55758}
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (PinelabsServiceImpl.java:132) - Ajency.in :: pinelabs api call for transaction 1386498-1581486596522 PlutusTransactionReferenceID:55758
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (PinelabsServiceImpl.java:134) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (ThirdPartyPaymentServiceImpl.java:83) - Ajency.in :: pinelabsdto status :OPEN
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (ThirdPartyPaymentServiceImpl.java:90) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (ThirdPartyPaymentServiceImpl.java:102) - Ajency.in :: saved customerOrderTransaction 90 transactionId :1386498-1581486596522
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (ThirdPartyPaymentServiceImpl.java:105) - Ajency.in :: initiate status :1
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (ThirdPartyPaymentServiceImpl.java:109) - Ajency.in :: initiate status :OPEN
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (POSAction.java:2882) - Ajency.in :: initiate status :OPEN
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (POSAction.java:2891) - Ajency.in :: pos action transaction status :OPEN
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (ThirdPartyPaymentServiceImpl.java:486) - Ajency.in :: has pending transactions true
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:19:58) (ThirdPartyPaymentServiceImpl.java:509) - Ajency.in :: hasActivePinelabsConfig true store 4034
[ INFO] [] [pool-24-thread-1] (12 Feb 2020 11:20:00) (UploadUsersScheduler.java:52) - Ajency.in :: Schedule Upload Users ::  Upload Users Campaign Cron Executed:1581486600001
[ INFO] [] [pool-24-thread-1] (12 Feb 2020 11:20:00) (UploadUsersScheduler.java:68) - Ajency.in :: Schedule Upload Users :: uploadUsersEnableCron : true uploadUsersThreshold : 2000 uploadUsersEmailAddress : analytics@brightlifecare.com,retail.tech@brightlifecare.com uploadUsersCronStartTime : 22:00:00 uploadUsersPerDayLimit : 800
[ INFO] [] [pool-24-thread-1] (12 Feb 2020 11:21:36) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (12 Feb 2020 11:21:36) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:23:21) (LoginAction.java:72) - Ajency.in :: trying to login for email: rohan@ajency.in
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 11:23:22) (UserServiceImpl.java:64) - Ajency.in :: user id: 16067491
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (DSRServiceImpl.java:1189) - Ajency.in :: POS :: pos dsr dateStringList: [2020-02-11, 2020-02-10, 2020-02-09, 2020-02-08, 2020-02-07] for wh: 4231
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (DSRServiceImpl.java:1201) - Ajency.in :: POS :: dsr missing dates: [2020-02-11, 2020-02-10, 2020-02-09, 2020-02-08, 2020-02-07] for wh: 4231
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (DSRServiceImpl.java:1235) - Ajency.in :: POS :: Order(s) present on 2020-02-11 but DSR missing for wh: 4231 dsr type: 1
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (DSRServiceImpl.java:120) - Ajency.in :: DSR :: warehouse: 4231 startDate: Sun Feb 09 00:00:00 IST 2020 endDate: Tue Feb 11 23:59:59 IST 2020 posSalesList: 2
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (POSReportServiceImpl.java:206) - Ajency.in :: TOTAL POS COUNT 2 TOTAL HK COUNT 0
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (POSReportServiceImpl.java:209) - Ajency.in :: TOTAL COUNT 2
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/order/payAtStoreCollection?z.ts==1581486820428&st=1&rsPrefix=NOI18&startDate=2020-02-09&endDate=2020-02-11  RC: 200
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (DSRServiceImpl.java:157) - Ajency.in :: DSR :: warehouse: 4231 startDate: Sun Feb 09 00:00:00 IST 2020 endDate: Tue Feb 11 23:59:59 IST 2020 hk returns size: 0
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (DSRServiceImpl.java:162) - Ajency.in :: DSR :: warehouse: 4231 startDate: Sun Feb 09 00:00:00 IST 2020 endDate: Tue Feb 11 23:59:59 IST 2020 hk sales size: 0
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (DSRServiceImpl.java:1075) - Ajency.in :: DSR :: prepaid = 0.0 cash collected = 0.0
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (DSRServiceImpl.java:1113) - Ajency.in :: DSR :: cash refunded = 0.0
[ INFO] [] [http-nio-8181-exec-5] (12 Feb 2020 11:23:40) (BankingDataServiceImpl.java:85) - Ajency.in :: DSR :: warehouse: 4231 startDate: Sun Feb 09 00:00:00 IST 2020 endDate: Tue Feb 11 23:59:59 IST 2020 pos cash: 1829.0 pas cash: 0.0 hk cash: 0.0 total cash collection: 1829.0

`

**Comment by shivam-kurtarkar** [comment]
ya it should be there is no problem 
you cannot initiate same transaction on same method cause other payment is in progress
