### ISSUE TITLE
transaction is not cancelled when the transaction is cancelled from postman,after the transaction is success.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1335]
Actual result
transaction is not cancelled when the transaction is cancelled from postman,after the transaction is success.

Steps
Go to the pos screen 
scan a barcode
Select the payment mode as payu
Click on initiate transaction 
Change the status to success
Click on get status 
Click on receive payment 
Cancel the transaction through postman using the url https://aqua61.healthkartqa.com/rest/api/ajax/payu/cancel/4034/1386500-1581488717121
check the status in the customer_order_transaction table

![image](https://user-images.githubusercontent.com/54023516/74309916-e8d39b00-4d91-11ea-97fc-2826eb8740a3.png)
![image](https://user-images.githubusercontent.com/54023516/74309934-f4bf5d00-4d91-11ea-8bb7-7a703a969171.png)

**Comment by shivam-kurtarkar** [comment]
after success status we do not make api call
hence
