### ISSUE TITLE
"Invalid state with given pincode null" message is displayed when the transaction is initiate without entering the phone number

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1345]
Actual result
"Invalid state with given pincode null" message is displayed when the transaction is initiate without entering the phone number

Steps 
Go to the pos screen
Do not enter the phone number
Select split payment mode
Select payu and credit/debit card
initiate transaction for credit/debit card

![image](https://user-images.githubusercontent.com/54023516/74405530-4aa80980-4e53-11ea-9ca6-46671d37360a.png)

**Comment by sharangsamonkar** [comment]
issue with js validation is not present for customer details.

**Comment by larissa-c-d** [comment]
Both the validations are displayed
![image](https://user-images.githubusercontent.com/54023516/74585013-64398480-4ffe-11ea-90e5-798ece886638.png)

![image](https://user-images.githubusercontent.com/54023516/74585004-4f5cf100-4ffe-11ea-9eac-0580d59123fe.png)
issue still exists

**Comment by larissa-c-d** [comment]
issue resolved
