### ISSUE TITLE
Final payable amount is not changed after the paytm voucher is applied.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1349]
Actual result
Final payable amount is not changed after the paytm voucher is applied.

Steps 
Go to the pos screen
Scan the barcode
select the payment mode as paytm voucher
Apply the voucher TEST111

![image](https://user-images.githubusercontent.com/54023516/74426707-d5046380-4e7b-11ea-8f62-0bcecd925ec6.png)
![image](https://user-images.githubusercontent.com/54023516/74426788-f9f8d680-4e7b-11ea-8fb9-bea2d5a2a72b.png)

**Comment by shivam-kurtarkar** [comment]
@sharangsamonkar

**Comment by sharangsamonkar** [comment]
Not an issue. Final payable amount remains the same.
