### ISSUE TITLE
initiate payment button is displayed,for payment mode UPI via edc machine for sis store

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1351]
Actual result
initiate payment button is displayed,for payment mode UPI via edc machine for sis store

Expected result 
Initiate payment button should not be displayed for sis store.

Steps
Go to the pos screen for an sis store
Select the payment  mode as split payment 
select the payment mode as  upi via edc machine

![image](https://user-images.githubusercontent.com/54023516/74501225-7092e400-4f0f-11ea-8882-5bc50c6b069a.png)

**Comment by shivam-kurtarkar** [comment]
only for card there is fallback
upi shows initiate button 
@sharangsamonkar
