### ISSUE TITLE
messages on the ui should disappear on click

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1360]
Actual result
Message disappears after timeout.

Expected result
messages on the UI should disappear on click

![image](https://user-images.githubusercontent.com/54023516/74625393-1c3b6e80-5172-11ea-905c-310a9038264f.png)

**Comment by Shraddhar23** [comment]
Increased the timeout to 15 secs.

**Comment by larissa-c-d** [comment]
Timeout is increased
