### ISSUE TITLE
UI displayed as "no data available in table"while trying to fetch data 

### ISSUE THREAD

**Issue by ambksud** [ajency/HK-Issue-Tracker#137]
Steps to Reproduce:
1.Navigate to Minimum Inventory Config 
2.Navigate to Zone panel
3.Select all the values from ZoneWiseStore,Brand Name and Product Variant ID
4.Click on Apply Filter
Actual Result 
User gets the screen displayed as "no data available in the table" instead of Loading
![ui-healthcart](https://user-images.githubusercontent.com/44572706/48332728-e6f4c680-e67a-11e8-96e1-549dde25a1bd.PNG)
Frequency:60%

**Comment by rohan-morje** [comment]
Issue verified and resolved
