### ISSUE TITLE
entry is made in the table when the file format is incorrect.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1370]
Actual result
entry is made in the table when the file format is incorrect.

Expected result
no entry should be made in the table when the file format is incorrect.

Steps
Go to the paytm voucher upload UI
Click on upload button

![image](https://user-images.githubusercontent.com/54023516/74632991-a5f53700-5186-11ea-82c9-ffc23b68c0c3.png)

**Comment by Shraddhar23** [comment]
No an issue.
There was a simultaneous upload.
