### ISSUE TITLE
Downloading voucher codes. You will receive an email shortly message is displayed every time the page is refreshed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1374]
Actual result
Downloading voucher codes. You will receive an email shortly message is displayed every time the page is refreshed.

Steps
Upload an excel sheet successfully.
Click on download voucher codes.
Click on the refresh icon on the browser.

![image](https://user-images.githubusercontent.com/54023516/74641934-21131900-5198-11ea-9df5-889ee587e282.png)

**Comment by Shraddhar23** [comment]
The form gets submitted because of which the error message is displayed.
It is a HTML issue.

**Comment by larissa-c-d** [comment]
Voucher email is also received.

**Comment by larissa-c-d** [comment]
issue resolved
