### ISSUE TITLE
voucher Uploads made with the existing UI are displayed on the new feature UI

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1375]
Actual result
voucher Uploads made with the existing UI are displayed on the new feature UI

new feature
![image](https://user-images.githubusercontent.com/54023516/74645077-4bb3a080-519d-11ea-8582-bc1647683bff.png)
existing feature
![image](https://user-images.githubusercontent.com/54023516/74645146-6128ca80-519d-11ea-86e3-e66c728df061.png)

**Comment by Shraddhar23** [comment]
Uploads from other Page will not be shown here.

**Comment by larissa-c-d** [comment]
issue resolved
