### ISSUE TITLE
Minimum inventory is not set as NA for all the product variant for a new store with new zone, 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#138]
By default when a new store is created or a new zone with new stores created: default value for min_inventory for a product variant belonging to the said zone or store needs to be set as NA (which means no entry in the DB for global or entry in global with min_inventory set as null and flag of not_applicable to true)

New zone created: test zone 
New store: Test retail df store

Actual result: Minimum inventory is not set as NA for all the product variant for a new store with new zone, 
ref screenshot

![image](https://user-images.githubusercontent.com/14803102/48348807-61880b00-e6a8-11e8-92a4-048d80b9fbb6.png)

**Comment by nutank** [comment]
@rohan-morje - Not an issue since global value is set for it, NA will fallback to global value. If global value itself is NA it would be NA for the said variant.
