### ISSUE TITLE
remove button is not aligned

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1386]
Actual result
remove button is not aligned

Steps
Go to the hk.com checkout page
Select credit/debit card for split payment 
Select initiate the transaction for one of the card payment 

![image](https://user-images.githubusercontent.com/54023516/74827802-04134d00-5334-11ea-8a9f-8ef40f03dcd3.png)

**Comment by Shraddhar23** [comment]
Remove button alignment is handled in the payu branch.
For this branch , we will align the Payment mode , Amount , Initiate payment fields.

**Comment by Shraddhar23** [comment]
![Screenshot 2020-02-20 at 6 41 01 PM](https://user-images.githubusercontent.com/48199171/74936676-9a1ca580-5410-11ea-913f-e6572ff1c3af.png)

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/75019732-6fd1f300-54b7-11ea-92f6-1832f894646d.png)
