### ISSUE TITLE
Initiate button is not aligned horizontally.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1388]
actual result
Initiate button is not aligned horizontally.

Expected result
Initiate button should be horizontally aligned.

Steps
Go to the pos screen
Select the payment mode as split payment 
select the payment mode as credit/debit card.

![image](https://user-images.githubusercontent.com/54023516/75007776-2627df00-549c-11ea-9667-65c670580956.png)

**Comment by Shraddhar23** [comment]
UI changes will be handled in payu branch.

**Comment by larissa-c-d** [comment]
issue resolved
