### ISSUE TITLE
NPL Market place value is not set to false when the "Enable N P L Marketplace" flag on the catalog is false.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1398]
Actual result
NPL Market place value is not set to false when the "Enable N P L Marketplace" flag on the catalog is false.

Expected result
NPL Market place value should be set to false when the "Enable N P L Marketplace" flag on the catalog is false.

Steps
Go to edit a retail store page on catalog
Disable the Enable NPL market place flag
Check the store table on aqua for the column npl market place.

![image](https://user-images.githubusercontent.com/54023516/75875933-b1a95480-5e3a-11ea-88e7-f747fbd64836.png)
![image](https://user-images.githubusercontent.com/54023516/75875996-dac9e500-5e3a-11ea-83c1-061d2046b7c8.png)

**Comment by rohan-morje** [comment]
will check after catalog is started
