### ISSUE TITLE
3PL orders tab is displayed when the NPL Marketplace flag is false on aqua and the user has permission THREEPL_ORDER_LISTING

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1399]
Actual result
3PL orders tab is displayed when the NPL Marketplace flag is false on aqua and the user has permission THREEPL_ORDER_LISTING

Expected result
The 3PL order tab should be displayed only when the NPL Marketplace flag is true on aqua and the user has permission THREEPL_ORDER_LISTING permission.

Steps
Assign the permission THREEPL_ORDER_LISTING to the user
Disable the  N P L Marketplace on catalog
Check if the 3PL Order tab is present on aqua.
![image](https://user-images.githubusercontent.com/54023516/75877790-76a92000-5e3e-11ea-9d79-716e8e7577db.png)
![image](https://user-images.githubusercontent.com/54023516/75877819-86c0ff80-5e3e-11ea-811f-a423752efbb7.png)

**Comment by shivam-kurtarkar** [comment]
the role assigning is one way. you can add but cannot remove
