### ISSUE TITLE
Barcode displaying on POS by clicking on POS order Punch are  highlighted in Red indicating barocde before them 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1401]
Go to 3PL Listing page for Del shalimar bagh store

Click on POS Order Punch link for 19 1799896 and observe thePOS screen

![image](https://user-images.githubusercontent.com/14803102/76206217-9b780b80-6221-11ea-9e2f-0cdbd063b521.png)

**Comment by shivam-kurtarkar** [comment]
there are items with expiry before this items expiry date.
In production this will not occur since order will be placed here only if they dont have stock.
