### ISSUE TITLE
Online Credit/debit card not displaying after it is selected in Split Payment

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1406]
OPen the POS
Select payment mode as Split Payment
Select payment moode as Online Credit/debit card and observe

Actual result: Online Credit/debit card not displaying after it is selected in Split Payment
![image](https://user-images.githubusercontent.com/14803102/76408892-aebae080-63b3-11ea-958d-206d3c77319b.png)

**Comment by Shraddhar23** [comment]
![Screenshot 2020-03-11 at 4 27 39 PM](https://user-images.githubusercontent.com/48199171/76410019-41a84a80-63b5-11ea-953f-db1d78ed3107.png)

**Comment by Shraddhar23** [comment]
![Screenshot 2020-03-11 at 4 55 02 PM](https://user-images.githubusercontent.com/48199171/76412124-1293d800-63b9-11ea-9ce7-0338707bf80b.png)
