### ISSUE TITLE
Customer Order Transaction not found message displayinh when getting Payment status  for Split Order of Online Card

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1408]
OPen the POS
select split payment of Online card and Online card
Initiate payment

Actual result: Customer Order Transaction not found message displayinh when getting Payment status  for Split Order of Online Card

![image](https://user-images.githubusercontent.com/14803102/76419504-78d32780-63c6-11ea-8e77-d9bf8a627a7a.png)

**Comment by Shraddhar23** [comment]
![Screenshot 2020-03-12 at 10 56 41 AM](https://user-images.githubusercontent.com/48199171/76490105-30f8e280-6450-11ea-98b8-a2ec63f5e49e.png)
