### ISSUE TITLE
Cannot scan barcode for checkout when ST is created for SIS  via API

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#141]
Create a ST for SIS via API
{
  "inventoryPlannerId": 144,	
  "stBoDtos": [
    {
      "fromWarehouse": "HKWH4-AB",
      "toWarehouse": "AWM-AB",
      "stBoVariantsDtos": [
        {
          "productVariantId": "NUT131-13",
          "quantity": "1",
          "productVendorId": "2"
        }    ]
        }
        ]
        }

SIS Gold Gym, Andheri (West) is Bright and Aqua enabled
Scan the barcode (of NPL product ) to checkout and observe

Following error message is displayed: Products of Vendor Bright Lifecare Pvt Ltd can only be added on this Stock Transfer!!

![image](https://user-images.githubusercontent.com/14803102/48757260-2007e900-ecc2-11e8-9f3a-fe950539e5ee.png)

**Comment by pitre55** [comment]
not an issue. vendor passed in st api request is 2(Bright) hence cannot accept product from any other vendor.
_note: currently, auto st for sis is not supported._
