### ISSUE TITLE
When an barcode is scanned to  Checkout- "Changes saved" message displayed instead of " Item scanned"

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#142]
Go to Postman Create stock transfer through API
Go to Checkout barocde page and scan the barcode and Observe

Actual result: When an barcode is scanned to  Checkout-Changes saved message displayed Item scanned

![image](https://user-images.githubusercontent.com/14803102/48764550-f658bd00-ecd5-11e8-80a3-a89bfcc9549e.png)

**Comment by pitre55** [comment]
Not an issue, existing functionality. Once a stock transfer is created/saved, **"Changes saved"** message is shown for any barcode scanned after saving st.
For manual initially no st is created, hence item saved message is shown.
