### ISSUE TITLE
Filter by Date Range and 3 PL Order Status do not give correct result

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1422]
Filter by 3PL Date Range OR Filter by 3PL Order Status and Observe

Actual result: Filter by Date Range and 3 PL Order Status do not give correct result

![image](https://user-images.githubusercontent.com/14803102/76857837-4620a780-687c-11ea-8ac4-5b2d88300f81.png)

**Comment by rohan-morje** [comment]
Issue not resolved

**Comment by rohan-morje** [comment]
Filter by 3PL Order status working.

Filter by Date Range not working
![image](https://user-images.githubusercontent.com/14803102/76959158-11295900-693f-11ea-8701-525d696077da.png)

**Comment by rohan-morje** [comment]
Filter by Date Range , data displaying in Excel

![image](https://user-images.githubusercontent.com/14803102/76959273-49c93280-693f-11ea-93b0-0a0c482e8620.png)

**Comment by sharangsamonkar** [comment]
Issues here:
1. extra records in excel
2. count is not coming correct
3. page number is wrong

Fix: Filtering and skipping in java not jsp.
