### ISSUE TITLE
Debit note is not generated when product is returned and also status is not changed

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1424]
shippingOrderGatewayId=5098760-S02605
One 3PL product was returned succcessfully

Actual result: Debit note is not generated when product is returned and also status is not changed

![image](https://user-images.githubusercontent.com/14803102/76930761-3d2be680-690d-11ea-8b81-f23e72734825.png)

**Comment by shivam-kurtarkar** [comment]
this was because  of only chekced in skuitems were being fetched
