### ISSUE TITLE
All products (3PL product) detail not displaying on 3PL Lisinting and SO page  after the order has been placed successfully

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1425]
POS has one 3PL order
Scan normal barcode and place the order and Observe

Actual result: 3PL product detail not displaying after the order has been placed successfully.
Also prooducts checked out are not displaying on SO page.
2 products were checked out but only one is displaying

Expected: 3PL product detail and normal prioduct detail should display  after the order has been placed successfully

![image](https://user-images.githubusercontent.com/14803102/76950387-f0a5d280-692f-11ea-9ea7-38d7d6a01fbf.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/76950539-2c409c80-6930-11ea-9d60-c67e13dcb01e.png)

**Comment by shivam-kurtarkar** [comment]
please check for new order only old wont show since there is no mapping
