### ISSUE TITLE
Time shown in 3PL Order Date field is not correct

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1426]
3PL  order is created at  4.30pm but time shown is 21:57:31

![image](https://user-images.githubusercontent.com/14803102/76954786-f4892300-6936-11ea-81c2-acfe69f134de.png)

**Comment by sharangsamonkar** [comment]
passing as a string

**Comment by rohan-morje** [comment]
Time shown is not correct. 
HK-17223-23069436 3PL Order is place at 9.40 on 19 march but in listing time shown is  15:00:40

![image](https://user-images.githubusercontent.com/14803102/77031784-9e64c000-69c8-11ea-88ec-e5186c70b4c7.png)
