### ISSUE TITLE
Only 3 records are shown on listing screen and 7 records are shown on Excel file when Filter by Phone number: 9552519582 and 3PL Order Status as RPU

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1427]
Filter by Phone number: 9552519582 and 3PL Order Status as RPU and Observe

Actual result: Showing 1- 7 of 7 results message is displayed but only 3 records are displaying in the result 

![image](https://user-images.githubusercontent.com/14803102/76957749-61eb8280-693c-11ea-8b6f-7267c4317420.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/76958598-0fab6100-693e-11ea-819b-8555b2d8289d.png)

**Comment by rohan-morje** [comment]
select filter : phone nu: **9552519582**  and 3PL order status as **RPU**

Message shown in not correct
**Showing 1 - 9 of 9 results**

corect message:  Showing 1 - 3  of 3 results
![image](https://user-images.githubusercontent.com/14803102/77056398-5c537280-69f8-11ea-9e79-d277fe85798f.png)

**Comment by shivam-kurtarkar** [comment]
max range 200
