### ISSUE TITLE
Multiple digits after decimal point in Final Payable Amount on 3PL Listing

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1431]
Observe the Final Payable Amount on 3PL Listing

Actual: Multiple digits after decimal point in Final Payable Amount on 3PL Listing

Expected: only 2 decimal after decimal 
![image](https://user-images.githubusercontent.com/14803102/77049058-6b80f300-69ed-11ea-96ce-44982965304f.png)

**Comment by shivam-kurtarkar** [comment]
amount is rounded as stated in requirement
