### ISSUE TITLE
There is insufficient quantity for HNUT10305-01. when PL product is entred

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1453]
Open the ST
Entert the PL product and Qty

Actualresult: There is insufficient quantity for HNUT10305-01. when PL product is entred

Expected:PLease select NPL products message shoulddisplay

![image](https://user-images.githubusercontent.com/14803102/78557277-1b4bc280-782e-11ea-9c1a-de634851ac26.png)

**Comment by shivam-kurtarkar** [comment]
added message "Could not find product variant HNUT_102331401 belonging to aqua."

**Comment by rohan-morje** [comment]
There is insufficient quantity for NUT1367-32. mesage displayed is incorrect when Vendor selected is Aquamarine and variant entered in Bright


![image](https://user-images.githubusercontent.com/14803102/78662124-80b2b880-78ed-11ea-99df-5b426a091d4e.png)

**Comment by shivam-kurtarkar** [comment]
There is no item in db hence

**Comment by rohan-morje** [comment]
As discussed with Sharang above message will be displayed when Aqua vendor is selected and PL product is added
