### ISSUE TITLE
Variant details are notdisplaying in the generated invocie

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1458]
Create ST
Ship the close
checkin the barocde ofST and closethe ST

Observe the invoice

Actual result:Variant details are notdisplaying in the generated invocie

![image](https://user-images.githubusercontent.com/14803102/78561221-f7d84600-7834-11ea-8bc3-51521c090574.png)

**Comment by shivam-kurtarkar** [comment]
doesnt have stli against it
