### ISSUE TITLE
There are 3 barcode with status as damage for variant NUT2044-03, but when variant and qty 2 is added - There is insufficient quantity for NUT2044-03.

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1461]
There are 3 barcode with status as damage for variant NUT2044-03
Create new ST
Enter the variant NUT2044-03 and barcode qty as 2 and observe 

**There is insufficient quantity for NUT2044-03. message is displayed**

Actual result - There are 3 barcode with status as damage for variant NUT2044-03, but when variant and qty 2 is added - There is insufficient quantity for NUT2044-03.

![image](https://user-images.githubusercontent.com/14803102/78631662-96f35100-78ba-11ea-9fd1-3e7581d62148.png)

**Comment by sharangsamonkar** [comment]
Check what all barcodes are used to check inventory on bright.

**Comment by rohan-morje** [comment]
currently could not checkout barocde on Bright due to ims setup, so reopening it
