### ISSUE TITLE
Expected Qty count displaying on UI is not correct when 2 barcodes of different batches are scanned 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1462]
106634  
Wh Aqua 5.0
OPen the ST
NUT2155-01  and  qty 2
Scan the 2 barcodes of different batches and observe the lisitng

Expected Qty count displaying on UI is not correct when 2 barcodes of different batches are scanned 

![image](https://user-images.githubusercontent.com/14803102/78634293-43d0cc80-78c1-11ea-8cef-87e3dd58afd9.png)

**Comment by rohan-morje** [comment]
Expected Qty is still not showing correct. 
Addded 2 qty and scanned 2 barocdes of different batch, But expected qty is showing as 2 -2 for both records
![image](https://user-images.githubusercontent.com/14803102/78664174-1b60c680-78f1-11ea-8a25-6700f6e7dd89.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/78664579-f1f46a80-78f1-11ea-9271-e42655f4fdf5.png)

**Comment by shivam-kurtarkar** [comment]
not an issue

**Comment by rohan-morje** [comment]
why?

**Comment by shivam-kurtarkar** [comment]
expected qty is same for all stli of same pv
and checkedout qty is sum of all of them
bright functionality

**Comment by shivam-kurtarkar** [comment]
@sharangsamonkar

**Comment by rohan-morje** [comment]
it is an isssue

**Comment by rohan-morje** [comment]
As discussed with Sharang and Shivam.
Sharang discussed with Snigdha regarding the flow
