### ISSUE TITLE
In ST listing , ST checkout time is shown as 12 AM

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1465]
Go to  ST Listing and Observe Checkout Date column 

Actual result: In ST listing , ST checkout time is shown as 12 AM

![image](https://user-images.githubusercontent.com/14803102/78637194-872e3980-78c7-11ea-95c2-97ddfb2c863b.png)

**Comment by shivam-kurtarkar** [comment]
in db time is 00:00. after fetching data till action its same. but changes in jsp
Time zone issue
@sharangsamonkar

**Comment by rohan-morje** [comment]
On production, actual ST time is displaying
Eg: 
![image](https://user-images.githubusercontent.com/14803102/78775751-60016600-79b4-11ea-8939-64df0fca0e8b.png)

**Comment by rohan-morje** [comment]
As discussed with Sharang, closing the issue
