### ISSUE TITLE
Do not allow to Add more products when one product is added and its barcode is scanned

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1467]
Create New ST
Select Vendor
Enter Variant and Qty , click on Add
Scan barocde
Now try to add another vendor

Actual result: Do not allow to Add more products when one product is added and its barcode is scanned

Expected:  Should allow to add another product when one product is entered and its barocde is scaned
![image](https://user-images.githubusercontent.com/14803102/78663672-3121bc00-78f0-11ea-82af-b9d2451163e1.png)

**Comment by shivam-kurtarkar** [comment]
disabled js removed

**Comment by rohan-morje** [comment]
Product variant and Qty field are enabled when status of the ST is shipped

![image](https://user-images.githubusercontent.com/14803102/78772293-2b3ee000-79af-11ea-81c0-b285b83cf9a3.png)

**Comment by shivam-kurtarkar** [comment]
now hiding it like scan barcode
