### ISSUE TITLE
New line item is created when adding the product variant which is already added to ST

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1468]
Open the ST
Add variant NUT304-38 and Qty as 1 and scan the barcod - > Line item is created
Now again select same variant and make Qty as 1 and Observe

Actual: New line item is created when adding the product variant which is already added to ST

Expectd: Same line item should be updated instead of creating one more line item

![image](https://user-images.githubusercontent.com/14803102/78671381-d9d61880-78fc-11ea-9185-b0cc1990c8d5.png)

**Comment by shivam-kurtarkar** [comment]
could not replicate
