### ISSUE TITLE
igst showing as 0 in stock_transfer_line_item table

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1469]
stock_transfer_id =106650

![image](https://user-images.githubusercontent.com/14803102/78674716-a8138080-7901-11ea-871a-271de5c3df11.png)

**Comment by rohan-morje** [comment]
plz confirm with sharang

**Comment by shivam-kurtarkar** [comment]
to from ware house same hence igst =0

**Comment by rohan-morje** [comment]
igst is displaying as 0 for to warehuse and from warehouse of different state
ST id: 106658

**Comment by shivam-kurtarkar** [comment]
st:106662 
works for store of different states

**Comment by rohan-morje** [comment]
![Uploading image.png…]()

**Comment by shivam-kurtarkar** [comment]
stocktransferAction.java line 699
if store diffrent tries to fetch from bright
but bright is down hence
