### ISSUE TITLE
Receving STN shipped mail when STN is in Packed status

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1476]
STN 106666	

Actual resuly: Receving STN shipped mail when STN is in Packed state

![image](https://user-images.githubusercontent.com/14803102/78781001-1ff2b100-79bd-11ea-940b-e1c86bbbca13.png)

**Comment by shivam-kurtarkar** [comment]
after shipping status chages to packed 
not an issue
