### ISSUE TITLE
Status of the ST is changed to Packed when Mark Stock Transfer Completed button is clicked

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1477]

**Comment by sharangsamonkar** [comment]
Check on 61

**Comment by shivam-kurtarkar** [comment]
if((EnumWarehouseType.getAllStPullbackTypeIds().contains(stockTransfer.getToWarehouse().getWarehouseType())) || (stockTransfer.getFromWarehouse().getWarehouseType().equals(EnumWarehouseType.Online_B2B.getId()))){
                    stockTransfer.setStockTransferStatus(EnumStockTransferStatus.Packed.getStockTransferStatus());




not an issue

**Comment by rohan-morje** [comment]
Discussed with sharang and closing the issue
