### ISSUE TITLE
Stock Transfer Life cycle details are incorrect - 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1478]
Open the Stock Transfer Life cycle stock_transfer_id = 106669

Stock_transfer_status_id=32 is shown which is Stock Transfer Approved

![image](https://user-images.githubusercontent.com/14803102/78787738-6e597d00-79c8-11ea-977d-627dccccfdd0.png)

**Comment by sharangsamonkar** [comment]
Check on 61 if its an issue

**Comment by rohan-morje** [comment]
Verified on master for Aqua wh 5,0
