### ISSUE TITLE
NPL: DF is happening on daily basis(fall back to old DF) and ST craeated for New store when Current Inventory is greater than Min Invenotry X

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#148]
Minimum Weight check disabled
DF enabled for product NUT304-27
DF enabled for store  4049 
Min Inventory Qty : 10  Current Inventory : 16
Daily sales qty: 3

Actual result: for NPL,  DF is happening on daily basis(fall back to old DF) and ST created for New store when Current Inventory is greater than Min Invenotry X
ST is created for 3 quantity

**Comment by sharangsamonkar** [comment]
@rohan-morje 
Was an existing issue. Please test for both PL and NPL.

Expected result: DF should not be created.
