### ISSUE TITLE
Barcode not uploaded due to excel header issue but changes saved message is dispalyed

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1486]
Open the ST
Add product and qty
Upload the file and observe

Actual: Barcode not uploaded due to excel header issue but changes saved message is dispalyed

Expected:   Upload failed - Exception @ Row:1 Invalid Column in excel.  

![image](https://user-images.githubusercontent.com/14803102/78985091-89053080-7b45-11ea-9991-6f79c78ca8e1.png)

**Comment by shivam-kurtarkar** [comment]
if no barcodes found thorws error failed to read file

**Comment by rohan-morje** [comment]
Failed to read barcodes from the file. message is displayed

![image](https://user-images.githubusercontent.com/14803102/79037461-e608f100-7bee-11ea-96c5-5c6a07e96c3a.png)
