### ISSUE TITLE
ST is getting  created with expected qty as NULL for NPL for New Store  when Source Inventory is 0

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#149]
New Store: X> C
NPL: NUT1628-02
Store: DEL green park (New Store)  
Source inventory : 0 
source_warehouse_id = 4334  
retail_warehouse_id = 4049

ST is getting  created with expected qty as NULL for NPL for New Store  when Source Inventory is 0 and carry forward of (X-C) quantity is not happening.

![image](https://user-images.githubusercontent.com/14803102/48943784-548dd600-ef4a-11e8-93ed-3c55318727af.png)

![image](https://user-images.githubusercontent.com/14803102/48943801-68393c80-ef4a-11e8-8280-e7da077403ab.png)

![image](https://user-images.githubusercontent.com/14803102/48943863-94ed5400-ef4a-11e8-8d88-1a1fa77b8469.png)

**Comment by sharangsamonkar** [comment]
Could not replicate.
