### ISSUE TITLE
Barcode getting upload through excel without Adding Product variant and Qty

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1492]
Select Vendor Aqua
Do not Add  Product variant and Qty
Scan barcode and Upload the file

Actual result : Barcode getting upload through excel without Adding Product variant and Qty

![image](https://user-images.githubusercontent.com/14803102/78993056-7a754400-7b5a-11ea-8d90-4c12a4192805.png)

**Comment by shivam-kurtarkar** [comment]
js disable button

**Comment by sharangsamonkar** [comment]
@rohan-morje Check if  once you encounter a wrong barcode, does the scanning stop.

**Comment by sharangsamonkar** [comment]
checke if all remainiin gbarcodes are checkedin if one is wrong
@rohan-morje

**Comment by rohan-morje** [comment]
barcode uploading when variant and qty not added
![image](https://user-images.githubusercontent.com/14803102/79037107-e9e74400-7beb-11ea-963d-1aaa6b69234a.png)

**Comment by rohan-morje** [comment]
@sharangsamonkar None of the barcode is getting uploaded when atleast 1 is incorrect
Following message is displayed - 
Either Invalid barcode, or insufficient Stock in warehouse.
![image](https://user-images.githubusercontent.com/14803102/79037329-8eb65100-7bed-11ea-90cd-938a8fa533b1.png)

**Comment by rohan-morje** [comment]
Barcodes are not uploading but validation mesage is not dispalyed

![image](https://user-images.githubusercontent.com/14803102/79071747-fc03d800-7cfa-11ea-9414-77743f106cc7.png)

**Comment by shivam-kurtarkar** [comment]
added css to show disable 
cannt checkout barcodes
