### ISSUE TITLE
Variant for which barcodes are not scanned are displaying at To Warehouse

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1500]
ST: 106770 
Add 4 different varaint - For 2 varaints checkout the barcodes ann for other 2 variants do not checkout any bacrcode
Ship the STN
Observe the ST at To Warehouse 
Actual result: Variant for which barcodes are not shipped are displaying at To Warehouse

Expected:Variant for which barcodes are not shipped should not display  at To Warehouse

![image](https://user-images.githubusercontent.com/14803102/79469884-5c0dbd80-801e-11ea-8026-4dc6fae0a121.png)

![image](https://user-images.githubusercontent.com/14803102/79469760-37b1e100-801e-11ea-9edc-7b985ebcb82d.png)

**Comment by shivam-kurtarkar** [comment]
not an issue

**Comment by rohan-morje** [comment]
As discussed with sharang,not an issue
