### ISSUE TITLE
Null pointer exception when uploading file

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1514]
WH : Aqua 5.0

![image](https://user-images.githubusercontent.com/14803102/80063548-c3ae9600-8553-11ea-8dcc-1e8f78d07724.png)

![image](https://user-images.githubusercontent.com/14803102/80063663-ffe1f680-8553-11ea-8c3a-ab19f37443cd.png)

**Comment by Shraddhar23** [comment]
Please check if you get this issue now.
