### ISSUE TITLE
Exception while uploading the barcode

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1523]
Create new ST
Upload variant via excel - NUT313-09
Upload barcode via excel and observe

Actual result: Exception while uploading the barcode

![image](https://user-images.githubusercontent.com/14803102/80089101-12235b00-857b-11ea-9f23-34457b2b48dc.png)

**Comment by Shraddhar23** [comment]
I uploaded the barcode excel for ST : 106956
