### ISSUE TITLE
Exception while uploading variant and qty

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1524]
I have got this exception many times

![image](https://user-images.githubusercontent.com/14803102/80093759-b3fa7600-8582-11ea-8a85-e48104e148ec.png)

**Comment by Shraddhar23** [comment]
Please check if you get this issue now.

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/80353199-a3a00f00-8892-11ea-85d3-aa5696b6c44d.png)

**Comment by sharangsamonkar** [comment]
File upload timeout issue.
