### ISSUE TITLE
Error marking stock transfer as shipped! message displayed whenshippingthe  ST onAqua

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1536]
Createthe ST
Addvariantand qty
Scan barcode and ship the ST

Actula result: Error marking stock transfer as shipped! message displayed whenshippingthe  ST onAqua

![image](https://user-images.githubusercontent.com/14803102/80300688-7b45e100-87bc-11ea-8e9f-37b8e237eace.png)

**Comment by Shraddhar23** [comment]
![Screenshot 2020-04-26 at 5 44 27 PM](https://user-images.githubusercontent.com/48199171/80307272-9aa53400-87e5-11ea-9928-8d670d89be67.png)
