### ISSUE TITLE
Not able to upload the barcodes through xl file

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1546]
Create new ST.
Edit Stock Transfer # 107066
Upload the  varraint
Now upload the barcodes Eg: NUT326-04

![image](https://user-images.githubusercontent.com/14803102/80449929-fa165780-893d-11ea-9d7d-e1296c129102.png)

![image](https://user-images.githubusercontent.com/14803102/80449988-1adead00-893e-11ea-8677-f3d1a2964806.png)

**Comment by Shraddhar23** [comment]
The message is displayed if the sku_item  fetched by the query is null.

select * from sku_item si join sku_group sg on si.sku_group_id = sg.id join sku s on sg.sku_id = s.id join warehouse w on s.warehouse_id = w.id where 
si.barcode = "IV-3072547-55" and w.id=4357 and si.`sku_item_status_id` in (10,160,150,40,50);

**Comment by Shraddhar23** [comment]
![Screenshot 2020-04-28 at 11 34 35 AM](https://user-images.githubusercontent.com/48199171/80452629-4a90b380-8944-11ea-9666-3893dace7e38.png)
