### ISSUE TITLE
Exception while returning the product

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1548]
![image](https://user-images.githubusercontent.com/14803102/80567128-23a0b300-8a12-11ea-8ac0-caf8b630d952.png)

![image](https://user-images.githubusercontent.com/14803102/80567209-5480e800-8a12-11ea-8f86-141397ecb80c.png)

![image](https://user-images.githubusercontent.com/14803102/80567235-606caa00-8a12-11ea-928f-6e7cae35327b.png)

**Comment by Shraddhar23** [comment]
![Screenshot 2020-04-29 at 12 33 35 PM](https://user-images.githubusercontent.com/48199171/80569061-bdb62a80-8a15-11ea-8371-6b1ac4cb2c31.png)
