### ISSUE TITLE
Email is triggered when there are no records t delete in daily sales

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1549]
Precondition: There are no data in daily sales

http://192.168.70.145:5050/rest/api/inventory/backupDailySales

Actual: Email trigger is trigered

![image](https://user-images.githubusercontent.com/14803102/80596867-acd0dd80-8a44-11ea-9006-c36306ba975c.png)

![image](https://user-images.githubusercontent.com/14803102/80596577-3a5ffd80-8a44-11ea-9f93-a81405fd3c80.png)

**Comment by sharangsamonkar** [comment]
We will send the mail. But instead of FAILED we can display NO DATA.

**Comment by Shraddhar23** [comment]
Changes are done.
