### ISSUE TITLE
B2G2 offer displaying  when there are only 2 barcodes present at the store

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1569]
OPen the POS, Store Delhi Greenpark
Scan 2 barcodes and observe

Actual result; B2G2 offer displaying  when there are only 2 barcodes present at the store

![image](https://user-images.githubusercontent.com/14803102/81280351-f6897b80-9075-11ea-9815-e723ac71a6db.png)

**Comment by sharangsamonkar** [comment]
can be picked up last.
