### ISSUE TITLE
Invoice details ie Item details displayed is not proper when BxGY is applied

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1575]
Open POS
Scan 2 barcode of NUT1367-39
Apply B1G1 offer
Click on Recieve Payment and  Observethe  inovice

Actualresult: Invoice details ie Item details displayed is not proper when BxGY is applied

![image](https://user-images.githubusercontent.com/14803102/81397029-269f5000-9144-11ea-9a0f-e5c6863ed25b.png)

![image](https://user-images.githubusercontent.com/14803102/81397057-34ed6c00-9144-11ea-9f5c-63d0f5b25e01.png)

**Comment by shivam-kurtarkar** [comment]
'-' is just part of text.
while creating invoice dto it groups by sku hence takes only 1 entry of cart line item
thus not printing info about the second item

also need to check hk price that is being printed
