### ISSUE TITLE
Order could not be placed! Amount mismatch issue has occured. Please try again!! message displayed when 3 barcodes of same product  and all have Fefo -Message should be changed

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1576]
SCan 3 barcode of NUT1367-39
Apply BxGy offer
CLick onreceive payment button andobserve

Actualresut: Order could not be placed! Amount mismatch issue has occured. Please try again!! message display

**Order cannot be created as different variants of the same product should have same discount ,** message isdisplayed when there is mismatch in Fefo

Message should be same when there is mismatch in offer price

![image](https://user-images.githubusercontent.com/14803102/81397567-4125f900-9145-11ea-9dc2-38a2152de590.png)

![image](https://user-images.githubusercontent.com/14803102/81397532-29e70b80-9145-11ea-8096-6a68f27b8361.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/81398778-8519fd80-9147-11ea-8604-a536203df2e2.png)

**Comment by shivam-kurtarkar** [comment]
Not an issue
there cant be 2 items of same variant with different amount

**Comment by rohan-morje** [comment]
This istheissue Shivam

**Comment by sharangsamonkar** [comment]
@shivam-kurtarkar 
The message is incorrect. See the second image that is the right message. Looks like in the case of bxgy it is not hitting this part of the code.

Dont change the message, check why the second image validation code is not getting hit

**Comment by shivam-kurtarkar** [comment]
validation message is thrown
![image](https://user-images.githubusercontent.com/52652317/81534993-9dc42680-9386-11ea-8ad3-8ffdff6ca8ec.png)
