### ISSUE TITLE
The line item is in wrong state , it has no barcode to delete message displayed on click on Download barcode link  when returning product on  RTU/RPO checkin page 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1592]
Open POS - GGN good earth mall
Scan IVM-467-166317  and IVM-467-166280
Apply BxGy offer
Place the Order
Go to Create Booking    Gateway Order ID: 1527877-ST00167
Return the second rrecord
Now return the order Reverse Order Created : Reverse Order Created : 39994-RP5254160
Go to 
Click on Download barcode

Actual resut: The line item is in wrong state , it has no barcode to delete message displayed on click on Download barcode link  when returning product on  RTU/RPO checkin page 

![image](https://user-images.githubusercontent.com/14803102/81549838-ff8f8b00-939c-11ea-867f-b777ee575885.png)

![image](https://user-images.githubusercontent.com/14803102/81549636-af182d80-939c-11ea-965b-7c949ce8bbf8.png)

**Comment by sharangsamonkar** [comment]
This normally comes when the barcode is not in checked out status.

**Comment by shivam-kurtarkar** [comment]
SELECT * from sku_item si WHERE si.barcode in ('IVM-467-166317', 'IVM-467-166280');

SELECT * from aqua_prod.product_variant_inventory pvi
where pvi.line_item_id=7017099

error occurred cause there is no pvi entry . 

IVM-467-166317 and IVM-467-166280
![image](https://user-images.githubusercontent.com/52652317/81716051-8d02d600-9496-11ea-8658-4be41dab2ce7.png)
