### ISSUE TITLE
Exception on click of Close & Mark RP as checked In button while returning product

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1593]
GGN Good earth mall

Scan 2 barcode of NUT1367-39     - Gateway Order- 1527878-ST48075
Apply BxGy offer
Place the  order
Now return 1 barcode
Now in RPU/RTO checkin page, add the barcode along with details and click on  Close & Mark RP as checked In button and observe

Actual result: Exception on click of Close & Mark RP as checked In button while returning product

![image](https://user-images.githubusercontent.com/14803102/81551329-47171680-939f-11ea-8df8-698078312350.png)

**Comment by shivam-kurtarkar** [comment]
3pl bug
