### ISSUE TITLE
Please scan 2 barcode(s) of NUT1367-41 and then apply the offer   pop up displayed when 2 barcodes are already scanned and B1G2 offer is applied

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1599]
Scan 2 barcode of NUT1367-41 BLR HRBR store
Apply B1G2 offer and Observe

Actual result": Please scan 2 barcode(s) of NUT1367-41 and then apply the offer   pop up displayed when 2 barcodes are already scanned and B1G2 offer is applied

![image](https://user-images.githubusercontent.com/14803102/81639615-146e2c00-943a-11ea-9ed4-630406180184.png)

![image](https://user-images.githubusercontent.com/14803102/81639740-729b0f00-943a-11ea-89a0-86858aa80ba5.png)

**Comment by shivam-kurtarkar** [comment]
B1G2 {"shoppingCartVariantId":74399,"triggerQty":1,"freebieVariantId":74399,"actionQty":2}
there needs 1 b and 2 g =3 NUT1367-41
msg comes as scan 1 ...

verify if you din click on "nut136741b2g2 "
where  {"shoppingCartVariantId":74399,"triggerQty":2,"freebieVariantId":74399,"actionQty":2}
there needs 2 b and 2 g =4 NUT1367-41
hence scan 2 ...

**Comment by rohan-morje** [comment]
Issue resolved
