### ISSUE TITLE
Allows to apply  cart value freebie when BxGy is already applied

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1603]
![image](https://user-images.githubusercontent.com/14803102/81680959-988fd600-9471-11ea-88a9-ae655cbfb48b.png)

Allows to apply  cart value freebie when BxGy is already applied but do not allow to apply BxGy when Cartvalue  is already applied

@sharangsamonkar

**Comment by shivam-kurtarkar** [comment]
should allow freebie
