### ISSUE TITLE
Remove BxGy  Offer pop up is not displayed when new offer is applied

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1604]
Open POS - GGN Good Earth Mall
Scan 2 barcode of NUT304-27
Apply  BxGY offer
Now Apply  **51 ON MB UN MT** offer

Actual result: Remove BxGy  Offer pop up is not displayed when new offer is applied

Expecetd result: Remove BxGy  Offer pop up is should  displayed when new offer is applied

![image](https://user-images.githubusercontent.com/14803102/81706402-9fc4dd00-948d-11ea-942d-1ae9bf70a3ca.png)

**Comment by rohan-morje** [comment]
Issue not resolved

**Comment by shivam-kurtarkar** [comment]
now fixed
