### ISSUE TITLE
Order could not be placed! Amount mismatch issue has occured. Please try again!!   message on click of receive payment when BxGy offer added and  Premium membership added using OTP

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1605]
OPen GGN Good Earth mall  - Phone 9898989899
Scan 3 barcode of NUT304-27
Apply B2Gy same NUT304-27, (this offer will not get applied)
Apply BxGy NUT304-27 - This offer will get applied
Apply Membership by entering the OTP 
Click on Receive Payment

Actual result: Order could not be placed! Amount mismatch issue has occured. Please try again!!   message on click of receive payment when BxGy offer added and  Premium membership added using OTP

![image](https://user-images.githubusercontent.com/14803102/81709280-67260300-948f-11ea-8b41-527e4cf8d7f2.png)

**Comment by shivam-kurtarkar** [comment]
pos service. validatePos
if (!posLineItemDto.getIsHKMembership()) {


it bypasses validation for variant with different amount

**Comment by shivam-kurtarkar** [comment]
arange ment to save 2 line items with diffrent amount is not made hence follows with this error
@sharangsamonkar

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/81805271-2b934380-9538-11ea-9f03-1ae18aea3df0.png)
