### ISSUE TITLE
Order could not be placed! Amount mismatch issue has occured. Please try again!!  message when placing the order

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1610]
Scan 2 barcode of NUT304-27
scan 1 barcode of NUT1367-39
Apply Premium membership
Apply BxGy offer on NUT304-27
Placce the order and observe

Actual result: Order could not be placed! Amount mismatch issue has occured. Please try again!!  message when placing the order

![image](https://user-images.githubusercontent.com/14803102/81795598-ea943280-9529-11ea-92a5-29c53b208216.png)

**Comment by rohan-morje** [comment]
Issue not resolved
![image](https://user-images.githubusercontent.com/14803102/81801719-7b6f0c00-9532-11ea-9a4b-6ab3de04c361.png)

**Comment by shivam-kurtarkar** [comment]
works
![image](https://user-images.githubusercontent.com/52652317/81821820-f5fa5480-954f-11ea-8c45-91d8b35c91c3.png)

**Comment by rohan-morje** [comment]
Issue resolved

![image](https://user-images.githubusercontent.com/14803102/81829606-b5eb9f80-9558-11ea-96fd-e7f2847589ab.png)

**Comment by rohan-morje** [comment]
Scan 2 barcde of NUT1367-39
Apply BxGy offer
Apply Memebership
Place order

Actual result: Order could not be placed! Amount mismatch issue has occured. Please try again!! message when placing the order



![image](https://user-images.githubusercontent.com/14803102/81841918-c3a92100-9568-11ea-8a14-fd3f51c66dd6.png)

**Comment by rohan-morje** [comment]
Issue resolved


![image](https://user-images.githubusercontent.com/14803102/81848688-20113e00-9573-11ea-9ba2-300c134b1dbd.png)
