### ISSUE TITLE
There is not enough inventory for product variant NUT1367-39, hence offer cannot be applied   message is displlayed when 3 barcodes of NUT1367-39 is

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1621]
GGN Omax Mall  -> GGN omax has 4 barcode of NUT1367-39

Scan 3 barcode and apply B2G2different offer (B2GYdiff NUT136739N433803) and observe
Donot scan any barcode of Gvariant - NUT4338-03

Actual result: There is not enough inventory for product variant NUT1367-39, hence offer cannot be applied...      message is displayed when 3 barcodes of NUT1367-39 is

Expected:  There is not enough inventory for product variant NUT4338-03, hence offer cannot be applied...    message should be displayed

![image](https://user-images.githubusercontent.com/14803102/81959036-84440880-962c-11ea-9bf5-c7a39a082b91.png)

![image](https://user-images.githubusercontent.com/14803102/81959302-db49dd80-962c-11ea-9957-51397820dcb5.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/81959829-aab67380-962d-11ea-8572-c11cb1bbd6a9.png)

**Comment by shivam-kurtarkar** [comment]
Not an issue offer is b2 g2 free
hence needs 2 items of 'NUT4338-03' . while there is only one in the inventory

```[ INFO] [] [http-nio-8181-exec-1] (16 May 2020 16:49:31) (POSAction.java:4798) - Ajency.in :: b:NUT1367-39 x:2 g:NUT4338-03 y:2 label:Buy 2 Get 2```

**Comment by rohan-morje** [comment]
reopen
![image](https://user-images.githubusercontent.com/14803102/82176576-cc954c00-98f4-11ea-9d49-91e297004744.png)
