### ISSUE TITLE
Exception in loggers while placing the order

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1623]
Scan 2 pl
1 npl 
apply cart value freebie and place order

Exception in loggers while placing the order

![image](https://user-images.githubusercontent.com/14803102/82310965-b36ac900-99e2-11ea-8076-c16e982e3f7d.png)

![image](https://user-images.githubusercontent.com/14803102/82310988-bbc30400-99e2-11ea-9935-34bdffca4c8d.png)

**Comment by shivam-kurtarkar** [comment]
written a migration to increase the product_varinat_name to 300
for cart_line_item
and line_item

update date is not updated 
@rohan-morje  need to double ckeck this
