### ISSUE TITLE
Exception while creating new user on POS

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1624]
Open POS
Enter the new customer details and click on Update Customer Info button

Actual result: Undefined pop is displayed and error in logs
[ERROR] [] [http-nio-8080-exec-4] (19 May 2020 10:54:22) (CreateUserAddressRequest.java:39) - Error validatingCreateUserAddressRequest user id cannot be null

**Comment by shivam-kurtarkar** [comment]
web set up is needed for creating new user
