### ISSUE TITLE
Offer not getting applied on converted barcode

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1627]
Please check for converted barcode case : 
i took A barcode pack of 12 and converted into B pack of 6 . My offer was applicable for only 2 barcodes of  B product . 
When i scanned 2 converted barcode of B i got the offer displayed but error msg displayed item level cannot be applied .

NUT5653-03  to be conveted to NUT5653-01
Scan barcode of NUT5653-03
Convert the barcode
Apply cvrtedbxgx1  offer and Observe
Offer not getting applied. 

![image](https://user-images.githubusercontent.com/14803102/82426812-ee820080-9aa5-11ea-833c-c560fe8dba1f.png)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/82431186-fb095780-9aab-11ea-93f7-1737b6852e9d.png)

**Comment by rohan-morje** [comment]
Offer got aplied on barcode converted NUT1367-36 to NUT6234-01

![image](https://user-images.githubusercontent.com/14803102/82431361-2db35000-9aac-11ea-9ee8-7b2d8f07f81f.png)

**Comment by shivam-kurtarkar** [comment]
was freebie created for  converted item 
need to check
