### ISSUE TITLE
Allows to add Cart value freebie when Offer freebie is already applied

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1628]
![image](https://user-images.githubusercontent.com/14803102/82526736-51c96c80-9b52-11ea-9430-4a3096427f72.png)

**Comment by shivam-kurtarkar** [comment]
![image](https://user-images.githubusercontent.com/52652317/82560128-717e8600-9b8e-11ea-88b5-9ba91d2a37f2.png)

**Comment by shivam-kurtarkar** [comment]
![image](https://user-images.githubusercontent.com/52652317/82560383-fe294400-9b8e-11ea-9b99-24d9bdd433b5.png)
