### ISSUE TITLE
Issue when buy1 get 1 free on mrp  is applied

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1629]
Below are the issue when buy1 get 1 free on mrp offer applied
 

For case where user scan a and b barcode then bxgx will be applied on either a or b . On what basis/priority we decided the offer application ?
Issue related to this is : i took product nut5282-02 and nut6234-01 on both of  individually i can apply bxgx offer in diff cart but when i add both product barcodes in the same cart and there is no inventory of nut6234-01 in this case offer should get applied on nut5282-02 barcode but still i was getting the error msg there is no enough invntory for nut6234-01. 

issue : please check if it is data issue or bug bcz i am experiencing with multiple variants
for variants HNUT7344-04,HNUT7341-02,NUT5282-03   bxgy is applied but on screen msg shows up cannot be applied and oder do get placed

**Comment by shivam-kurtarkar** [comment]
2nd issue solved

**Comment by shivam-kurtarkar** [comment]
1st issue solved 
now iterating for variants to apply offer
