### ISSUE TITLE
Offers are not  displaying when PL and NPL products are scanned

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#163]
scan Ultimate Nutrition pv IV-1027199-146 which do not have any offers
scan HealthKart CLA 1000 mg, 60 capsules (HNUT8604-01)

Actual Result: Offers are not  displaying when PL and NPL products are scanned

![image](https://user-images.githubusercontent.com/14803102/49793624-b0829800-fd5b-11e8-8bea-faf16eb128b7.png)

**Comment by pitre55** [comment]
Not an issue... You need to tick offer allowed check box on catalog against that variant for the offers to get displayed.
