### ISSUE TITLE
Some offers are not displaying when we apply the offer, apply membership and remove offer

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1630]
![image](https://user-images.githubusercontent.com/14803102/82529271-40835e80-9b58-11ea-8308-f474d8fa99ec.png)

![image](https://user-images.githubusercontent.com/14803102/82529431-a374f580-9b58-11ea-8839-5dc30336a52b.png)

**Comment by shivam-kurtarkar** [comment]
pls give barcode you scanned, and more info

**Comment by rohan-morje** [comment]
Scan 2 / 3 barcode of NUT6234-01 -> 5 offers will be displayed
Apply bcgxsame offer -> Remove1 variant and observe
Only 3 offers will be displayed

![image](https://user-images.githubusercontent.com/14803102/82545460-5737ae80-9b74-11ea-89b5-cf1bde1c279b.png)

**Comment by shivam-kurtarkar** [comment]
same as https://github.com/ajency/HK-Issue-Tracker/issues/1632
