### ISSUE TITLE
Item level offer cannot be applied to some of the item(s) in your cart! message displayed when variant having BxGY is removed

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1631]
Scan 2 barcode of NUT5282-01
Apply BxGy offer
Remove the variant by clicking on x icon having BxGy offer 

Actual result:  Item level offer cannot be applied to some of the item(s) in your cart! message displayed when variant having BxGY is removed

**Comment by shivam-kurtarkar** [comment]
correct behaviour
