### ISSUE TITLE
Offer applied is not displaying when offer is changed

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1632]
Scan 2 barcode of NUT5282-01 and 2 barcodeof  NUT5282-02
Apply Buy 1 Get on MRP offer
Nowchange and apply **bxgy** offer and observe
Remove Offer pop up will be displayed 
Click Ok

Actual result: bxgy offer applied not displaying

![image](https://user-images.githubusercontent.com/14803102/82550052-94536f00-9b7b-11ea-9b9d-7b523a1cf191.png)

![image](https://user-images.githubusercontent.com/14803102/82550300-edbb9e00-9b7b-11ea-875d-70b7ea53f166.png)

**Comment by shivam-kurtarkar** [comment]
when map of cart variant is created 
if there is bxgy freebie it overwrites the variants amount to 0
since bxgy freebie comes at last
and if variants variantSingleOfferPrice is 0 some offers are not shown

**Comment by rohan-morje** [comment]
resolved
