### ISSUE TITLE
Please scan 1 barcode of NUT1367-41and then apply offermessage displayed when there are other product variant on which BxGy offer is applicable

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1643]
Scan 2 product of 

![image](https://user-images.githubusercontent.com/14803102/82743954-0f8d6e80-9d90-11ea-9ddd-7d32d6f61780.png)

**Comment by shivam-kurtarkar** [comment]
pls mention which order is applied

**Comment by shivam-kurtarkar** [comment]
NUT136741 bxgy gives the message which is correct
![image](https://user-images.githubusercontent.com/52652317/82746550-a79a5080-9dae-11ea-83e8-132c7bddc8a5.png)

Buy 1 Get 1 on MRP applies on 1st one
![image](https://user-images.githubusercontent.com/52652317/82746555-c00a6b00-9dae-11ea-82bc-f00e63291e59.png)
