### ISSUE TITLE
Allows to run DF multiple times within 7 days when 7 days frequency is set for NPL

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#173]
nplDfFrequencyInSeconds = 604800 (7 nights)

Last DF run was 24-12- 2018
Allows to run DF on 28-12 -2018

Actual Result : Allows to run DF multiple times within 7 days when 7 days frequency is set for NPL

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/50511379-674c7b00-0ab3-11e9-8c9b-f48e3af39724.png)

**Comment by rohan-morje** [comment]
DF not happening for NPL on 29-12-2018  20:00:05
DF happening for NPL on 28-12-2018  20:00:05
![image](https://user-images.githubusercontent.com/14803102/50675848-a67c4e00-1016-11e9-89b0-6aa86f094b2e.png)

**Comment by sharangsamonkar** [comment]
This is the correct behaviour. Not an issue.
