### ISSUE TITLE
Clicking on Close and mark RP as checkedin without clicking on save does not throw an error

### ISSUE THREAD

**Issue by ambksud** [ajency/HK-Issue-Tracker#187]
Scenario:
1.From RTO Checking page download and  scan a barcode and set the warehouse condition :Item Missing 
2.Click on Close and mark RP as checkedin without clicking on save
3.Error message pops up saying"Select and scan atleast one row"
4.Click on save and close Close and mark RP as checkedin .
5.Navigate back to RTO checkin page for the same RTO id
6.change the current warehouse condition from Item missing to Item mismatch.
7.Click on close Close and mark RP as checkedin(without clicking on save)

Actual Result
No error message popped up

Expected Results
Error Message should appear saying "Select and  scan atleast one row".

**Comment by priyal105** [comment]
Issue Fixed
