### ISSUE TITLE
UI Issue: Error messages should be Red color

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#196]
https://aqua61.healthkartqa.com/pages/user-outbound-call-details.jsp?phoneNumber=7972109711&login=true&login=true

Actual result: Error messages are not marked in red color

Expected result: Error messages should be red in red color

![image](https://user-images.githubusercontent.com/14803102/52106346-6fe72280-2618-11e9-9725-879abbeb27fc.png)

![image](https://user-images.githubusercontent.com/14803102/52106426-bb013580-2618-11e9-8bb7-b28b8e9d409e.png)

**Comment by sharangsamonkar** [comment]
Red doesn't go well with the background color.

**Comment by rohan-morje** [comment]
Make failure messages in red
