### ISSUE TITLE
When inventory is insufficient and items are marked under review the items are not displayed in the checkout page

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#210]
![b2c14](https://user-images.githubusercontent.com/44566032/52465651-5ceaca00-2ba5-11e9-893d-651a0ec93ba0.png)

**Comment by priyal105** [comment]
1.Create B2C order single item
2.After clicking SO Checkout,in the checkout screen mark items under review.
3.In checkout page there is no link for load details.

**Comment by priyal105** [comment]
ISSUE SOLVED
