### ISSUE TITLE
Mark Checkedout button does not appear in B2C checkout page

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#211]
![b2cs12](https://user-images.githubusercontent.com/44566032/52475183-c0362580-2bc0-11e9-95ea-dadb77ce0619.png)
![b2bs16](https://user-images.githubusercontent.com/44566032/52475193-d217c880-2bc0-11e9-985b-031cdb58073b.png)

**Comment by priyal105** [comment]
Issue Solved
