### ISSUE TITLE
The Bright invoice and the Print Bright so invoice displays under review items.

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#212]
![b2cs20](https://user-images.githubusercontent.com/44566032/52475361-49e5f300-2bc1-11e9-9920-3d72231c2e3c.png)
![b2cs21](https://user-images.githubusercontent.com/44566032/52475385-579b7880-2bc1-11e9-8eb9-0371f3ba4d89.png)

**Comment by priyal105** [comment]
Issue Solved
