### ISSUE TITLE
For B2C order, Invoice and Print Refreshed SO Invoice should display Location and Mfd month fields. 

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#214]
![b2cs17](https://user-images.githubusercontent.com/44566032/52561548-b4956980-2e21-11e9-9f61-33d621a3860b.png)

**Comment by priyal105** [comment]
Issue solved-

-------------------

![b2cinv](https://user-images.githubusercontent.com/44566032/52691761-d90b5600-2f87-11e9-93f8-80ad49a6d47b.png)
![b2cbrightinv](https://user-images.githubusercontent.com/44566032/52691764-df013700-2f87-11e9-8e50-e2bbfb3085a7.png)
