### ISSUE TITLE
Swiggy option gets displayed in payment mode for non registered user

### ISSUE THREAD

**Issue by ambksud** [ajency/HK-Issue-Tracker#222]
Scenario1:
1.Enter the details of a registered user
2.user gets to see Swiigy in the payment mode,Click on it
3.Change the user info to a random phone number (the details get displayed in the POS screen)
4.Click on Customer Update Info

Actual Results
The payment mode field display swiggy

**Comment by rohan-morje** [comment]
Issue verified and resolved
