### ISSUE TITLE
Utilize HKCash can be applied after scanning the barcodes

### ISSUE THREAD

**Issue by ambksud** [ajency/HK-Issue-Tracker#223]

**Comment by rohan-morje** [comment]
issue not resolved
![image](https://user-images.githubusercontent.com/14803102/53322536-ab1bff00-3901-11e9-8683-543c8e3fc944.png)

**Comment by rohan-morje** [comment]
HK can cannot beapplied to non registered users

**Comment by rohan-morje** [comment]
Issue verified and resolved
