### ISSUE TITLE
Wrong requested quantity gets displayed for box enabled in Edit Stock Transfer Page  

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#225]
![snnb18](https://user-images.githubusercontent.com/44566032/53236631-c1844980-36ba-11e9-8679-40e6c5ff98d2.png)
![111111](https://user-images.githubusercontent.com/44566032/53236712-f5f80580-36ba-11e9-8876-3db4e940157a.png)
![111](https://user-images.githubusercontent.com/44566032/53236747-0ad49900-36bb-11e9-86ec-7473433c89ab.png)

**Comment by priyal105** [comment]
Closed
