### ISSUE TITLE
For box enabled after marking box under review, Review Button disappears

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#228]
![ur1](https://user-images.githubusercontent.com/44566032/53403155-1e447480-39d9-11e9-9eac-2f13ac89d133.png)
![ur2](https://user-images.githubusercontent.com/44566032/53403158-213f6500-39d9-11e9-9e36-452c43ffedec.png)

**Comment by priyal105** [comment]
ISSUE SOLVED
