### ISSUE TITLE
After marking box under review,swapping doesnt take place even if inventory is available

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#229]
![ur1](https://user-images.githubusercontent.com/44566032/53403603-f9043600-39d9-11e9-8aea-b6ccbfcaeef5.png)
![ur2](https://user-images.githubusercontent.com/44566032/53403620-ff92ad80-39d9-11e9-9aff-f7dee21729df.png)

**Comment by priyal105** [comment]
CLOSED NON ISSUE
