### ISSUE TITLE
Change Action button text to 'Yes' & 'No'

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/HK-Issue-Tracker#23]
![image](https://user-images.githubusercontent.com/35555935/45292384-af4e8e80-b512-11e8-9238-bc9f8bf74f8d.png)
![image](https://user-images.githubusercontent.com/35555935/45292452-e2911d80-b512-11e8-9c1b-99f80796244b.png)

**Comment by pitre55** [comment]
confirm() uses a dialog built-in to the browser. There is no way to change the buttons.
