### ISSUE TITLE
Incorrect message appears after marking box under review

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#230]
![screenshot 2019-02-26 at 5 28 55 pm](https://user-images.githubusercontent.com/44566032/53412079-5e622200-39ee-11e9-800a-e90b465b5893.png)
![screenshot 2019-02-26 at 5 29 24 pm](https://user-images.githubusercontent.com/44566032/53412111-79cd2d00-39ee-11e9-88f1-f15a8d7eb369.png)

**Comment by priyal105** [comment]
![screenshot 2019-02-27 at 11 41 41 am](https://user-images.githubusercontent.com/44566032/53469684-f579b900-3a84-11e9-8e6a-c2d45d688df9.png)

**Comment by priyal105** [comment]
ISSUE SOLVED
