### ISSUE TITLE
PLease select payment mode message is displaying when clicking on Receive payment button afterselecting swigy payment

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#267]
Enter the non swiggy number
Scan the barcode
Select payment option Offline paytm
Change the phone number to Swiggy number
Select Swiggy payment
Click on Receive payment button

PLease select payment mode message is displaying

![image](https://user-images.githubusercontent.com/14803102/54519517-c15f2d00-498c-11e9-80b5-ffc0009f8c22.png)

**Comment by pitre55** [comment]
Not an issue... Ant db was not run, and swiggy payment mode was not present in db
