### ISSUE TITLE
Bulk upload functionality not working as expected.

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#268]
![Screenshot 2019-03-19 at 3 42 49 PM](https://user-images.githubusercontent.com/44566032/54604083-ef676e80-4a6b-11e9-853e-ba79cd9bfe42.png)
![Screenshot 2019-03-19 at 10 57 09 AM](https://user-images.githubusercontent.com/44566032/54603964-9dbee400-4a6b-11e9-964e-554f6272f541.png)
![Screenshot 2019-03-19 at 3 52 59 PM](https://user-images.githubusercontent.com/44566032/54604016-c050fd00-4a6b-11e9-9de6-8d0dc0592296.png)

**Comment by priyal105** [comment]
CLOSED

**Comment by priyal105** [comment]
EXISTING CASE:

1. Excel sheet has 2 entries:
1 Variant is GT
Same variant is present with no channel name

2.Excel sheet has 2 entries:
1 Variant is GT
Same variant is present with invalid channel name

**Comment by ambksud** [comment]
> EXISTING CASE:
> 
> 1. Excel sheet has 2 entries:
>    1 Variant is GT
>    Same variant is present with no channel name
> 
> 2.Excel sheet has 2 entries:
> 1 Variant is GT
> Same variant is present with invalid channel name

Non - issue

**Comment by priyal105** [comment]
Takes the latest valid variant entry.

**Comment by priyal105** [comment]
Takes the latest valid variant entry.

**Comment by priyal105** [comment]
On the excel sheet entering Variant id, blank column and then channel name and then uploading throws message "Upload failed - null"

**Comment by priyal105** [comment]
Issue solved
