### ISSUE TITLE
Bulk upload doesnt work as expected

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#273]
Scenario 1: Box enabled

Shelf life>max
Bulk
Request has been submitted successfully

Shelf life<min
Bulk
Request has been submitted successfully

Scenario 2: Box disabled

Shelf life>max
Bulk
Request has been submitted successfully

Shelf life<min
Bulk
Request has been submitted successfully

Scenario 3: Box enabled and later disabled
Bulk
Please scan a valid box ,either this box size does not match with any of the booked box sizes or shelf life is not same !!

**Comment by priyal105** [comment]
CLOSED
