### ISSUE TITLE
Incorrect messages displayed for bulk upload ST

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#274]
Scenario 1: Box enabled

Shelf life>max
Bulk
Request has been submitted successfully

Shelf life<min
Bulk
Request has been submitted successfully

Please scan a valid box ,either this box size does not match with any of the booked box sizes or shelf life is not same !!

Scenario 2: Box disabled

Shelf life>max
Bulk
Request has been submitted successfully

Shelf life<min
Bulk
Request has been submitted successfully

Scenario 3: Box enabled and later disabled
Bulk
Please scan a valid box ,either this box size does not match with any of the booked box sizes or shelf life is not same !!

**Comment by priyal105** [comment]
B2B-

Scenario1: 
BOX ENABLED AND LATER DISABLED-
Entering barcode with shelf life less than max

UI
Request has been submitted successfully

Bulk	 	 	
FAILED
Please scan a valid box ,either this box size does not match with any of the booked box sizes or shelf life is not same !!

Scenario2: 
UI
Request has been submitted successfully

>max
Upload failed - Exception @ Row:1 Invalid Column in excel.

Please scan a valid box ,either this box size does not match with any of the booked box sizes or shelf life is not same !!

**Comment by priyal105** [comment]
CLOSED
