### ISSUE TITLE
For B2B order on scanning barcode, shelf life within the range doesnt work as expected

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#284]
Scenario1:Box enabled

Scan barcode with shelf life within the range

Message-
single-  "Oops!! Shelf life of item is less than default shelf life or greater than maximum shelf life of booked items"

bulk upload-Shelf life not satisfied!!

Scenario2:Box disabled 

Scan barcode with shelf life within the range

Message-"Oops!! Shelf life of item is less than default shelf life or greater than maximum shelf life of booked items"

**Comment by priyal105** [comment]
CLOSED
