### ISSUE TITLE
Box_Prefix shoudl be non mandatory while warehouse creation

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/HK-Issue-Tracker#3]
Snapshot dd the requirement document:
![image](https://user-images.githubusercontent.com/35555935/44980651-18bc2380-af8e-11e8-97f9-912fcafe6bae.png)

**Comment by pitre55** [comment]
fixed

**Comment by SavantMaithili** [comment]
Tested - Success

Can create warehouse with empty box prefix
