### ISSUE TITLE
Validation message displayed as bullet point; enter size field should not be displayed with this validation

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/HK-Issue-Tracker#30]
![image](https://user-images.githubusercontent.com/35555935/45669207-e806ed00-bb3c-11e8-993b-198124f1ff9c.png)

- This error is not easily readable 
- Also, if this is incorrect variant, why do we show boz size field on clicking 'Search' ?

**Comment by pitre55** [comment]
Existing functionality on Catalog portal for all the validations
