### ISSUE TITLE
When freebie group is edited, new entry is not created in Cart_value_freebie_config_log table

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#305]

**Comment by rohan-morje** [comment]
Edit the freebie group and Save

Actual: When freebie group is edited, new entry is not created in Cart_value_freebie_config_log table
same entry is updated

**Comment by Shraddhar23** [comment]
Could not replicate on Local

**Comment by rohan-morje** [comment]
Rplicate on 145
