### ISSUE TITLE
Please enter valid input fields validation is displayed on home page instead of Add New 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#306]
Enter negative value in MIN/max cart value  and quantity and click on Save

![image](https://user-images.githubusercontent.com/14803102/56114156-a2e55500-5f7d-11e9-8697-1205f71a0b0f.png)

**Comment by Shraddhar23** [comment]
same as #304

**Comment by rohan-morje** [comment]
Issue resolved
