### ISSUE TITLE
Null value is displayed in Eligible Freebie Groups column in edit mode

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#307]
Go to Retail Freebie Group Configuration
Edit the Freebie Groups and click on Save

Null value is displayed in Eligible Freebie Groups column after editing the record

![image](https://user-images.githubusercontent.com/14803102/56133087-3ed88600-5fa9-11e9-81c4-fb67814b5abb.png)

**Comment by Shraddhar23** [comment]
Unable to replicate on Local

**Comment by rohan-morje** [comment]
Issue replicable on 145

**Comment by rohan-morje** [comment]
Issue resolved
