### ISSUE TITLE
Discount cannot be more than the total amount validation displayed

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#312]
Scan the barcode
Attach Gymbag Freebie from Cart line freebie
Apply 26 % ITEM LEVEL DISCT PRC ITEM VALUE ON MRP and observe

Actual result: Discount cannot be more than total amount validation displayed

![image](https://user-images.githubusercontent.com/14803102/56284303-bcc79900-6131-11e9-81d2-b791a6c38af1.png)

![image](https://user-images.githubusercontent.com/14803102/56284276-a6214200-6131-11e9-8990-6d87a751d39b.png)

**Comment by sharangsamonkar** [comment]
![Screenshot 2019-04-23 at 6 37 58 PM](https://user-images.githubusercontent.com/29853994/56583324-f3e8ef00-65f6-11e9-96c1-750ee90feb43.png)

**Comment by rohan-morje** [comment]
Issue resolved
