### ISSUE TITLE
Null pointer error occurs when applying 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#313]
Scan the barcode
Apply 26 % ITEM LEVEL DISCT PRC ITEM VALUE ON MRP
Click on Receive payment

Actual result: Null pointer error

![image](https://user-images.githubusercontent.com/14803102/56285182-411b1b80-6134-11e9-97fc-9e0974b2585f.png)

![image](https://user-images.githubusercontent.com/14803102/56285149-2a74c480-6134-11e9-8ee7-3b89ea839b09.png)

**Comment by sharangsamonkar** [comment]
![Screenshot 2019-04-20 at 7 33 35 PM](https://user-images.githubusercontent.com/29853994/56458362-3dd99700-63a3-11e9-8a1b-7cf76ab65bc3.png)

**Comment by rohan-morje** [comment]
resolved
