### ISSUE TITLE
In Order Invoice, freebie are displaying above main product

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#316]
Go to BO page
Search the BO  ID 13545688
clickon Inoive link

In Order Invoice, freebie are displaying above main product

![image](https://user-images.githubusercontent.com/14803102/56340438-8c363c80-61cf-11e9-955d-6ce3e32b740f.png)

![image](https://user-images.githubusercontent.com/14803102/56340571-e800c580-61cf-11e9-8f8a-6cbf73b73dc9.png)

**Comment by sharangsamonkar** [comment]
fixed. new orders should not show this issue

**Comment by rohan-morje** [comment]
Not able to view invoice
