### ISSUE TITLE
NPL Product - PAYMENT_AND_CHECKOUT_AMOUNT_MISMATCH##PAYMENT7699.0##CLI_AMOUNT##7298.0 Error occurred while creating Order

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#317]
Scan NPL product (NUT304-27)
Apply NPL PL Offer -  Get Rs 401.0 ORDER LEVEL DISCOUNT FLAT 
Apply Cart freebie
Click on Receive Payment 

Actual result:  PAYMENT_AND_CHECKOUT_AMOUNT_MISMATCH##PAYMENT7699.0##CLI_AMOUNT##7298.0 Error occurred while creating Order

![image](https://user-images.githubusercontent.com/14803102/56337989-a0753c00-61c5-11e9-81b9-bf7bfdf3e87c.png)

**Comment by sharangsamonkar** [comment]
offer not available

**Comment by rohan-morje** [comment]
Issue resolved
