### ISSUE TITLE
PAYMENT_AND_CHECKOUT_AMOUNT_MISMATCH when offer freebie is applied to flash enabled  pv

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#320]
Scan PL   (NUT5055-02
Scan flash enabled PL  NUT5282-02)
Apply offer freebie - Freebie with NUT4338-03
Click on Receive payment

Actual result: 
PAYMENT_AND_CHECKOUT_AMOUNT_MISMATCH##PAYMENT2798.61##CLI_AMOUNT##3578.61
Error occurred while creating Order

![image](https://user-images.githubusercontent.com/14803102/56358545-83a82b00-61fc-11e9-9ca6-89987de10779.png)

**Comment by sharangsamonkar** [comment]
![Screenshot 2019-04-20 at 6 01 55 PM](https://user-images.githubusercontent.com/29853994/56457318-6d35d700-6396-11e9-9f68-194d40496d25.png)

**Comment by rohan-morje** [comment]
resolved
