### ISSUE TITLE
Null pointer exception when applying offer

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#321]
https://aqua145.healthkartqa.com/admin/pos/POS.action
Scan HNUT10823-0
Cart value freebie not selected
Apply  NPL PL Offer -> Item level offer cannot be applied to some of the item(s) in your cart!
Apply 
Apply 210.0 ITEM LEVEL DISCOUNT FLAT ONMRP -   Item level offer cannot be applied to some of the item(s) in your cart!
Chnage freebie without removing
Apply  33 PERC ITEM LEVEL DIS ON ITEM VALUE -> Null pointer exception occured

![image](https://user-images.githubusercontent.com/14803102/56405473-05926580-628a-11e9-95d6-2cf99fe0d15c.png)

**Comment by sharangsamonkar** [comment]
not an issue anymore

**Comment by rohan-morje** [comment]
resolved
