### ISSUE TITLE
SIS  PAYMENT_AND_CHECKOUT_AMOUNT_MISMATCH##PAYMENT537.0

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#325]
PAYMENT_AND_CHECKOUT_AMOUNT_MISMATCH##PAYMENT537.0Sc

Scan PL 
Attach cart value freebie
Apply SIS Offer 481 ITEM LEVEL DIS FLAT ONMRP

![image](https://user-images.githubusercontent.com/14803102/56421093-781d3880-62be-11e9-8f25-a5332cf2defa.png)

**Comment by sharangsamonkar** [comment]
![Screenshot 2019-04-20 at 5 19 15 PM](https://user-images.githubusercontent.com/29853994/56456902-7f147b80-6390-11e9-9ba2-cd3b8517115e.png)

**Comment by rohan-morje** [comment]
Issue resolved
