### ISSUE TITLE
Discount cannot be more than the total amount validation displayed 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#329]
Scan (HNUT10823-01) Nouriza Protein Cookies, 100 g Choco Chip 
Apply cart value freebie - MuscleBlaze Shaker, Assorted 650 ml (NUT4338-03) (Shaker)
Apply 26 % ITEM LEVEL DISCT PRC ITEM VALUE ON MRP

Actual result: Discount cannot be more than the total amount validation displayed  when clicked on receive payment

![image](https://user-images.githubusercontent.com/14803102/56493446-c1fb5e00-650c-11e9-9d37-f0ac0fa9f6ee.png)

**Comment by sharangsamonkar** [comment]
![Screenshot 2019-04-23 at 6 44 45 PM](https://user-images.githubusercontent.com/29853994/56583742-e6803480-65f7-11e9-9322-4619bb86264b.png)

**Comment by rohan-morje** [comment]
issue resolved
