### ISSUE TITLE
404 Error occurred when clicked on invoice link

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#347]
ST ID 43660
Go to ST and click on Invoice link
![Screen Shot 2019-05-13 at 12 48 31 PM](https://user-images.githubusercontent.com/14803102/57615518-83037a00-7599-11e9-9404-c4eaaa8e4cc7.png)

**Comment by sharangsamonkar** [comment]
is this the right screenshot?

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/57697189-4eaebd00-7670-11e9-87ea-9b1401555a85.png)

**Comment by rohan-morje** [comment]
Invoice displaying
