### ISSUE TITLE
Pagination displayed twice on Premium Party Listing Screen

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#355]
![1](https://user-images.githubusercontent.com/44566032/57928356-13a9c500-78ce-11e9-8b22-ce990ac29405.png)
![2](https://user-images.githubusercontent.com/44566032/57928363-199fa600-78ce-11e9-8881-b61b476d6842.png)

**Comment by priyal105** [comment]
Non issue
