### ISSUE TITLE
Incorrect popup message appears when trying to add/delete party on Premium Party Listing Screen

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#357]
Existing case:
1.Add party-
Click on Add link
Confirmation pop up appears with message as-Are you sure you want to add user to premium party?

2.Delete party-
Click on Delete link
Confirmation pop up appears with message as-'Are you sure you want to delete premium party mapping for the user?

Proposed case:
1.Add party-
Click on Add link
Confirmation pop up appears with message as-'Are you sure you want to Add Store Name to the Premium Club?'

2.Delete party-
Click on Delete link
Confirmation pop up appears with message as-'Are you sure you want to delete Store Name to the Premium Club?'

![3](https://user-images.githubusercontent.com/44566032/57929137-21604a00-78d0-11e9-974a-87fadbe69039.png)
![4](https://user-images.githubusercontent.com/44566032/57929144-2624fe00-78d0-11e9-88e4-b8db0dcd5032.png)

**Comment by priyal105** [comment]
ISSUE SOLVED
