### ISSUE TITLE
Incorrect message appears after adding/deleting party on Premium Party Listing Screen

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#358]
Existing case:
1.After adding party to premium club-
Message appears as-User added to premium party

2.1.After deleting party from premium club-
Message appears as-User premium party mapping deleted

Proposed case:
1.After adding party to premium club-
Message appears as-‘Party Added Successfully to the premium Club’ 

2.After deleting party from premium club-
Message appears as-‘Party deleted successfully from the premium club'

**Comment by priyal105** [comment]
ISSUE SOLVED
