### ISSUE TITLE
Clicking on Print Delivery Note button throws HTTP Status 404 error 

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#376]
![11](https://user-images.githubusercontent.com/44566032/58457678-e4544d00-8144-11e9-8f2b-49628f8c70e0.png)
![12](https://user-images.githubusercontent.com/44566032/58457683-ea4a2e00-8144-11e9-9f6e-cc388941c9d5.png)

**Comment by priyal105** [comment]
CLOSED
