### ISSUE TITLE
Incorrect CheckedIN Qty displayed on Inventory Checkin Against Stock Transfer page after closing ST for Aqua to Aqua ST

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#380]
![4 2](https://user-images.githubusercontent.com/44566032/59180164-d27d9b80-8b81-11e9-8fd2-40ca06fab8a8.png)
![4 1](https://user-images.githubusercontent.com/44566032/59180170-d4475f00-8b81-11e9-8d09-25da100dc86c.png)

**Comment by priyal105** [comment]
ISSUE CLOSED
