### ISSUE TITLE
When trying to checkin freebie on aqua throws Invalid checkin error

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#381]
![3 2](https://user-images.githubusercontent.com/44566032/59180319-3e600400-8b82-11e9-9dcc-c170c033e664.png)
![3 1](https://user-images.githubusercontent.com/44566032/59180321-415af480-8b82-11e9-8492-3a479092fd7f.png)

**Comment by priyal105** [comment]
ISSUE CLOSED
