### ISSUE TITLE
Pay at store order data not reflecting in DSR

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#387]
Precondition: pay at str placed for Delhi greenpark
Select Delhi Green park store
Go to Warehouse -> DSR
Select 19 june date and  click on Create DSR for POS and pay at Store button

Actual result: Pay at store order data not reflecting in DSR 

![image](https://user-images.githubusercontent.com/14803102/59741221-fd55a700-9287-11e9-948f-90c5a15e9cb5.png)

**Comment by sharangsamonkar** [comment]
Because base_order status is not delivered.

**Comment by rohan-morje** [comment]
Issue resolved
