### ISSUE TITLE
In view DSR values are not rounded off to 2 after decimals

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#407]
Go to view DSr of naraina store on 27 June and Observe

Actual result: In view DSR values are not rounded off to 2 decimals

Expected: In view DSR values should be round off to 2 points after decimal 

![image](https://user-images.githubusercontent.com/14803102/60248082-851e5f80-98df-11e9-939e-181a8cb28c67.png)

**Comment by sharangsamonkar** [comment]
To test this makes sales such that the total of some collection is in decimal.

Also added rounding off to the total column. Please check that as well.

**Comment by rohan-morje** [comment]
Issue resolved
