### ISSUE TITLE
Confirmation pop up appears if duplicate mfg batch no is entered when warehouse is selected on Job Manual/Auto Screen

### ISSUE THREAD

**Issue by ghost** [ajency/HK-Issue-Tracker#411]
![c2](https://user-images.githubusercontent.com/44566032/60324987-d4c65f00-99a3-11e9-8ac7-d3425bbd7a8a.png)

**Comment by priyal105** [comment]
Selected warehouse: HK Bright WH 4.0

**Comment by priyal105** [comment]
CLOSED
