### ISSUE TITLE
Null pointer exception when saving the HK.com DSR  by keeping store value field empty

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#416]
HK.com cash order was placed for Dwarka sec 7 store
Go to Create DSR for HK.com order
Enter the store value for Cash collection
Do not enter Store value for Prepaid Collection and click on Save button

Actual result: NUll pointer exception hen saving the HK.com DSR  by keeping store value field empty

 
![image](https://user-images.githubusercontent.com/14803102/60437253-96db6c00-9c2b-11e9-8b57-a9bd9c1105fa.png)

**Comment by sharangsamonkar** [comment]
Handled. If no values are passed they are treated as 0.

**Comment by rohan-morje** [comment]
Issue resolved
