### ISSUE TITLE
Valdation not displayed when End date is less than Start date when viewing DSR i

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#420]
Go to DSR page
Select  End date is less than Start date
Eg Start date: 4 july
 End date :1 July
Click on View DSR for POS & pay at store or View DSR for hk.com

Actual result: Validation not displayed when End date is less than Start date when viewing DSR

**Comment by sharangsamonkar** [comment]
added on all places. please check.

**Comment by rohan-morje** [comment]
Issue resolved
