### ISSUE TITLE
HK.com order is not displaying in sales breakup link under cash collection

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#421]
3 HK.com  order were placed for dwarka sec 10
HKD-09709-17935767 paytm 549  
HKD-76535-17935769 split card 500 paytm 49   Delivery by SM
HKD-03627-17935771 cash 549 Store pickup

HKD-09709-17935767  HK.com order is not displaying in sales breakup link under cash collection
![image](https://user-images.githubusercontent.com/14803102/60510035-14ff4780-9cec-11e9-8aab-b1fb924fe255.png)

![image](https://user-images.githubusercontent.com/14803102/60510130-4d9f2100-9cec-11e9-8613-9b2a628b8b86.png)

**Comment by sharangsamonkar** [comment]
it is paytm should not show in cash anyways.
As per the new logic is should come under prepaid.

Please check this and if it isnt there please move this bug to not fixed
