### ISSUE TITLE
Pay at store data not reflecting in Create DSR page

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#425]
Go to Mum bandra store
Create DSR for  2nd July and Observe

Pay at store data not reflecting in Create DSR page for Mum bandra store

![image](https://user-images.githubusercontent.com/14803102/60566728-63145980-9d85-11e9-9f00-e20a67e90c90.png)
![image](https://user-images.githubusercontent.com/14803102/60566740-6f001b80-9d85-11e9-92f5-aa9099362be9.png)

**Comment by sharangsamonkar** [comment]
cannot replicate
