### ISSUE TITLE
Customer name not displaying in Pay at Store sales breakup page

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#430]
Pay at store order was placed for  9742418095 
Go to Mum bandra store 
Go to create DSR 
Click on sales breakup link of Card collection pay at store and observe

Actual result: Customer name not displaying in Pay at Store sales breakup page

![image](https://user-images.githubusercontent.com/14803102/60659954-4276fd00-9e74-11e9-93ab-94065c5e831a.png)

![image](https://user-images.githubusercontent.com/14803102/60659847-093e8d00-9e74-11e9-9689-7189a97c50ad.png)

**Comment by sharangsamonkar** [comment]
These users do not have the name saved on hk_cat db.

**Comment by rohan-morje** [comment]
Issue resolved
