### ISSUE TITLE
For Mum bandra store banking data of Del Green park and Mum bandra is displaying in View banking page

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#437]
Go to Mum bandra store
GO to DSR -> Banking section
Select Start date: 5 July   End date: 5 July
Do not select any store and  click on View banking by date and observe 

Actual result: For Mum bandra store, banking data of Del Green park and Mum bandra is displaying in View banking page

Expected result: Banking data of only Mum bandra should be displayed
![image](https://user-images.githubusercontent.com/14803102/60715426-99470a00-9f3a-11e9-97d8-cad3cdea8a09.png)

**Comment by sharangsamonkar** [comment]
Cannot replicate

**Comment by rohan-morje** [comment]
Selected Store (retail store) data is displaying with store selected from banking dropdown
Select a WH: BLR HSR
Go to Banking , select MUm bandra store from dropdown and observe

Actual result:Selected Store (retail store) data is displaying with store selected from banking dropdown

![image](https://user-images.githubusercontent.com/14803102/60788151-a7369e00-a179-11e9-9bad-38d9b66aa80f.png)

**Comment by rohan-morje** [comment]
Issue resolved
