### ISSUE TITLE
STs skipped due to weight check count displayed is incorrect

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#460]
DF was set to happen for 2 retail store
But due to weight check . DF did not happen

Actual result: In  STs skipped due to weight check column count is shown as 1 instead of 2

Expected result:  2 count should be shown in STs skipped due to weight check column

![image](https://user-images.githubusercontent.com/14803102/61512096-80e4ee00-aa16-11e9-80c6-0cb6a8e9703b.png)

![image](https://user-images.githubusercontent.com/14803102/61512101-86dacf00-aa16-11e9-8dc0-53c1dccd4f1c.png)

**Comment by sharangsamonkar** [comment]
issue fixed
