### ISSUE TITLE
Order getting placed when Paytm Voucher amount is less than Order Amount

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#509]
Go to POS screen
Scan the product - Total cart value is 699
Apply the HK cash : 350 
Cart value becomes 699 -350 = 
Now apply Paytm Voucher of 400 .  Paytm voucher will get applied successfully and Receive payment button will be enabled
Now remove the HK cash attached
Now cart value is 699 and Paytm voucher vlaue is 400
Still order is getting placed

![image](https://user-images.githubusercontent.com/14803102/63940606-7db63680-ca87-11e9-8320-f6bb04a85f01.png)

**Comment by sharangsamonkar** [comment]
Similar to #508. Fixed.

**Comment by rohan-morje** [comment]
Cart value changed. Please re-apply voucher. message is displayed

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/63994584-b18a6e00-cb12-11e9-89ce-1c1988a22567.png)
