### ISSUE TITLE
Results are not sorted according to expiry date.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#545]
The barcodes to expire first should be on the top with respect to the applied filters.
![sorting_data_issue](https://user-images.githubusercontent.com/54023516/65123096-2cf38700-da10-11e9-95f5-6a616ee100c0.png)

**Comment by shivam-kurtarkar** [comment]
sorted by product expiry date and then sku item id

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/65406826-4fb1e100-ddfe-11e9-90cd-34574eb74058.png)

the results are sorted according to the expiry date.
