### ISSUE TITLE
Create new stock transfer label and test button  appears on barcodes page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#546]
The TEST button and the CREATE STOCK TRANSFER is not needed.
![ui](https://user-images.githubusercontent.com/54023516/65134625-3554bd80-da22-11e9-92c7-bd27aa280c5f.png)

**Comment by shivam-kurtarkar** [comment]
The TEST button and the CREATE STOCK TRANSFER  button removed

**Comment by larissa-c-d** [comment]
The Test button and create stock transfer button does not exists.
![image](https://user-images.githubusercontent.com/54023516/65405935-7a4e6a80-ddfb-11e9-92a0-9afd57274a1b.png)
