### ISSUE TITLE
sku item id is displayed as id in the table for barcodes

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#547]
the id column contains sku item id which is not a necessary column.
![id_issue](https://user-images.githubusercontent.com/54023516/65134371-d2632680-da21-11e9-8320-d5012cda299e.png)

**Comment by sharangsamonkar** [comment]
Please add a description and a screenshot of all issues.

**Comment by larissa-c-d** [comment]
Okay

**Comment by shivam-kurtarkar** [comment]
renamed id to sku item id

**Comment by larissa-c-d** [comment]
sku item id should be removed from the table.
![image](https://user-images.githubusercontent.com/54023516/65406126-21330680-ddfc-11e9-867b-f3c2e024c939.png)
