### ISSUE TITLE
Displays extra entries if the filter settings are default.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#548]
should display results for all warehouses,all variants id's in those warehouses,with all the statuses and sorted according to expiry date (barcode to expire first should be on top)
![no_filter_selected](https://user-images.githubusercontent.com/54023516/65138905-5ec51780-da29-11e9-94ac-2892e28f3516.png)

**Comment by shivam-kurtarkar** [comment]
extra entries of non sis and retail warehouses filtered out

**Comment by larissa-c-d** [comment]
The correct number of entries are displayed.
![image](https://user-images.githubusercontent.com/54023516/65406057-d6b18a00-ddfb-11e9-9c38-a16bb85b1322.png)
