### ISSUE TITLE
Extra entries for the date filter

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#550]
There are extra entries for expiry date filter.

![extra_entries_date](https://user-images.githubusercontent.com/54023516/65149419-af476f80-da3f-11e9-87cd-29196192a725.png)

**Comment by shivam-kurtarkar** [comment]
changed expiry filter  to expiry after

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/65405473-e16b1f80-ddf9-11e9-9f0b-c1da27b0ec5e.png)
 extra entries still exists for the expiry date filter.

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/65949884-a2bd1100-e45a-11e9-98ba-37a4e1bb4e4a.png)
results for the specified expiry date displayed.
