### ISSUE TITLE
Displays multiple barcodes when details are viewed after inventory checkin

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#554]
![muliple_barcodes_after_inventory checkin](https://user-images.githubusercontent.com/54023516/65243433-f9932400-db05-11e9-9a77-352818ba0e31.png)

multiple barcodes are displayed when clicked on view details is clicked after stock transfer

**Comment by shivam-kurtarkar** [comment]
same as #553

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/65484328-a7af1d00-debc-11e9-9da9-b7f16364827c.png)

issue still exists,displays multiple issues.

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66453533-4bcec180-ea82-11e9-81d3-27bec1dd64ec.png)

barcodes are displayed correctly.
