### ISSUE TITLE
Item details not displayed for damaged product

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#555]
![damaged_entry_revert1](https://user-images.githubusercontent.com/54023516/65246862-fc454780-db0c-11e9-8822-f496def7bffd.png)
![damaged_enrty_revert_2](https://user-images.githubusercontent.com/54023516/65246866-fe0f0b00-db0c-11e9-8f69-2de45c0984aa.png)

Item details are  not displayed for a damaged product after the creation of a stock transfer.

**Comment by shivam-kurtarkar** [comment]
item displayed only for checked in and checked out status.

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66544887-fdd7bd80-eb56-11e9-9112-fb4ce4dd6cfd.png)
![image](https://user-images.githubusercontent.com/54023516/66544901-0d570680-eb57-11e9-8238-ef056c38169d.png)
Issue exists on the master branch also.
