### ISSUE TITLE
Update stock transfer button is present when stock transfer  is marked as completed at the source warehouse. .

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#559]
![update_stock_transfer_button_present_if_stock_transfer_marked_completed](https://user-images.githubusercontent.com/54023516/65302601-4b38be80-db99-11e9-9deb-f470ad77a44f.png)

The update stock transfer button is still preset if the stock transfer is marked as completed at the source warehouse.

**Comment by shivam-kurtarkar** [comment]
probably not a bug .

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66544104-ca942f00-eb54-11e9-9a20-3d30bcc7dc51.png)
Issue exists on mater branch also.
