### ISSUE TITLE
30 percent discount is getting applied during Flash period - Highest discount ie SKU -  70 percent is not getting applied

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#56]
Item: MuscleBlaze CLA 1000, 90 softgels ( Product varinat id : NUT5445-01)  IVM-348-20605

Purchase time: 5.11PM 2018-09-26
Flash Sale Timing > 15 units start: 2018-09-26 17:00 end: 2018-09-26 18:00

Flash sale id : 
FEFO Enabled : 40%
SKU Discount: 70%
Product Variant Discount: 20%
Flash Discount: 50%

Actual Result : 30 percent discount is getting applied during Flash period
Highest discount ie SKU -  70 percent is not getting applied

![30 percert discount](https://user-images.githubusercontent.com/14803102/46079181-065f8f00-c1b4-11e8-8b2d-23380c3c2887.png)

**Comment by sharangsamonkar** [comment]
Works fine.

**Comment by rohan-morje** [comment]
Not an issue
