### ISSUE TITLE
Select a warehouse does not contain all the warehouses 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#564]
![missing_warehouses](https://user-images.githubusercontent.com/54023516/65315053-0de22a00-dbb5-11e9-9b0a-ef1311051c77.png)

Select a warehouse dropdown does not contain all the warehouses

**Comment by shivam-kurtarkar** [comment]
only displays warehouses for logged in users

**Comment by larissa-c-d** [comment]
/home/larissa/Pictures/week2/pne_kal_warehouse.png

warehouse assigned to user can be changed.
