### ISSUE TITLE
barcode that is in the process of stock transfer can be scanned for stock transfer again

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#567]
![same_barcode_stock_transfer_1](https://user-images.githubusercontent.com/54023516/65318705-c3b07700-dbbb-11e9-8a7c-878f7403946a.png)
![same_barcode_stock_transfer_2](https://user-images.githubusercontent.com/54023516/65318709-c6ab6780-dbbb-11e9-9b25-bdb10a543772.png)
![same_barcode_stock_transfer_3](https://user-images.githubusercontent.com/54023516/65318716-c9a65800-dbbb-11e9-8aff-c172ccf9dcd7.png)

When a stock transfer is being made form source warehouse (MUM Bandra )to destination warehouse( MUM Mahavir Nagar) for a barcode (IVM-387-48208) and when the create and save button is clicked and the stock transfer is marked as completed at the source warehouse .It allows scanning the same barcode (IVM-387-48208 )for another stock transfer and save it.

**Comment by shivam-kurtarkar** [comment]
fails to enforce checking. barcode is checked while adding to the list but not while saving. hence we can add one item to multiple carts and then when we save same item is can be added to all the carts

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66455726-31e4ad00-ea89-11e9-9018-c7a505c779ea.png)

Does not allow to scan the item for another stock transfer once scanned for a stock transfer.
