### ISSUE TITLE
No stock transfer info not displayed for some of the stock transfers

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#568]
![image](https://user-images.githubusercontent.com/54023516/65957345-36e2a480-e46a-11e9-8460-d59bd850fafc.png)

![image](https://user-images.githubusercontent.com/54023516/65484090-03c57180-debc-11e9-8834-6fa4bb5e7252.png)

stock transfer info is not displayed fro some of the stock transfers.

**Comment by shivam-kurtarkar** [comment]
need more info to recreate situation.

**Comment by larissa-c-d** [comment]
stock transfer info is displayed for entries after specific date (19th sept 2019)
