### ISSUE TITLE
Wrong barcodes displayed in the table when a stock transfer is created and saved.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#569]
![wrong_barcodes_displayed_1](https://user-images.githubusercontent.com/54023516/65486187-7258fe00-dec1-11e9-9d2b-2d58619e37e6.png)
![wrong_barcodes_displayed_2](https://user-images.githubusercontent.com/54023516/65486198-7c7afc80-dec1-11e9-9f90-26c27a6594f9.png)

wrong barcodes are displayed.

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66284686-9fa4a380-e8e6-11e9-9aed-1559073ccc69.png)
![image](https://user-images.githubusercontent.com/54023516/66284812-5acd3c80-e8e7-11e9-91c0-e25127f22ff6.png)

issue still exists, barcode displayed in the stock transfer table when the item is scanned and the button "**save and create stock transfer"** is clicked is different form the barcode displayed in the table when the "**view item details**" button is clicked.

**Comment by shivam-kurtarkar** [comment]
probably not an error

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66545130-ab4ad100-eb57-11e9-9e35-190ba4b5d45f.png)
Issue exists on the master branch also.
