### ISSUE TITLE
The Gym dropdown for gym does not contain the gym name .

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#570]
![dropdown](https://user-images.githubusercontent.com/54023516/65506148-8f54f780-dee8-11e9-9232-3f69814519fb.png)

the gym dropdown does not contain the gyms i the dropdown.
the state dropdown does not contain the states

**Comment by shivam-kurtarkar** [comment]
system issue

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66541465-ff9c8380-eb4c-11e9-98be-0a718d3b76bf.png)
 Issue exists on master branch also.
