### ISSUE TITLE
Update customer info creates a new entry.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#575]
![update_customer_info_1](https://user-images.githubusercontent.com/54023516/65572893-1b1d6100-df87-11e9-8729-51ccd0c246bd.png)
![update_customer_info2](https://user-images.githubusercontent.com/54023516/65572897-1e185180-df87-11e9-9266-76304629805e.png)
 
update customer info creates a new entry in the database

**Comment by shivam-kurtarkar** [comment]
system issue

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66543684-af74ef80-eb53-11e9-9d46-01db582b8f05.png)
![image](https://user-images.githubusercontent.com/54023516/66543725-ce738180-eb53-11e9-9064-01a42e0a352e.png)
Issue exists on master branch also.
