### ISSUE TITLE
Age and gender fields not cleared on clearing phone number.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#577]
![Clearing_phone_number](https://user-images.githubusercontent.com/54023516/65590022-b292ac00-dfa7-11e9-9e8b-bf3d84760dc9.png)
On clearing the phone number field all the other fields should be cleared,but the age and the gender fields do not get cleared.

**Comment by shivam-kurtarkar** [comment]
since phone number is updatable. its not a bug

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66542001-ded52d80-eb4e-11e9-8d1c-d091bc8a4539.png)
 issue exists on master branch also.
