### ISSUE TITLE
PO line item table not updated

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#589]
![po_line_item_table](https://user-images.githubusercontent.com/54023516/65678608-3cf31280-e071-11e9-85cc-e6ffbd15da2e.png)

PO line item table is not updated when a purchase is made.

**Comment by shivam-kurtarkar** [comment]
po_line_item table is not used

**Comment by larissa-c-d** [comment]
po_line_item table not related to the task
