### ISSUE TITLE
Error message is displayed when item level flat dicount on MRP offer is applied

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#59]
Go to http://aqua61.healthkartqa.com/admin/pos/POS.action
Variant ID: NUT5282-01 Flash sale is on 50%
FEFO enbled: 60%

MuscleBlaze Whey Gold Protein, 4.4 lb Rich Milk Chocolate (
scan barcode: IVM-387-1197
Old MRP: 5999
new MRP: 6399

Apply Offer: ITEM LEVEL DISCOUNT FLAT ONMRP 471 and Observe
Offer MRP: 471ruppees

Actual result: " Item level offer cannot be applied to some of the item(s) in your cart!"  Error message is displayed when item level flat dicount on MRP offer is applied

![image](https://user-images.githubusercontent.com/14803102/46282457-2e256d00-c58f-11e8-9e85-bd34f01b10ae.png)

**Comment by sharangsamonkar** [comment]
Could not replicate. Offer is successfully applied. Please check.
![screen shot 2018-10-03 at 2 08 40 pm](https://user-images.githubusercontent.com/29853994/46399659-fb59b100-c715-11e8-9dd4-d2eaa620e0fa.png)

**Comment by rohan-morje** [comment]
Not an issue
