### ISSUE TITLE
option to select a carry bag not displayed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#590]
![image](https://user-images.githubusercontent.com/54023516/65681620-ebe61d00-e076-11e9-8c4b-9f4585b0a93c.png)

option to select a carry bag not available.

**Comment by shivam-kurtarkar** [comment]
system issue

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66540449-7b94cc80-eb49-11e9-9e2a-e1026fd92887.png)
Issue exists on master branch also.
