### ISSUE TITLE
The city field should be uneditable.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#592]
![image](https://user-images.githubusercontent.com/54023516/65688831-61f37f80-e089-11e9-971a-dc8b17596d4d.png)

 The city field should be editable as the city is auto populated on entering the pincode.

**Comment by shivam-kurtarkar** [comment]
probably not a bug

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66540347-2658bb00-eb49-11e9-8873-971b5b1f9bf3.png)
Issue exists on master branch also.
