### ISSUE TITLE
Error message not displayed if the payment reference number is not in the correct range of digits.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#594]
![image](https://user-images.githubusercontent.com/54023516/65688930-90715a80-e089-11e9-85a4-6614b7fb9371.png)

Error message is not displayed if the Payment Reference No. is not in the correct range of digits.

**Comment by shivam-kurtarkar** [comment]
no validation present

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66542190-85213300-eb4f-11e9-860e-65243deeb155.png)
Issue exist on master branch also.
