### ISSUE TITLE
Takes alphabet as input for payment reference number.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#596]
![payment_reference_number](https://user-images.githubusercontent.com/54023516/65689866-83556b00-e08b-11e9-8fcd-faee210c4559.png)

![payment_refernce_number_2](https://user-images.githubusercontent.com/54023516/65690018-c4e61600-e08b-11e9-8f64-0fa311b72fea.png)

Takes alphabet for payment reference number.

**Comment by shivam-kurtarkar** [comment]
system issue

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66539979-d6c5bf80-eb47-11e9-8b63-7f9c515f77b5.png)
Issue present on master branch also.
