### ISSUE TITLE
Offers are not displaying when one barcode scanned has FEFO Discount Applied and for other barcode Flash Discount Applied

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#60]
Go to http://aqua61.healthkartqa.com/admin/pos/POS.action
Variant ID: NUT5282-01 Flash sale is on 50%
FEFO enbled: 60%
Flash discount : 50 %

MuscleBlaze Whey Gold Protein, 4.4 lb Rich Milk Chocolate (
scan barcode: IVM-387-1290 - expiry 2018-10-30
barcode: IVM-405-46250 - expiry: 2020-01-28

Actual result: Offers are not displaying when one barcode scanned has FEFO Discount Applied and for other barcode Flash Discount Applied
ref screenshot

![image](https://user-images.githubusercontent.com/14803102/46283097-0d5e1700-c591-11e8-99a1-7a6f649f6c0c.png)

**Comment by sharangsamonkar** [comment]
Validation of pos is done. This checks if all pos line items have the same discount applied or not. If validation fails no offers are shown.

Not an issue.
