### ISSUE TITLE
Search BO page Gives Error.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#600]
![BO_Error](https://user-images.githubusercontent.com/54023516/65748481-a9c5e580-e121-11e9-8e6b-f8573eb85f7d.png)

BO Page gives error when id BO id or nay of the fields are entered and search button is clicked.

**Comment by shivam-kurtarkar** [comment]
changing mysql mode fixes issue
[mysqld]
sql_mode = STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66459734-3910b880-ea93-11e9-8a4c-47b42d214497.png)
BO page does not give error.
