### ISSUE TITLE
Data in the row not cleared when the item is reverted.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#618]
![row_not_cleared_when_item_is_reverted](https://user-images.githubusercontent.com/54023516/66454727-43788580-ea86-11e9-8cbf-aad4e863bfc1.png)

Data in the row not cleared when the item is reverted,when clicked on stock transfer info.

**Comment by shivam-kurtarkar** [comment]
not a bug.  quantity tells its been reverted. Since the item was checked out to keep a track of it its been showed

**Comment by larissa-c-d** [comment]
The item that is reverted is in checked in state

**Comment by larissa-c-d** [comment]
Data displayed for record purpose.
