### ISSUE TITLE
stock transfer with reverted items can be sent to destination warehouse and can be approved at the destination warehouse.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#620]
![image](https://user-images.githubusercontent.com/54023516/66457884-fe0c8600-ea8e-11e9-9ca4-786517191354.png)

![image](https://user-images.githubusercontent.com/54023516/66457962-32804200-ea8f-11e9-832a-b1c324fe101b.png)

stock transfer with reverted items can be sent to destination warehouse and can be approved at the destination warehouse.

**Comment by shivam-kurtarkar** [comment]
system related : handling of empty cart

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66545276-f1a03000-eb57-11e9-9b7f-196b19105efe.png)
issue exist on the master branch also.
