### ISSUE TITLE
The states dropdown does not contain the list of the states

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#621]
![image](https://user-images.githubusercontent.com/54023516/66539301-1fc84480-eb45-11e9-89ce-4562f565fd79.png)
 The states dropdown does not contain the states.

**Comment by shivam-kurtarkar** [comment]
system issue

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66542790-2f4d8a80-eb51-11e9-9361-5f87638baa63.png)
issue exists on master also.
