### ISSUE TITLE
All the results for a particular date are not shown.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#623]
![image](https://user-images.githubusercontent.com/54023516/66627854-908d6080-ec1a-11e9-8034-0e0b51db367c.png)
![image](https://user-images.githubusercontent.com/54023516/66627941-e2ce8180-ec1a-11e9-8251-867a264dc881.png)
All the results for a particular date are not shown(2019-10-10).

**Comment by shivam-kurtarkar** [comment]
changed filter from payment_date in payment table to create_dt in base_order table

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/66647534-c9dbc580-ec46-11e9-8cb3-dc97a3da0cc7.png)
 All the order's for a particular date are displayed.
