### ISSUE TITLE
Incorrect offer price is getting applied when Item level Flat discount is applied for one product variant with Fefo has 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#63]
MuscleBlaze Whey Gold Protein, 4.4 lb Rich Milk Chocolate (NUT5282-01) - Fefo enabled and HK offer false
Scan the barcode of the above variant > IVM-387-1290

Scan the barcode of different variant for which FEFO is disabled . NUT5356-01  IVM-359-26376
Apply the ITEM LEVEL DISCOUNT FLAT 521 and observe

Actual result: Incorrect Offer price is getting applied on the product variant which do not have fefo discount.  
Getting discount of 730.34 when ITEM LEVEL DISCOUNT FLAT 521 is applied

![image](https://user-images.githubusercontent.com/14803102/46291436-17414380-c5ac-11e8-8e6d-b545aa36675b.png)

**Comment by sharangsamonkar** [comment]
521 flat is never applied.

![screen shot 2018-10-03 at 4 46 37 pm](https://user-images.githubusercontent.com/29853994/46407300-0fa8a880-c72c-11e8-8a55-c727a900bde1.png)

**Comment by rohan-morje** [comment]
Issue observed on live
![image](https://user-images.githubusercontent.com/14803102/46466375-beaaba00-c7e8-11e8-9ce3-f7ecc45413dd.png)
