### ISSUE TITLE
Entries not displayed if the start and the end date is the same.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#637]
![same_start_end_date](https://user-images.githubusercontent.com/54023516/66906171-d08e8200-f024-11e9-8982-73a3ea081db7.png)

No data displayed if the start and the end date is the same.

**Comment by shivam-kurtarkar** [comment]
It would display if entry is created on  2019-09-03 exactly at 00:00:00 time
