### ISSUE TITLE
Item level flat discount on MRP 1000 rs is getting applied which is less than Flash Discount

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#64]
Fefo enabled
http://aqua61.healthkartqa.com/admin/pos/POS.action
Scan the barcode which has Flash sale enabled > IVM-387-1290
MuscleBlaze Whey Gold Protein, 4.4 lb Rich Milk Chocolate (NUT5282-01)
50% Flash Discount  is applied  
Try to add offer Item level flat discount on MRP 1000

Above offer is getting applied. 
Item level flat discount on MRP 1000 rs is getting applied which is less than Flash Discount Rs 3199

![image](https://user-images.githubusercontent.com/14803102/46363082-abd0a200-c68f-11e8-8a9a-5c7e7cd5863a.png)

 

![image](https://user-images.githubusercontent.com/14803102/46362651-82fbdd00-c68e-11e8-91e8-db2b08007ca8.png)

**Comment by sharangsamonkar** [comment]
Not an issue.

**Comment by rohan-morje** [comment]
Not an issue
