### ISSUE TITLE
1 unit left in Flash Sale but allowing to scan more than 1 unit in POS with Flash discount being applied to all the scanned units

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#65]
Flash sale is on. Only 1unit available in flash sale.
variant: NUT5282-01
Scanbarcode: IVM-405-21768 > Flash sale will be applied
IVM-405-21767 > Flash sale will be applied

Actual Result: 1 unit left in Flash Sale but allowing to scan more than 1 unit in POS with Flash discount being applied to all the scanned units

**Comment by sharangsamonkar** [comment]
That is the functionality.

**Comment by rohan-morje** [comment]
As per developer comment closingthe issue
