### ISSUE TITLE
SIS: Item level flat discount on MRP 1000 rs is getting applied which is less than Flash Discount 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#67]
http://aqua61.healthkartqa.com/admin/pos/POS.action
Scan the barcode which has Flash sale enabled > IVM-405-14920
MuscleBlaze Whey Gold Protein, 4.4 lb Rich Milk Chocolate (NUT5282-01)
50% Flash Discount is applied
**Try to add offer Item level flat discount on MRP 1000**

Above offer is getting applied.
Item level flat discount on MRP 1000 rs is getting applied which is less than Flash Discount Rs 3200

![image](https://user-images.githubusercontent.com/14803102/46396008-c47e9d80-c70b-11e8-9ba0-a65a1a91c4e5.png)

**Comment by sharangsamonkar** [comment]
Not an issue.
