### ISSUE TITLE
'Conversion applicable' checkbox not checked on the edit page when the vendor is Bright Lifecare Pvt Ltd (HK-Fulfilled) and the 'convert to nut id' is not disabled.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#672]
**Issue**
'Conversion applicable' checkbox not checked on the edit page when the vendor is Bright Lifecare Pvt Ltd (HK-Fulfilled) and the 'convert to nut id' is not disabled.

**steps**
1.Click on edit icon , for an conversion with vendor Bright Lifecare Pvt Ltd (HK-Fulfilled)  ( id=131728)
2.scroll down to the conversion enabled checkbox.
3.see the error.

**Screenshots**

![image](https://user-images.githubusercontent.com/54023516/67920823-a82d8880-fbcb-11e9-9c2a-5b79548a780c.png)

**Comment by shivam-kurtarkar** [comment]
if entry is there in the table and conversion applicable boolean is set to false then previous nut id is displayed. This is done to preserve old data. field is disabled if conversion applicable  is false

**Comment by larissa-c-d** [comment]
Testing done, Issue fixed.
