### ISSUE TITLE
Sync issue - is_conversion_applicable is changed to 1 when  in edit mode vendor is changed  from bright to any other vendor

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#707]
Edit store variant details
http://catalog61.healthkartqa.com/admin/crud/catalog/variant/StoreVariantCrud.action?createOrEditStoreVariant=&storeVariantId=13473&storeId=1
Edit the variant id - NUT1367-02
Change the vendor from Bright Lifecare Pvt Ltd to KS Healthcare and Save it

Product_variant_conversion_details table is not updated when changes are made to Store variant

![image](https://user-images.githubusercontent.com/14803102/68210597-deb83880-fffb-11e9-9d2d-9f19a53bec4c.png)
![image](https://user-images.githubusercontent.com/14803102/68210626-eb3c9100-fffb-11e9-8e20-e641dd75c10e.png)

![image](https://user-images.githubusercontent.com/14803102/68208749-dfe76680-fff7-11e9-8960-6b88b636e309.png)

![image](https://user-images.githubusercontent.com/14803102/68208710-c80fe280-fff7-11e9-9b6a-14f4bcb5cbf9.png)

**Comment by shivam-kurtarkar** [comment]
When vendor is changed from non fulfilled to fulfilled HSN status is revoked to Approval Pending. hence sync does not occur thereafter. Need to approve HSN status for sync to work.

**Comment by rohan-morje** [comment]
resolved
