### ISSUE TITLE
Email invoice content needs to be changed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#766]
**Issue**
Email invoice content needs to be changed.

**Screenshot**
![email content](https://user-images.githubusercontent.com/54023516/69407654-0d881b80-0d2b-11ea-80b9-6fbd25451e56.png)

**Comment by sharangsamonkar** [comment]
To be done once we get the proper content from HK.

@shivam-kurtarkar For now, put content that suggests it is an order invoice.

**Comment by larissa-c-d** [comment]
Email Content not updated
![image](https://user-images.githubusercontent.com/54023516/71237333-41a12d00-2327-11ea-9b2e-a588ae83b147.png)
