### ISSUE TITLE
The check box for Update Gst Reverse Pickup Invoice is auto checked.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#769]
**Issue**
The check box for Update Gst Reverse Pickup Invoice is auto checked,When te check box for send SMS/Email is checked for Update Gst Invoice and there is No Shipping order found with given id gateway order id.

**Screenshot**
![both check boxes are checked](https://user-images.githubusercontent.com/54023516/69420007-c5c1be00-0d43-11ea-8b20-da75a37300ce.png)

**Steps**
-Go to https://aqua145.healthkartqa.com/core/accounting/UpdateInvoiceUtility.action.
-Enter an Invalid gateway order id.
-Check the send SMS/Email check box for Update Gst Invoice
-Click on Generate Invoice.

![image](https://user-images.githubusercontent.com/54023516/69420385-9790ae00-0d44-11ea-8a67-26c834c3f20a.png)

**Steps**
-Go to https://aqua145.healthkartqa.com/core/accounting/UpdateInvoiceUtility.action.
-Enter an Invalid Reverse pickup order id.
-Check the send SMS/Email check box for Update Gst Reverse Pickup Invoice
-Click on Generate Invoice.

**Comment by sharangsamonkar** [comment]
When you reload both check boxes should not be checked.

**Comment by larissa-c-d** [comment]
Issue resolved
