### ISSUE TITLE
Reverse Pickup Invoice PDF details not updated.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#773]
Issue
PDF generated on the Update Invoice Utility page does not give the updated details.

Steps 
-Change the amount of the invoice from the reverse_pick_up_order table.
-Go to https://aqua145.healthkartqa.com/core/accounting/UpdateInvoiceUtility.action
-Enter the Reverse pickup order id.
-Click on Generated Invoice.

Screenshots
![reverse pdf not updated 1](https://user-images.githubusercontent.com/54023516/69533492-ec7b3100-0f9d-11ea-9d8f-5e6c7cebe051.png)
![reverse pick up invoice 2](https://user-images.githubusercontent.com/54023516/69533496-eedd8b00-0f9d-11ea-9bb4-1f8c42acd608.png)

**Comment by sharangsamonkar** [comment]
So see changes please edit the line item table.

**Comment by larissa-c-d** [comment]
Issue resolved
