### ISSUE TITLE
Total amount displayed as 0 if the Invoice is generated after creating a booking.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#774]
Issue 
Total amount displayed as 0 if the Invoice is generated after creating a booking.

Steps 
-Go to https://aqua145.healthkartqa.com/admin/order/search/SearchShippingOrder.action?searchShippingOrder=&shippingOrderGatewayId=4844478-S67707
-Click on Create Booking
-Enter the details
-Enter the reverse pick up id generated on the Update utility page
-Click on Generate Invoice

Screenshot
Booking Screen
![image](https://user-images.githubusercontent.com/54023516/69535953-05d2ac00-0fa3-11ea-9991-9026ac8579c5.png)

Invoice generated
![image](https://user-images.githubusercontent.com/54023516/69536006-200c8a00-0fa3-11ea-9c82-9b7b0f8d20ac.png)

**Comment by sharangsamonkar** [comment]
Need to place a check while generating the return invoice. Only if the checkin is done it should allow to generate else show the proper message on the utility page.

**Comment by larissa-c-d** [comment]
Issue resolved.
