### ISSUE TITLE
The column Status should be changed to Item Status.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#786]
Issue
The column Status should be changed to Item Status.

Screenshot
![table W1](https://user-images.githubusercontent.com/54023516/69849211-171d0080-12a2-11ea-89ad-c33c06c09440.png)

Steps
Go to http://localhost:8181/admin/display_items/DisplayItems.action?itemListManagement=
See the error

**Comment by legred21** [comment]
Fixed
![image](https://user-images.githubusercontent.com/55079454/69934528-29907780-14f8-11ea-98d1-aee21aac365e.png)

**Comment by larissa-c-d** [comment]
Issue resolved
