### ISSUE TITLE
warehouse dropdown should have a select all option.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#787]
Actual Results
warehouse dropdown does not have an select all option.

Expected Results
warehouse dropdown should have an select all option.

Screenshot
![warehouse all](https://user-images.githubusercontent.com/54023516/69851229-3a967a00-12a7-11ea-8f25-3bae409cf344.png)

Steps
1.Go to http://localhost:8181/admin/display_items/DisplayItems.action?itemListManagement=
2.Click on the warehouse dropdown.
3.See the error

**Comment by legred21** [comment]
Fixed
![image](https://user-images.githubusercontent.com/55079454/69934677-a3286580-14f8-11ea-91cc-aa038c5904da.png)

**Comment by larissa-c-d** [comment]
Issue resolved
