### ISSUE TITLE
status selection dropdown should have a select all option.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#793]
Actual Results
status selection dropdown does not have an select all option.

Expected Results
status selection dropdown should have a select all option.

Screenshot
![warehouse all](https://user-images.githubusercontent.com/54023516/69851229-3a967a00-12a7-11ea-8f25-3bae409cf344.png)

Steps
1.Go to http://localhost:8181/admin/display_items/DisplayItems.action?itemListManagement=
2.Click on the warehouse dropdown.
3.See the error

**Comment by legred21** [comment]
Fixed

**Comment by larissa-c-d** [comment]
Issue resolved.
