### ISSUE TITLE
Search results are not displayed if the expiry date is not set and the warehouse, product variant, and the item status filter have been applied.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#794]
Actual Results
If the warehouse,product variant and the status filter have been set and the expiry date filter is not set the results are not displayed.

Expected Result 
If the warehouse,product variant ad the status filter have been set and the expiry date filter is not set the results should be displayed on click of search.

![image](https://user-images.githubusercontent.com/54023516/69958015-e7802980-1529-11ea-9a40-5f81669c4dc3.png)

**Comment by legred21** [comment]
Fixed

**Comment by larissa-c-d** [comment]
Issue resolved
