### ISSUE TITLE
Search results are not displayed if the product variant is not set and the warehouse,item status and the expiry date filter have been applied.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#795]
Actual Results
If the warehouse, the item status and the  expiry date filter have been set and the product variant filter is not set the results are not displayed.

Expected Result 
If the warehouse, the item status and the  expiry date filter have been set and the product variant filter is not set the results should be displayed on click of search based on the applied filters.

![image](https://user-images.githubusercontent.com/54023516/69958522-029f6900-152b-11ea-9396-f7134394d4c0.png)

**Comment by legred21** [comment]
Fixed

**Comment by larissa-c-d** [comment]
Issue resolved
