### ISSUE TITLE
The barcodes to expire first not displayed on top.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#796]
Actual Result
The barcodes to expire first not displayed on top.

Expected Results
The barcodes to expire first should be displayed on top.

Steps
-Go to http://localhost:8181/admin/display_items/DisplayItems.action
-Apply the warehouse, product variant , item status filter

Screenshot
![image](https://user-images.githubusercontent.com/54023516/70031400-303eed80-15d1-11ea-84c1-d6b9561fd7d0.png)

**Comment by legred21** [comment]
Fixed

**Comment by larissa-c-d** [comment]
![12⁄16⁄1913:11:00](https://user-images.githubusercontent.com/54023516/70888125-9120e980-2005-11ea-86db-dd64731c91eb.png)

**Comment by legred21** [comment]
Fixed
![image](https://user-images.githubusercontent.com/55079454/70892191-aa7a6380-200e-11ea-95b9-a28cf2e8e7b1.png)
