### ISSUE TITLE
Results are not filtered based on the expiry date.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#797]
Actual results
Results are not sorted according to the expiry date.

Expected results
Results should be sorted according to the expiry date

Screenshot
Results Before application of the expiry filter.
![image](https://user-images.githubusercontent.com/54023516/70030581-86129600-15cf-11ea-8bcf-2a6f6108f900.png)

Results After application of the expiry filter.
![image](https://user-images.githubusercontent.com/54023516/70030764-e73a6980-15cf-11ea-8d26-57de251f93d3.png)

**Comment by legred21** [comment]
fixed

**Comment by larissa-c-d** [comment]
Expected result
Only the barcodes for the date specified in the filter should be dislayed.

![12⁄16⁄1913:06:37](https://user-images.githubusercontent.com/54023516/70887892-00e2a480-2005-11ea-980c-6827fbe465a8.png)

**Comment by legred21** [comment]
Fixed
![image](https://user-images.githubusercontent.com/55079454/70891541-6dfa3800-200d-11ea-9325-7fa40820fb30.png)
