### ISSUE TITLE
Sufficient Inventory available message is displayed on click of CHECK INVENTORY when sufficient inventory is not available

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#802]
IP ID 3726
Variant : NUT1367-41  HYD Himayat nagar, BLR JP nagar 
Source Inventory: 20     Minimum Inventory to Refill: 200
HYD Himayat nagar  - 12
BLR JP nagar             - 10

Create the Inventory Planner 
Click on CHECK INVENTORY button and Observe

Actual Result: **Sufficient Inventory available** message is displayed on click of CHECK INVENTORY when sufficient inventory is not available 

![image](https://user-images.githubusercontent.com/14803102/70115828-ed3f5180-1686-11ea-9165-df299a92d938.png)
![image](https://user-images.githubusercontent.com/14803102/70116191-f7ae1b00-1687-11ea-92e2-022627f81207.png)

![image](https://user-images.githubusercontent.com/14803102/70115997-748cc500-1687-11ea-867e-27bb8235a1ca.png)

**Comment by sharangsamonkar** [comment]
Is this present on master as well?

**Comment by rohan-morje** [comment]
No.. on master there is different message
145
Following message is displayed on click of Check Inventory button
Sufficient inventory not available. Please update Actual Dispatch values for the following.
Variant ID | Warehouse Name | Expected Qty | Available Qty
-- | -- | -- | --
NUT1367-34 | Bhiwandi Bright CFA 2.0 | 200 | 155


![image](https://user-images.githubusercontent.com/14803102/70130175-158a7880-16a6-11ea-99b4-ba9e5e128f57.png)

**Comment by rohan-morje** [comment]
ISSUE RESOLVED
