### ISSUE TITLE
ST count displaying is Not correct after approving the ST (gateway timeout error )

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#810]
IP 3730
Minimum Inv to refill - 5
Src Inventory: 20
NUT1367-41
HYD Himayat Nagar Actual dispatch: 20
BLR JP Nagar Actual Dispatch : 15

Submit the IP for approval and approve the IP - 

Actual result: ST count displaying is Not correct after approving the ST (gateway timeout error )

2 ST are created but ST count showing as 4

![image](https://user-images.githubusercontent.com/14803102/70123794-68a9fe80-1699-11ea-90fb-350bde2fef97.png)

**Comment by Shraddhar23** [comment]
![Screenshot 2019-12-05 at 12 08 14 PM](https://user-images.githubusercontent.com/48199171/70210136-ef251580-1757-11ea-935a-d99f4415527e.png)

**Comment by rohan-morje** [comment]
ISSUE RESOLVED
