### ISSUE TITLE
Gateway Timeout error when approving the IP after clicking on Check Inventory

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#812]
NUT1367-34
Minimum Inventory to refill 5
Source Inventory 70
HYD Himayat Nagar  Actual dispatch - 50
BLR JP Nagar   Actual Disptch 30 

Create the IP -> Click on Check Inventory button -> Submit for Approval 
Click on Approve button and observe

Actual result: gateway Timeout pop up is displaying when approving

ON Master:  when clicked on Approve button 
Source inventory: 155   NUT1367-34    ip 3341
![image](https://user-images.githubusercontent.com/14803102/70134653-86ce2980-16ae-11ea-997a-00ad8b9233be.png)

**Comment by Shraddhar23** [comment]
![Screenshot 2019-12-05 at 12 06 19 PM](https://user-images.githubusercontent.com/48199171/70210038-b08f5b00-1757-11ea-8a4f-5f74698c8182.png)
