### ISSUE TITLE
Gateway Timeout error when approving the IP after clicking on Distribute and Skip button

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#814]
NUT1367-34
Minimum Inventory to refill 5
Source Inventory 70
HYD Himayat Nagar Actual dispatch - 55
BLR JP Nagar Actual Dispatch 30

Create the IP -> Click on DISTRIBUTE & SKIP button-> Submit for Approval
Click on Approve button and observe

Actual result: Gateway Timeout error when approving the IP and when page is refshed IP is in approved state

![image](https://user-images.githubusercontent.com/14803102/70136381-e67a0400-16b1-11ea-92cc-29a656974822.png)

![image](https://user-images.githubusercontent.com/14803102/70136299-bc284680-16b1-11ea-9f7e-20a9564c00b9.png)

On Master IP is getting created successfully

**Comment by Shraddhar23** [comment]
![Screenshot 2019-12-05 at 12 25 52 PM](https://user-images.githubusercontent.com/48199171/70211138-665ba900-175a-11ea-8b76-3f3736cde67b.png)

**Comment by rohan-morje** [comment]
iSSUE RESOLVED
