### ISSUE TITLE
There was some error while approving after clicking on Check Inventory

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#815]
NUT1367-34
Minimum Inventory to refill 5
Source Inventory 70
HYD Himayat Nagar Actual dispatch - 50
BLR JP Nagar Actual Disptch 30

Create the IP -> Click on Check Inventory button -> Submit for Approval
Click on Approve button and observe

Actual result: There was some error while approving after clicking on Check Inventory

![image](https://user-images.githubusercontent.com/14803102/70137767-ba13b700-16b4-11ea-83c0-ba007048791f.png)
![image](https://user-images.githubusercontent.com/14803102/70137829-e0395700-16b4-11ea-8fa9-06ec2ca28c6b.png)
![image](https://user-images.githubusercontent.com/14803102/70137903-137be600-16b5-11ea-8b8a-1beee675a8ab.png)

On master
![image](https://user-images.githubusercontent.com/14803102/70137784-c6980f80-16b4-11ea-92fb-0426d93a1e0c.png)
![image](https://user-images.githubusercontent.com/14803102/70137841-ecbdaf80-16b4-11ea-833d-5629f5eb23c5.png)

same issue on master

**Comment by Shraddhar23** [comment]
![Screenshot 2019-12-05 at 10 17 31 AM](https://user-images.githubusercontent.com/48199171/70205003-9bf79680-1748-11ea-913b-f191a90de268.png)

**Comment by rohan-morje** [comment]
There was some error while approving : Inventory Planner cannot be approved as there is no ST data.  message is displayed. 
Issue resolved
