### ISSUE TITLE
email field not auto populated on entering the phone number.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#837]
Actual results
email field not auto populated on entering the phone number.
![image](https://user-images.githubusercontent.com/54023516/70494747-86acae80-1b32-11ea-9d45-b486d7422472.png)

**Comment by rohan-morje** [comment]
Email id from catalog-users table will fetch . If email id is null in catalog than it will fetch from aqua-user table. If email id is null on aqua, than email id from user_detail table will be fetched
