### ISSUE TITLE
Success/Error message is not displayed for Update Gst Reverse Pickup Invoice.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#858]
Actual Result
Success/Error message is not displayed for Update Gst Reverse Pickup Invoice.

Expected Result
Success/Error message should be displayed for Update Gst Reverse Pickup Invoice.

![image](https://user-images.githubusercontent.com/54023516/70613242-4fbbc300-1c2e-11ea-908e-ab9cba7d8233.png)
![image](https://user-images.githubusercontent.com/54023516/70613274-5e09df00-1c2e-11ea-9b34-42207217b25a.png)

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/70691417-1000e400-1cdf-11ea-8bd2-8110a4ba4ae4.png)

**Comment by sharangsamonkar** [comment]
SMS / Email not present in the email.

**Comment by larissa-c-d** [comment]
Issue resolved
