### ISSUE TITLE
Email not received for  Update Gst Reverse Pickup Invoice.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#859]
![image](https://user-images.githubusercontent.com/54023516/70613532-ce186500-1c2e-11ea-8a23-8bff49ae0e8e.png)
![image](https://user-images.githubusercontent.com/54023516/70613567-e1c3cb80-1c2e-11ea-9ab9-062e48e0eb66.png)
![image](https://user-images.githubusercontent.com/54023516/70613615-f56f3200-1c2e-11ea-91b8-2692090c4bff.png)

**Comment by sharangsamonkar** [comment]
Looks like its because the email is null in the user table. Please check.

**Comment by larissa-c-d** [comment]
issue resolved
