### ISSUE TITLE
Minimum inventory value field not accepting NA value

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#86]
Go to http://bright61.healthkartqa.com/admin/inventory/MinimumInventoryConfig.action
Minimum Inventory Configuration > Filter the product  variant  > Click on View/Edit Range link and try to enter Minimum Inventory Quantity value as NA

Actual Result: Minimum inventory value field not accepting **NA value**

![image](https://user-images.githubusercontent.com/14803102/47294646-5272e780-d62b-11e8-92ba-4796129a2529.png)

**Comment by ambksud** [comment]
Issue Fixed
