### ISSUE TITLE
Email and sms received on click of Close and mark RP as completed, when the send sms/email flag is false.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#860]
Actual Result
Email and sms received on click of Close and mark RP as completed, when the send sms/email flag is false.

Expected result
Email and sms should not be received on click of Close and mark RP as completed, when the send sms/email flag is false.

![image](https://user-images.githubusercontent.com/54023516/70618937-f48fcd80-1c39-11ea-866b-947fdf80e918.png)
![image](https://user-images.githubusercontent.com/54023516/70618960-01142600-1c3a-11ea-95cd-dccc3d9b0cf3.png)
![image](https://user-images.githubusercontent.com/54023516/70618999-1be69a80-1c3a-11ea-8f42-f33733b1f872.png)

**Comment by sharangsamonkar** [comment]
1. Flag of the store that placed and returned the order should be checked.
2. Flag for sendReturnInvoiceSMSEmail in global_defaults table.

**Comment by larissa-c-d** [comment]
[ INFO] [] [http-nio-8181-exec-7] (13 Dec 2019 12:33:33) (GSTInvoiceServiceImpl.java:460) - Ajency.in :: uploading to s3 with file key: gstReturnInvoicePDF/2019/Dec/SO_5924997_1576220613794.pdf
[ INFO] [] [http-nio-8181-exec-7] (13 Dec 2019 12:33:37) (GSTInvoiceServiceImpl.java:473) - Ajency.in :: saved to SOGSTReturnInvoiceHistory table , id:45
[ INFO] [] [http-nio-8181-exec-7] (13 Dec 2019 12:33:37) (RPWarehouseCheckinAction.java:286) - Ajency.in :: reverse pick up id155823 sendReturnInvoiceEmailSMS true loggedInStore.sendSmsEmailInvoice:true
[ INFO] [] [http-nio-8181-exec-7] (13 Dec 2019 12:33:37) (GSTInvoiceServiceImpl.java:612) - Ajency.in :: url for return invoice: http://aqua61.healthkartqa.com/core/accounting/GSTInvoiceDownload.action?customerReturnInvoiceAsPdf=&reversePickupOrderId=35361-RP5924997&user=CwqwNarWyUa8SXHKJRhHAA%253D%253D
[ INFO] [] [http-nio-8181-exec-7] (13 Dec 2019 12:33:37) (GSTInvoiceServiceImpl.java:527) - Ajency.in :: sending email to email address : larissa@ajency.in
[ INFO] [] [http-nio-8181-exec-7] (13 Dec 2019 12:33:37) (GSTInvoiceServiceImpl.java:542) - Ajency.in :: sending sms to mobile no: 9552519582
[ INFO] [] [http-nio-8181-exec-7] (13 Dec 2019 12:33:37) (GSTInvoiceServiceImpl.java:552) - Ajency.in :: making jarvis call for sending sms to the customer [8052] no:9552519582
[ INFO] [] [http-nio-8181-exec-7] (13 Dec 2019 12:33:37) (MailBoltServiceImpl.java:34) - Send sms url http://192.168.70.133:4040/sms/send/transactional?z.ts==1576220617155&st=1
[ INFO] [] [pool-24-thread-1] (13 Dec 2019 12:34:00) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (13 Dec 2019 12:34:00) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false



![image](https://user-images.githubusercontent.com/54023516/70777400-b1eb0400-1da5-11ea-9cdb-ebf458aee531.png)
![image](https://user-images.githubusercontent.com/54023516/70777422-c0392000-1da5-11ea-83a9-f4595f7f16ad.png)
![image](https://user-images.githubusercontent.com/54023516/70777454-db0b9480-1da5-11ea-8736-233b264d4655.png)
![image](https://user-images.githubusercontent.com/54023516/70777489-f1195500-1da5-11ea-876c-5484bf9712a1.png)

**Comment by larissa-c-d** [comment]
issue resolved
