### ISSUE TITLE
Exception is displayed in the log when the email id is not stored in the database and return invoice is generated.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#861]
![image](https://user-images.githubusercontent.com/54023516/70619679-83e9b080-1c3b-11ea-85a8-8b3ecf8a4149.png)
![image](https://user-images.githubusercontent.com/54023516/70619726-9e238e80-1c3b-11ea-896f-2128d2e841ed.png)

**Comment by shivam-kurtarkar** [comment]
@larissa-c-d  pls put logs in code tags instead of photos

**Comment by shivam-kurtarkar** [comment]
added empty string check
