### ISSUE TITLE
Invoice link is cleared if the error message is displayed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#865]
Access an unauthorised invoice.
Click the back icon when the error is displayed.

![image](https://user-images.githubusercontent.com/54023516/70682423-d7eca780-1cc4-11ea-950c-42d074f40bea.png)

**Comment by shivam-kurtarkar** [comment]
since its redirected you cant go back. but we can provide a button with the link to retry @sharangsamonkar

**Comment by sharangsamonkar** [comment]
Proper behaviour.
