### ISSUE TITLE
Value selected in Brand name and Product variant id field is not cleared when Zone is changed

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#87]
Go to http://bright61.healthkartqa.com/admin/inventory/MinimumInventoryConfig.action
Minimum Inventory Configuration >
Go to Zone tab > Select zone eg: North ,  Select Brand Name and Product variant id  and click on Apply Filter button > Data will load 
Now change the Zone to south and Observe

Actual result: Value selected in Brand name and Product variant id field is not cleared when Zone is changed

**Comment by sharangsamonkar** [comment]
not an issue

**Comment by ambksud** [comment]
Not an Issue
