### ISSUE TITLE
[ERROR] [] [http-nio-8181-exec-3] (12 Dec 2019 12:55:42) (GSTInvoiceServiceImpl.java:482) -   is displayed even when the data is successfully entered in the table.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#870]
[ INFO] [] [http-nio-8181-exec-3] (12 Dec 2019 12:55:36) (GSTInvoiceServiceImpl.java:469) - Ajency.in :: uploading to s3 with file key: gstReturnInvoicePDF/2019/Dec/SO_4844465_1576135536940.pdf
 [ERROR] [] [http-nio-8181-exec-3] (12 Dec 2019 12:55:42) (GSTInvoiceServiceImpl.java:482) - Ajency.in :: saved to SOGSTReturnInvoiceHistory table , id:15 
[ INFO] [] [http-nio-8181-exec-3] (12 Dec 2019 12:55:42) (UpdateInvoiceUtilityAction.java:132) - Ajency.in :: send sms email: true
[ INFO] [] [http-nio-8181-exec-3] (12 Dec 2019 12:55:42) (UpdateInvoiceUtilityAction.java:140) - Ajency.in :: sending link to customer false from store 4034 warehouse 4034
[ INFO] [] [http-nio-8181-exec-3] (12 Dec 2019 12:55:42) (UpdateInvoiceUtilityAction.java:51) - Ajency.in :: logged in store 4034 send sms /email flag: false
[ INFO] [] [pool-24-thread-1] (12 Dec 2019 12:56:20) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (12 Dec 2019 12:56:20) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false

**Comment by shivam-kurtarkar** [comment]
logger is meant to be shown shown every time entry is made successfully

**Comment by sharangsamonkar** [comment]
Change the log level to info

**Comment by larissa-c-d** [comment]
`[ INFO] [] [http-nio-8181-exec-9] (13 Dec 2019 09:37:00) (GSTInvoiceServiceImpl.java:401) - Ajency.in :: new pdf created : /usr/local/projects/tomcat_aqua_new/webapps/ROOT/gstInvoicePDF/SO_5924990_1576210019350.pdf
[ INFO] [] [http-nio-8181-exec-9] (13 Dec 2019 09:37:00) (GSTInvoiceServiceImpl.java:429) - Ajency.in :: uploading to s3 with file key: gstInvoicePDF/2019/Dec/SO_5924990_1576210019350.pdf
[ERROR] [] [http-nio-8181-exec-9] (13 Dec 2019 09:37:05) (GSTInvoiceServiceImpl.java:442) - Ajency.in :: saved to sogstInvoiceHistory table , id:74
[ INFO] [] [http-nio-8181-exec-9] (13 Dec 2019 09:37:05) (POSAction.java:3245) - Ajency.in :: sending link to customer false from store 4034
[ INFO] [] [http-nio-8181-exec-9] (13 Dec 2019 09:37:05) (GSTInvoiceServiceImpl.java:581) - Ajency.in :: user login : MOB_8B4abY1575872303978
[ INFO] [] [http-nio-8181-exec-9] (13 Dec 2019 09:37:05) (GSTInvoiceServiceImpl.java:590) - Ajency.in :: customer invoice url : http://aqua61.healthkartqa.com/core/accounting/GSTInvoiceDownload.action?customerInvoiceAsPdf=&gatewayOrderId=5924990-S61490&user=CwqwNarWyUa8SXHKJRhHAA%253D%253D
[ INFO] [] [pool-24-thread-1] (13 Dec 2019 09:39:00) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (13 Dec 2019 09:39:00) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false

`
![error logger](https://user-images.githubusercontent.com/54023516/70768762-a50de680-1d8c-11ea-9e53-8c2b979e7e74.png)

**Comment by larissa-c-d** [comment]
Issue resolved for return invoice but still exists for so_gst_invoice, issue raised #877
