### ISSUE TITLE
HTTP Status 500 – Internal Server Error is displayed when the path is removed from the link.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#872]
![image](https://user-images.githubusercontent.com/54023516/70697882-5f014600-1cec-11ea-8cec-07398436a0ab.png)

**Comment by shivam-kurtarkar** [comment]
@sharangsamonkar

**Comment by larissa-c-d** [comment]
The other links behave the same.should be handled globally.
