### ISSUE TITLE
Send SMS/Email is false for 4034:MUM Mahavir Nagar message is not correct 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#879]
" Send SMS/Email is false for 4034:MUM Mahavir Nagar message is not correct " Message displayed is not correct when Send Invoice link through S M S/ E M A I L chechbox is disabled for the reverse

Send Invoice link through S M S/ E M A I L is disbaled

\Return Invoice": 64711-RP59249934
Go to Invoice Utility page and generate the invoice and observe

Expcted: Send SMS/Email is disabled for MUM Mahavir Nagar

![image](https://user-images.githubusercontent.com/14803102/70773762-55381b00-1d9e-11ea-87cc-36ac0d32fb89.png)

**Comment by larissa-c-d** [comment]
issue resolved
