### ISSUE TITLE
Minimum inventory value accepting value greater than 1000

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#88]
Go to http://bright61.healthkartqa.com/admin/inventory/MinimumInventoryConfig.action
Minimum Inventory Configuration > Filter the product variant > Click on View/Edit Range link and try to enter Minimum Inventory Quantity value as NA

Actual result: Minimum inventory value accepting value greater than 1000

Expected result: Minimum inventory value should not accept value greater than 1000

![image](https://user-images.githubusercontent.com/14803102/47295170-a6ca9700-d62c-11e8-972c-db616c46028a.png)

**Comment by ambksud** [comment]
Issue Resolved
