### ISSUE TITLE
Null pointer exception when invalid data is entered SO gateway order id field while generating invoice

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#880]
Go to Update Invoice Utility page
Enter the invalid data in SO Gateway Order Id textbox and click on Generate Invoice button

Actual : Null pointer exception was obseerved

![image](https://user-images.githubusercontent.com/14803102/70774282-c3c9a880-1d9f-11ea-903b-304ac21bc468.png)

**Comment by larissa-c-d** [comment]
Issue resolved
