### ISSUE TITLE
Expiry date field is auto populated on navigating to the other results pages from the first page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#886]
Actual result
Expiry date field is auto populated on navigating to the other results pages from the first page.

Expected result
Expiry date filter should not get auto populated when clicked on any of the result page.

![image](https://user-images.githubusercontent.com/54023516/70888459-64210680-2006-11ea-9dc4-d371fdf8b44b.png)
![image](https://user-images.githubusercontent.com/54023516/70888492-79963080-2006-11ea-8c0e-bccd4b22e767.png)

**Comment by legred21** [comment]
fixed
![image](https://user-images.githubusercontent.com/55079454/70892686-a3a02080-200f-11ea-807c-aae5b0760e0f.png)

![image](https://user-images.githubusercontent.com/55079454/70892621-88cdac00-200f-11ea-8cd2-e2cb54c520a0.png)

**Comment by larissa-c-d** [comment]
Issue resolved
