### ISSUE TITLE
Error displayed on click of save an create stock transfer button

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#887]
`HTTP Status 500 – Internal Server Error
Type Exception Report

Message Unhandled exception in exception handler.

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

net.sourceforge.stripes.exception.StripesServletException: Unhandled exception in exception handler.
	net.sourceforge.stripes.exception.DefaultExceptionHandler.handle(DefaultExceptionHandler.java:160)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:250)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:142)
	com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
Root Cause

org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:80)
	org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:91)
	org.hibernate.loader.Loader.getResultSet(Loader.java:2066)
	org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1863)
	org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1839)
	org.hibernate.loader.Loader.doQuery(Loader.java:910)
	org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
	org.hibernate.loader.Loader.doList(Loader.java:2554)
	org.hibernate.loader.Loader.doList(Loader.java:2540)
	org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
	org.hibernate.loader.Loader.list(Loader.java:2365)
	org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:497)
	org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
	org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:236)
	org.hibernate.internal.SessionImpl.list(SessionImpl.java:1300)
	org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
	com.hk.admin.impl.dao.inventory.StockTransferDaoImpl.getStockTransferInformation(StockTransferDaoImpl.java:298)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	com.sun.proxy.$Proxy123.getStockTransferInformation(Unknown Source)
	com.hk.web.action.admin.inventory.StockTransferAction.createSplitStockTransfers(StockTransferAction.java:1990)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:142)
	com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
Root Cause

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'aqua_prod.stock_transfer_information' doesn't exist
	sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	com.mysql.jdbc.Util.getInstance(Util.java:381)
	com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
	com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3558)
	com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3490)
	com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
	com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109)
	com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2648)
	com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2077)
	com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2228)
	org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:82)
	org.hibernate.loader.Loader.getResultSet(Loader.java:2066)
	org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1863)
	org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1839)
	org.hibernate.loader.Loader.doQuery(Loader.java:910)
	org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
	org.hibernate.loader.Loader.doList(Loader.java:2554)
	org.hibernate.loader.Loader.doList(Loader.java:2540)
	org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
	org.hibernate.loader.Loader.list(Loader.java:2365)
	org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:497)
	org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
	org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:236)
	org.hibernate.internal.SessionImpl.list(SessionImpl.java:1300)
	org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
	com.hk.admin.impl.dao.inventory.StockTransferDaoImpl.getStockTransferInformation(StockTransferDaoImpl.java:298)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	com.sun.proxy.$Proxy123.getStockTransferInformation(Unknown Source)
	com.hk.web.action.admin.inventory.StockTransferAction.createSplitStockTransfers(StockTransferAction.java:1990)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:142)
	com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/8.5.24`

**Comment by legred21** [comment]
fixed

**Comment by larissa-c-d** [comment]
issue resolved
