### ISSUE TITLE
View details should be renamed to ST Info on the Stock transfer list page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#888]
Expected result
View details should be renamed to ST Info on the Stock transfer list page.

![image](https://user-images.githubusercontent.com/54023516/70906670-ecb29d80-202c-11ea-8cc0-6df2ede8149a.png)

Steps 
Create a stock transfer.
check the stock transfer list table.

**Comment by legred21** [comment]
Fixed

**Comment by larissa-c-d** [comment]
Issue resolved.
