### ISSUE TITLE
Page hangs when all the product variants are selected

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#89]
Go to http://bright61.healthkartqa.com/admin/inventory/MinimumInventoryConfig.action
Minimum Inventory Configuration >
Go to Global tab >  click on Select All link to select all the brands and Observe

Actual Result: Page hangs when all the product variants are selected by clicking on Select All link

**Comment by ambksud** [comment]
Issue Resolved
