### ISSUE TITLE
Null pointer exception when opening link https://aqua137.healthkartqa.com/admin/rtv/ExtraInventory.action with the permission PO_MANAGEMENT

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#893]
https://aqua137.healthkartqa.com/admin/rtv/ExtraInventory.action with the permission PO_MANAGEMENT

![image](https://user-images.githubusercontent.com/14803102/70970847-7d3cbc80-20c5-11ea-9f7b-05589405136a.png)

**Comment by Shraddhar23** [comment]
The line at which a Null Pointer is thrown is commented in the code.

**Comment by rohan-morje** [comment]
master same issue
