### ISSUE TITLE
Null pointer exception when clicked on Invoice link in ST lisiting page

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#894]
https://aqua137.healthkartqa.com/admin/inventory/StockTransfer.action
https://aqua137.healthkartqa.com/admin/inventory/StockTransfer.action?downloadGstInvoice=&stockTransfer=85914

![image](https://user-images.githubusercontent.com/14803102/70972016-68155d00-20c8-11ea-97af-1304bae58f85.png)

**Comment by Shraddhar23** [comment]
Invoice Link uses "distpath" property of the environment file and not adminDownloads/adminUploads.
