### ISSUE TITLE
File not downloading when clicked on Download NPL Barcode button 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#896]
https://aqua137.healthkartqa.com/admin/store/ABRetailMovement.action

**Comment by Shraddhar23** [comment]
File does get downloaded.

![Screenshot 2019-12-20 at 9 54 38 AM](https://user-images.githubusercontent.com/48199171/71230229-cfbce980-230e-11ea-867d-d72b69c4acc9.png)

**Comment by rohan-morje** [comment]
File not getting dwnloade for following button:
Download Shipping Order PL barcode
Download RV PL barcode
Download Return Purchase Order Barcode

**Comment by Shraddhar23** [comment]
Download Shipping Order PL barcode

WH : AMG CG Road

SELECT DISTINCT si.barcode AS barcode, w.identifier AS storeName,pv.id AS nutId, psm.shipping_order_id AS shippingOrderId, psm.source_warehouse_name AS sourceWarehouse FROM (SELECT MAX(pvi.id) AS id FROM sku_item si INNER JOIN product_variant_inventory pvi ON pvi.sku_item_id = si.id WHERE si.sku_item_status_id = 10 AND pvi.qty = +1 GROUP BY si.id) AS pvid INNER JOIN product_variant_inventory pvi ON pvid.id = pvi.id INNER JOIN sku_item si ON pvi.sku_item_id = si.id INNER JOIN sku_group sg ON si.sku_group_id = sg.id INNER JOIN sku s ON sg.sku_id = s.id INNER JOIN product_variant pv ON s.product_variant_id = pv.id INNER JOIN product p ON pv.product_id = p.id LEFT JOIN po_so_mapping psm ON psm.barcode = si.barcode INNER JOIN warehouse w ON s.warehouse_id = w.id WHERE s.warehouse_id = 4151 AND pvi.grn_line_item_id IS NOT NULL AND p.brand IN ('HK', 'HealthKart', 'Incredio', 'Healthviva','MuscleBlaze','Nouriza','TrueBasics','TheProteinZone','Gritzo');

File gets downloaded along with folder creation.


Download RV PL barcode


SELECT DISTINCT si.barcode FROM (SELECT MAX(pvi.id) AS id FROM sku_item si INNER JOIN product_variant_inventory pvi ON pvi.sku_item_id = si.id WHERE si.sku_item_status_id = 10 AND pvi.qty = +1 GROUP BY si.id) AS pvid INNER JOIN product_variant_inventory pvi ON pvid.id = pvi.id INNER JOIN stock_transfer_line_item stli ON pvi.stock_transfer_line_item_id = stli.id INNER JOIN stock_transfer stn ON stli.stock_transfer_id = stn.id INNER JOIN warehouse fw ON stn.from_warehouse_id = fw.id INNER JOIN sku_item si ON pvi.sku_item_id = si.id INNER JOIN sku_group sg ON si.sku_group_id = sg.id INNER JOIN sku s ON sg.sku_id = s.id INNER JOIN product_variant pv ON s.product_variant_id = pv.id INNER JOIN product p ON pv.product_id = p.id INNER JOIN warehouse w ON s.warehouse_id = w.id WHERE s.warehouse_id = 4033 AND pvi.stock_transfer_line_item_id IS NOT NULL AND p.brand IN ('HK', 'HealthKart', 'Incredio', 'Healthviva','MuscleBlaze','Nouriza','TrueBasics','TheProteinZone','Gritzo');



SELECT po.bright_so_gateway_id AS shippingOrderId, sbwm.bright_warehouse_identifier AS sourceWarehouse FROM (SELECT MAX(pvi.id) AS id FROM sku_item si INNER JOIN product_variant_inventory pvi ON pvi.sku_item_id = si.id WHERE si.barcode = 'IVM-455-281818' AND pvi.grn_line_item_id IS NOT NULL) AS pvid INNER JOIN product_variant_inventory pvi ON pvi.id = pvid.id INNER JOIN grn_line_item gli ON pvi.grn_line_item_id = gli.id INNER JOIN goods_received_note grn ON gli.goods_received_note_id = grn.id INNER JOIN purchase_order po ON grn.purchase_order_id = po.id INNER JOIN supplier_bright_warehouse_mapping sbwm ON po.supplier_id = sbwm.supplier_id; 


select shipping_order_id AS shippingOrderId, source_warehouse_name as sourceWarehouse from po_so_mapping where barcode = 'IVM-455-281818';




Download Return Purchase Order Barcode

WH : AMG CG Road

SELECT DISTINCT si.barcode AS barcode, w.identifier AS storeName,pv.id AS nutId FROM (SELECT MAX(pvi.id) AS id FROM sku_item si INNER JOIN product_variant_inventory pvi ON pvi.sku_item_id = si.id WHERE si.sku_item_status_id = 10 AND pvi.qty = +1 GROUP BY si.id) AS pvid INNER JOIN product_variant_inventory pvi ON pvid.id = pvi.id INNER JOIN sku_item si ON pvi.sku_item_id = si.id INNER JOIN sku_group sg ON si.sku_group_id = sg.id INNER JOIN sku s ON sg.sku_id = s.id INNER JOIN product_variant pv ON s.product_variant_id = pv.id INNER JOIN product p ON pv.product_id = p.id INNER JOIN warehouse w ON s.warehouse_id = w.id WHERE s.warehouse_id = 4151 AND pvi.shipping_order_id IS NOT NULL AND pvi.inv_txn_type_id IN (270, 80) AND p.brand IN ('HK', 'HealthKart', 'Incredio', 'Healthviva','MuscleBlaze','Nouriza','TrueBasics','TheProteinZone','Gritzo');


File gets downloaded along with folder creation.

**Comment by rohan-morje** [comment]
resolved
