### ISSUE TITLE
Success/Failure message for SMS not displayed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#897]
Actual result
Success/Failure message for SMS not displayed.

Expected result
Success/Failure message for SMS should be displayed.

![image](https://user-images.githubusercontent.com/54023516/70977383-d0b60700-20d3-11ea-86e2-18e8f37ba312.png)

**Comment by shivam-kurtarkar** [comment]
expected message "message Email sent.Failed to send SMS"

**Comment by larissa-c-d** [comment]
Issue resolved.
