### ISSUE TITLE
adminDownload folder is not created when Download Pincode XLS button 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#898]
![image](https://user-images.githubusercontent.com/14803102/70982612-4bcfeb00-20dd-11ea-88d0-4fe439a2b3f4.png)

**Comment by Shraddhar23** [comment]
Uses adminUploads folder in the code which does get created and the file also gets downloaded.

![Screenshot 2019-12-20 at 9 59 27 AM](https://user-images.githubusercontent.com/48199171/71230388-7608ef00-230f-11ea-8ec0-87f277d3be53.png)
