### ISSUE TITLE
adminDownload folder is not created when Download Courier Excel button is clicked

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#899]
![image](https://user-images.githubusercontent.com/14803102/70983347-969e3280-20de-11ea-822f-3a36965d206a.png)

https://aqua137.healthkartqa.com/admin/courier/ChangeDefaultCourier.action

**Comment by Shraddhar23** [comment]
Uses adminUploads folder path which does get created and the file also gets downloaded.

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/71253693-9c01b400-234e-11ea-9253-8cad64f10858.png)

**Comment by rohan-morje** [comment]
Uses adminUploads folder path which does get created and the file also gets downloaded.
