### ISSUE TITLE
UI not as per Wireframes

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#90]
Go to http://bright61.healthkartqa.com/admin/inventory/MinimumInventoryConfig.action
Minimum Inventory Configuration > Go  to Global tab and observe

![image](https://user-images.githubusercontent.com/14803102/47338050-10da4f00-d6b4-11e8-8d97-2fd86fbe7c15.png)
![image](https://user-images.githubusercontent.com/14803102/47338147-6f073200-d6b4-11e8-8644-c48d85039ea6.png)

Go  to Zone tab and observe
![image](https://user-images.githubusercontent.com/14803102/47338243-bdb4cc00-d6b4-11e8-9df7-6469d70fc8a4.png)
![image](https://user-images.githubusercontent.com/14803102/47338489-b9d57980-d6b5-11e8-830b-32601ac4fc33.png)

**Comment by ambksud** [comment]
Issue Fixed
![fixed new](https://user-images.githubusercontent.com/44572706/47835193-abc7dd00-ddc8-11e8-99b2-b7123e792bff.PNG)
![fixed new](https://user-images.githubusercontent.com/44572706/47835201-b4b8ae80-ddc8-11e8-8faf-ec165f4a7a3e.PNG)
