### ISSUE TITLE
Https 404 Not found error displayed when opening PDF link  https://aqua137.healthkartqa.com/admin/inventory/PO.action

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#904]
https://aqua137.healthkartqa.com/admin/inventory/PO.action
Click on PDF link and observe

![image](https://user-images.githubusercontent.com/14803102/70990513-b12ad880-20eb-11ea-9e7a-8bb4fa9f31a1.png)

**Comment by Shraddhar23** [comment]
PDF file opens on 145 server.
The folder path used is distpath.

**Comment by rohan-morje** [comment]
Could not download pdf , could not check Download folder creation
Error occured while downling pdf
![image](https://user-images.githubusercontent.com/14803102/71253232-55f82080-234d-11ea-8544-aa2e0ef8d862.png)
