### ISSUE TITLE
HTTP Status 500 – Internal Server Error is displayed on click of Update button.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#912]
Actual result
HTTP Status 500 – Internal Server Error is displayed on click of Update button.

Expected result
Folder adminUploads should get create automatically if the folder does not exists.

**URL**:https://aqua145.healthkartqa.com/admin/shipment/ParseActualCourierShipmentChargeExcel.action

`HTTP Status 404 – Not Found
Type Status Report

Message /pages/admin/updateActualCourierShipmentCharges.jsp

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/8.5.20`

**Comment by Shraddhar23** [comment]
adminUploads folder gets created on click of update after attaching the sample Excel file.

**Comment by rohan-morje** [comment]
resolved
