### ISSUE TITLE
sms not received  but the SMS sent message is displayed on POS screen

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#916]
Actual result
sms not received but the SMS sent message is displayed on POS screen

Expected result
 SMS should be received

![image](https://user-images.githubusercontent.com/54023516/71235452-3a2b5500-2322-11ea-98cc-92ee95b5c1ab.png)

`	... 77 more
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:33) (GSTInvoiceServiceImpl.java:419) - Ajency.in :: new pdf created : /usr/local/projects/tomcat_aqua_new/webapps/ROOT/gstInvoicePDF/SO_5925078_1576823673823.pdf
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:33) (GSTInvoiceServiceImpl.java:446) - Ajency.in :: uploading to s3 with file key: gstInvoicePDF/2019/Dec/SO_5925078_1576823673823.pdf
[ INFO] [] [Thread-15] (20 Dec 2019 12:04:34) (MailBoltServiceImpl.java:37) - Ajency.in :: post response com.hk.rest.response.GenericResponse@108964de
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (GSTInvoiceServiceImpl.java:451) - Ajency.in :: successfully uploaded to upload pdf to aws gstInvoicePDF/2019/Dec/SO_5925078_1576823673823.pdf
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (GSTInvoiceServiceImpl.java:459) - Ajency.in :: saved to sogstInvoiceHistory table , id:218
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (POSAction.java:3250) - Ajency.in :: sending link for so 5925078 to customer true from store 4057
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (GSTInvoiceServiceImpl.java:635) - Ajency.in :: user login : MOB_8B4abY1575872303978
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (GSTInvoiceServiceImpl.java:644) - Ajency.in :: customer invoice url : http://aqua61.healthkartqa.com/core/accounting/GSTInvoiceDownload.action?customerInvoiceAsPdf=&gatewayOrderId=5925078-S06599&user=CwqwNarWyUa8SXHKJRhHAA%253D%253D
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (GSTInvoiceServiceImpl.java:135) - Ajecny.in :: [DEBUG] 6 : true
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (GSTInvoiceServiceImpl.java:538) - Ajecny.in :: [DEBUG] failing ...
[ERROR] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (POSAction.java:3260) - Ajency .in :: Failed to send Email to user: 16138317for shipping order gateway id 5925078-S06599
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (GSTInvoiceServiceImpl.java:140) - Ajecny.in :: [DEBUG] 5 : false
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (NpsSmsServiceImpl.java:67) - saving particular customer to the npsSmstrigger table9552519582
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (NpsSmsServiceImpl.java:77) - Saved Data to nps Sms Trigger table
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (GSTInvoiceServiceImpl.java:596) - Ajency.in :: sending link http://aqua61.healthkartqa.com/core/accounting/GSTInvoiceDownload.action?customerInvoiceAsPdf=&gatewayOrderId=5925078-S06599&user=CwqwNarWyUa8SXHKJRhHAA%253D%253D sms to mobile no: 9552519582
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (GSTInvoiceServiceImpl.java:606) - Ajency.in :: making jarvis call for sending sms to the customer [8051] no:9552519582
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:37) (MailBoltServiceImpl.java:34) - Send sms url http://192.168.70.133:4040/sms/send/transactional?z.ts==1576823677671&st=1
[ INFO] [] [http-nio-8181-exec-109] (20 Dec 2019 12:04:38) (MailBoltServiceImpl.java:37) - Ajency.in :: post response com.hk.rest.response.GenericResponse@4edbb4f6
`

**Comment by shivam-kurtarkar** [comment]
force fail debug
