### ISSUE TITLE
Images in the email content not displayed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#919]
Actual result
![image](https://user-images.githubusercontent.com/54023516/71240114-53d29980-232e-11ea-8815-b93c4cc60cc3.png)

Expected result
![image](https://user-images.githubusercontent.com/54023516/71240279-ba57b780-232e-11ea-9efe-5e93340348e9.png)

**Comment by shivam-kurtarkar** [comment]
mark not spam

**Comment by larissa-c-d** [comment]
issue resolved
