### ISSUE TITLE
Feedback link in the email not clickable.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#920]
Actual result
Feedback link in the email not clickable.

Expected result
Feedback link in the email should be clickable.

![image](https://user-images.githubusercontent.com/54023516/71244186-f80d0e00-2337-11ea-9393-4318b7b622e5.png)

**Comment by shivam-kurtarkar** [comment]
if gmail marks it as spam then all hrefs and src are removed mark it as not spam to see original

**Comment by shivam-kurtarkar** [comment]
if gmail marks it as spam then all hrefs and src are removed mark it as not spam to see original

**Comment by larissa-c-d** [comment]
issue resolved
