### ISSUE TITLE
Column remaining inventory live should be renamed to Inventory.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#928]
Actual result
column name is Remaining Inventory Live.

Expected result
Column name should be renamed to Inventory.

Steps
Go to the POS screen

![image](https://user-images.githubusercontent.com/54023516/71460079-60446f80-27d0-11ea-9485-353413bb01eb.png)

**Comment by legred21** [comment]
fixed

**Comment by larissa-c-d** [comment]
Issue resolved
