### ISSUE TITLE
Remaining inventory not displayed on the base order page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#932]
Actual result
Remaining inventory not displayed on the base order page.

Expected result
Remaining inventory should be  displayed on the base order page.

![image](https://user-images.githubusercontent.com/54023516/71461995-e31cf880-27d7-11ea-9d2c-631af17ebfcc.png)
![image](https://user-images.githubusercontent.com/54023516/71462015-f4660500-27d7-11ea-8a07-fc0d7a77bb8c.png)

**Comment by legred21** [comment]
under "shipping order details" column "view details" link is provided which displays order details in new tab

**Comment by legred21** [comment]
check on master
