### ISSUE TITLE
Order id not displayed on click of view details on the BO page and SO page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#934]
Actual result
Order id not displayed on click of view details on the BO page and SO page.

Expected result
Order id should be displayed on click of view details on the BO page and SO page.

![image](https://user-images.githubusercontent.com/54023516/71462405-317ec700-27d9-11ea-9955-db5762e165af.png)

**Comment by legred21** [comment]
Fixed
