### ISSUE TITLE
Quantity column should be renamed to checked out quantity in the pos_line_item table.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#937]
Expected  result
Quantity column should be renamed to Checked out quantity in the pos_line_item table.

![image](https://user-images.githubusercontent.com/54023516/71464397-3fcfe180-27df-11ea-9adc-5d82c13233b4.png)

**Comment by legred21** [comment]
fixed

**Comment by larissa-c-d** [comment]
issue resolved
