### ISSUE TITLE
Select All checkbox to select all the payment modes not displayed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#939]
Actual result
Select All checkbox to select all the payment modes not displayed.

Expected result
Select All checkbox to select all the payment modes should be displayed on the create/edit retail store page.

Screenshot
Create retail store 
![image](https://user-images.githubusercontent.com/54023516/71669089-8f8b4b80-2d91-11ea-8d8d-2b09ab38df5e.png)
Update retail store 
![image](https://user-images.githubusercontent.com/54023516/71669133-af227400-2d91-11ea-8a6d-bd706ba5c55d.png)

**Comment by rohan-morje** [comment]
As mentioned in ETA, select All option not required
