### ISSUE TITLE
'number of items in the order' column is not present in the order details table displayed on the UI.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#940]
**Actual result**
'number of items in the order' column is not present in the order details table displayed on the UI.

**Expected result**
'number of items in the order' column should be  present in the order details table displayed on the UI.

**Screenshot**
![image](https://user-images.githubusercontent.com/54023516/71708513-fa7f6580-2e17-11ea-8401-ab730de44006.png)

**Comment by legred21** [comment]
Fixed
