### ISSUE TITLE
Status column should be changed to 'Order Status' 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#941]
**Expected result**
Status column should be changed to 'Order Status' 

**Screenshot**
![image](https://user-images.githubusercontent.com/54023516/71708513-fa7f6580-2e17-11ea-8401-ab730de44006.png)

**Comment by legred21** [comment]
Fixed

**Comment by larissa-c-d** [comment]
Issue resolved.
