### ISSUE TITLE
All the  payment modes selected on the create/edit a retail store page are not displayed in the dropdown on POS. 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#947]
Actual result:
All the  payment modes selected on the create/edit a retail store page are not displayed in the payment mode dropdown. 

Expected result
All the  payment modes selected on the create/edit a retail store page should be displayed in the payment mode dropdown. 

![image](https://user-images.githubusercontent.com/54023516/71721634-ce7dd780-2e4b-11ea-8e8f-86f185a4deba.png)
![Screenshot from 2020-01-03 17-08-26](https://user-images.githubusercontent.com/54023516/71721644-d5a4e580-2e4b-11ea-8b97-5eec9c29e02c.png)

**Comment by Shraddhar23** [comment]
All the payment modes are visible in the drop down.

![Screenshot 2020-01-05 at 6 33 08 PM](https://user-images.githubusercontent.com/48199171/71780546-e12e1300-2fe9-11ea-80b6-90efd309738e.png)

**Comment by larissa-c-d** [comment]
Swiggy payment mode should be visible only for specific users, but can be displayed issue raised #967
