### ISSUE TITLE
Internal Server error on saving the store after adding  payment mode

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#950]
OPen the retail store in edit mode
Select one payment mode (Paytm voucher ) and save it
Open the retail store again in edit mode 
Select onemore payment mode () Split payment 
and click on Sae details and observe

Internal Server error on saving the store after adding  payment mode

![image](https://user-images.githubusercontent.com/14803102/71725098-c4aea100-2e58-11ea-8f9f-6da6228898b4.png)

![image](https://user-images.githubusercontent.com/14803102/71725067-a183f180-2e58-11ea-80b1-bce431d1858b.png)
![image](https://user-images.githubusercontent.com/14803102/71725085-b2346780-2e58-11ea-8df5-c3ec6478c258.png)

**Comment by Shraddhar23** [comment]
Added all the payment modes one by one , no exception observed.

![Screenshot 2020-01-05 at 6 11 28 PM](https://user-images.githubusercontent.com/48199171/71780302-d02fd280-2fe6-11ea-843c-9b575db663cf.png)
