### ISSUE TITLE
retail store  created  not displayed on create assign warehouse page if vendor is Bright Lifecare Pvt Ltd

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#951]
Actual result
retail store created  not displayed on  assign warehouse page if vendor is Bright Lifecare Pvt Ltd

Expected result
retail store created should be displayed on  assign warehouse page. 

![image](https://user-images.githubusercontent.com/54023516/71725191-0b040000-2e59-11ea-94f0-55059bda4987.png)
![image](https://user-images.githubusercontent.com/54023516/71725227-2242ed80-2e59-11ea-8c8a-a786949ef40f.png)

**Comment by Shraddhar23** [comment]
Retail store with Bright vendor gets displayed on Aqua

![Screenshot 2020-01-05 at 6 05 27 PM](https://user-images.githubusercontent.com/48199171/71780235-ff920f80-2fe5-11ea-895b-e1b7d4f5e3f8.png)

![Screenshot 2020-01-05 at 6 05 20 PM](https://user-images.githubusercontent.com/48199171/71780236-03be2d00-2fe6-11ea-8741-f70c76a8d18b.png)

**Comment by larissa-c-d** [comment]
Issue resolved
