### ISSUE TITLE
payment mode is removed form Catalog page but still reflecting on POS screen

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#961]
Add payment mode Counter cash in Catalog and place th order
Remove the Counter cash payment mode from Catlog and open the POS screen and Observe

Payment mode "Counter cash is" reflecting on POS screen eve after removing if from Catalog page

![image](https://user-images.githubusercontent.com/14803102/71799076-4af5fd80-307a-11ea-820b-5c8b9afbb2fd.png)

![image](https://user-images.githubusercontent.com/14803102/71799115-6103be00-307a-11ea-8869-36bf9e942f63.png)

**Comment by Shraddhar23** [comment]
The mapping on Aqua for the payment mode was not updated as the Sync API was not working.
