### ISSUE TITLE
Payment mode not loading on POS screen for SIS store

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#963]
Go to POS screen
Select SIS store and Observe (Gold Gym Kandhivali East )

Actual result: Payment mode not loading on POS screen for SIS store

![image](https://user-images.githubusercontent.com/14803102/71801447-f86c0f80-3080-11ea-931f-bc57356324af.png)

**Comment by larissa-c-d** [comment]
Issue resolved
