### ISSUE TITLE
"Initiate Transaction FAILED, Please try Re-Initiating the Transaction " message should be changed to 'Initiated Transaction FAILED, Please try Re-Initiating the Transaction.'   

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#981]
Actual result
"Initiate Transaction FAILED, Please try Re-Initiating the Transaction " (message displayed if the initiate transaction cal fails )

Expected result
'Initiated Transaction FAILED, Please try Re-Initiating the Transaction.'    

![image](https://user-images.githubusercontent.com/54023516/71955593-b7a20100-320e-11ea-8c0c-0c4a112e43b0.png)

**Comment by sharangsamonkar** [comment]
Changed to "Failed to Initiate Transaction, please try again."

**Comment by larissa-c-d** [comment]
PLEASE APPROVE OPEN TXN FIRST [ExistingReferenceId:53625, Amount:295900] should be change to Approve open transaction first.

**Comment by larissa-c-d** [comment]
Issue resolved
