### ISSUE TITLE
"Error occurred while getting transaction status." message is displayed on click of Get status

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#983]
Actual result
"Error occurred while getting transaction status." message is displayed on click of Get status button.

Expected result
Transaction status should be  displayed on click of Get status button.

![image](https://user-images.githubusercontent.com/54023516/71957739-917f5f80-3214-11ea-9655-9f24157f001b.png)

**Comment by shivam-kurtarkar** [comment]
the message is if api call fails
