### ISSUE TITLE
New entry is made in the customer_order_transaction table each time the payment transaction id is changed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#988]
Actual result
New entry is made in the customer_order_transaction table each time the payment transaction status is displayed

**steps**
Scan a barcode 
choose the payment mode as UPI via EDC machine 
Click on initiate transaction 
Click on cancel transaction
 
![image](https://user-images.githubusercontent.com/54023516/71969740-4b82c580-322d-11ea-8c58-3d8ceb379b2f.png)

**Comment by sharangsamonkar** [comment]
Not an issue. New entry is made every time we initiate a transaction.
