### ISSUE TITLE
If the order is cancelled all the entries for the transaction are set to failed status.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#989]
Actual result
If the order is cancelled all the entries for the transaction are set to failed status.

Steps
scan a barcode 
click on initiate transaction button.
click on cancel 
Click on initiate transaction button
Click on cancel
![image](https://user-images.githubusercontent.com/54023516/71971191-188e0100-3230-11ea-8308-ef3a8d29c256.png)
![image](https://user-images.githubusercontent.com/54023516/71971216-2ba0d100-3230-11ea-8f90-0129049844a5.png)

**Comment by sharangsamonkar** [comment]
Not an issue. Functionality.
