### ISSUE TITLE
The transaction is cancelled when the payment debug key for cancel is false.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#990]
Actual result
The transaction is cancelled when the payment debug key for cancel is false.

Expected result
The transaction should not be cancelled if the payment debug key for cancel is false.

![image](https://user-images.githubusercontent.com/54023516/71973034-e7afcb00-3233-11ea-82ce-43d2ce14b62c.png)
![image](https://user-images.githubusercontent.com/54023516/71973071-fac29b00-3233-11ea-849b-2484fda354e3.png)

**Comment by shivam-kurtarkar** [comment]
true or false

**Comment by shivam-kurtarkar** [comment]
forcePinelabsInitApiCall is global flag for init cancel and void
