### ISSUE TITLE
"Error occurred while getting transaction status" message is displayed when transaction successful is displayed in the customer_order_transaction table.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#992]
Actual result
"Error occurred while getting transaction status" message is displayed when transaction successful is displayed in the customer_order_transaction table.

Expected result
"Transaction Success " message should be displayed on on click of get status if the transaction is successful.

**Steps**
Scan a barcode 
Click on initiate transaction
Click on get status
Check the order status in the customer_order_transaction table.

![image](https://user-images.githubusercontent.com/54023516/71974105-ab319e80-3236-11ea-9c7e-057afcb67710.png)
![image](https://user-images.githubusercontent.com/54023516/71974133-b7b5f700-3236-11ea-9d5d-da9816a92ca4.png)

**Comment by sharangsamonkar** [comment]
Need to check again.
