### ISSUE TITLE
Customer order gateway order id is not displayed in the table on the open UI transaction page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#995]
Actual result
Customer order gateway order id is not displayed in the table on the open UI transaction page.

Expected result
Customer order gateway order id should be displayed in the table on the open UI transaction page.

![image](https://user-images.githubusercontent.com/54023516/71977937-1c298400-3240-11ea-98d9-8ca05c6c77e3.png)

**Comment by sharangsamonkar** [comment]
Have added order transaction id. This should be enough to identify the payment

**Comment by sharangsamonkar** [comment]
Removed customer order id as well
