### ISSUE TITLE
PTRID should be displayed on the POS screen after the transaction is successful.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#998]
Actual result
PTRID not displayed on the POS screen, after the transaction is successful.

Expected result
PTRID should be displayed after the transaction is successful.

![image](https://user-images.githubusercontent.com/54023516/72038479-876a6900-32c7-11ea-94dc-1c90abccade2.png)

**Comment by sharangsamonkar** [comment]
PTRID should be shown when transaction is open.
