### ISSUE TITLE
"Initiate Transaction FAILED, Please try Re-Initiating the Transaction. Failed to get pinelabs config"  message is displayed on the POS Screen.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#999]
**Store:** FBD Eros Mall
Scan a barcode 
select payment mode as UPI via EDC machine.
click on initiate transaction

Actual result
"Initiate Transaction FAILED, Please try Re-Initiating the Transaction. Failed to get pinelabs config"  message is displayed on the POS Screen.

Expected result
Initiate transaction button should not be displayed if there is no pinelabs configuration for the store.

![image](https://user-images.githubusercontent.com/54023516/72040248-f1860c80-32cd-11ea-8098-247d1b21d158.png)

**Comment by sharangsamonkar** [comment]
@shivam-kurtarkar In this case only failed to get pinelab config should be shown.

**Comment by sharangsamonkar** [comment]
Not an issue. Pinelabs config is fetch only when we make the call. If we hide it initially then the user won't know that the button are not shown because of missing pinelabs config.
